export const kissPrompts = [
  'Small kisses littered across the other’s face.',
  'A small, fleeting kiss - which is immediately followed by a passionate, hungry kiss.',
  'A breathy demand: “Kiss me” - and what the other person does to respond.',
  'An accidental brush of lips followed by a pause and going back for another, on purpose.',
  'Throwing their arms around the other person’s neck, hugging them close before kissing them passionately on the lips.',
  'Wild, breathless kisses brought on by a heartfelt gift.',
  'French kisses where they trace every tooth with their tongues as though trying to memorize them.',
  'Laying a gentle kiss to the back of the other’s hand.',
  'A kiss that lasts so long, they are sharing each other’s breaths.',
  'A hello/good-bye kiss that is given without thinking - where neither person thinks twice about it.',
  'Morning kisses that are exchanged before either person opens their eyes, kissing blindly until their lips meet in a blissful encounter.',
  'Sneaking away to a hidden corner to share a secretive kiss.',
  'Butterfly kisses against the other’s cheeks.',
  'A kiss so desperate that the two wind around each other, refusing to let go until they are finished.',
  'A fierce kiss that ends with a bite on the lip, soothing it with a lick.',
  'One person pouting, only to have it removed by a kiss from the other person.',
  'Tucking their hands beneath the other person’s shirt, just to watch them break the kiss and gasp in surprise at the sensation of cold/warm hands on their skin.',
  'Teasing kisses where one person blows air into the other’s mouth and runs away.',
  'One person stopping a kiss to ask “Do you want to do this?”, only to have the other person answer with a deeper, more passionate kiss.',
  'Kissing in a stairwell, giving them an artificial height difference.',
  'A chaste kiss given to each other because they are in mixed company.',
  'A kiss that is leading to more, but is interrupted by a third party.',
  'A kiss that tastes of the food/dessert they are eating.',
  'Deep kisses where they have their hands tangled in each other’s hair to pull them closer.',
  'Wet kisses after finding refuge from the rain.',
  'Brushing a kiss along the shell of the other person’s ear.',
  'Kisses exchanged while one person sits on the other’s lap.',
  'One person tracing the other’s lips with a fingertip until they can’t resist any longer, tilting their chin towards them for a kiss.',
  'Staring at each other’s lips for a moment before moving closer, as if drawn together by some unseen force.',
  'Weak, sweaty kisses because it’s unbearably hot.',
  'Pulling away from a kiss, whispering words of love against each other’s lips.',
  'A kiss so passionate, so perfect - that after they part, neither person can open their eyes for a few moments afterwards.',
  'An unexpected kiss that shocks the one receiving it.',
  'Kisses that start on their fingers and run up their arm, eventually ending on their lips.',
  'An awkward kiss given after a first date.',
  'Starting with bunny kisses before moving on to soft kisses.',
  'Cleaning the other person’s lips with a lick and a kiss.',
  'Whispering “I love you” before a chaste, delicate kiss.',
  'Kissing tears from the other’s face.',
  'A gentle kiss that quickly descends into passion, with little regard for what’s going on around them.',
  'Kisses shared under an umbrella.',
  'Distracting kisses from someone that are meant to stop the other person from finishing their work, and give them kisses instead.',
  'A kiss pressed to the top of the head.',
  'Tentative kisses given in the dark.',
  'Kisses exchanged as they move around, hitting the edges of tables or nearly tripping over things on the floor before making it to the sofa, or bed.',
  'A lingering kiss before a long trip apart.',
  'A kiss paired with a tight hug, knocking the breath out of the person being hugged.',
  'One person has to bend down in order to kiss their partner, who is standing on their tip-toes to reach their partner’s.',
  'Short and sweet kiss after meeting up for a date.',
  'A kiss, followed by more that trail down the jaw and neck.',
  'whispering “kiss me” to your lover',
  'wrapping your arms around your lover’s neck',
  'kisses that travel from your lover’s nose to their lips',
  'breaking the kiss but instantly pressing your lips back together',
  'intertwining your fingers',
  'kisses that start out gentle but grows more passionate',
  'forehead against forehead',
  'running your fingers through your lover’s hair',
  'unbuttoning your lover’s shirt, pressed against the wall',
  'surprise kisses, in which your lover weren’t prepared for it but responds immediately',
  'a kiss in which, “we’re late for work but let’s be later”',
  'kisses shared under a waterfall',
  'pulling your lover closer by the waistband',
  'kissing under the stars',
  'messy kisses, destroying furniture trying to reach the bed',
  'a kiss that isn’t meant to happen but it does anyway',
  'sliding your hands down your lover’s chest',
  'grabbing your lover by the collar',
  '“if we get caught kissing we’re dead but let’s risk it”',
  'hand kisses',
  'exploring each other’s lips',
  'smiling in-between kisses',
  'now-or-never kisses',
  'caressing your lover’s cheek',
  'good night kisses',
  '“i was supposed to take a shower alone but sure, jump right in”',
  'brushing your lips together, lingering for a moment',
  'an accidental kiss between two exes',
  'kisses in which, you’ve already said goodbye but can’t help stealing another one',
  'this might be our last kiss ever so let’s make it last',
  'kitchen counter make-outs',
  'jumping into your lover’s arms',
  'soft kisses while cuddling in bed',
  'i missed you kisses',
  'a kiss that leave you breathless',
  'stopping a kiss when it gets too heated',
  'a kiss on the cheek turns into a kiss on the lips',
  'trailing kisses from your lover’s lips to their neck',
  '“everything is going to be okay” kisses',
  'kisses that start of passionate but grows more delicate',
  'pulling away from a kiss to look at each other, then smiling as you dive in for another kiss',
  'wrapping your legs around your lover’s body as they lift you',
  'a goodbye kiss, but neither of you can quite let go',
  '“we shouldn’t do this” but they do so, anyway',
  'a swirling reunion kiss',
  '“i’ve had a terrible day at work so just kiss me”',
  'a kiss that lasts longer than it should',
  'tending to your lover’s wound, placing a kiss on top of their head, grateful they’re still alive',
  'spinning your lover into a kiss on the dance floor',
  'kisses in which, i can’t believe this is real, but i love you so much',
  '{A} and {B} share a light kiss.',
	'{B} and {A} share a passionate kiss.',
  '{B} and {A} touching their foreheads against each other, sharing kisses.',
  '{A} and {B} recreating their first kiss.',
  "{B} kissing away {A}'s tears.",
]