const nsfwPrompts = [
	'{A} and {B} sending each other nudes.',
	"{A} and {B} enjoying a night of stargazing. Things are going well and they start to kiss/make out when a storm hits. Instead of seeking shelter from the rain, they make love under the night sky, not caring if they're drenched, just caught up in the moment of passion itself.",
	"{B} and {A} staying at a hotel outside of town for a lazy, romantic weekend, most of which they spend nude. {B} decides that they feel too comfortable and doesn't want to get up to go out for food, so {A} decides to order out for them and get dressed just enough to meet the delivery person at the door. While {A} is accepting the order, {B} wraps up in a sheet and comes up behind them, smug as both {A} and the delivery person become flustered.",
	'{A} comes home to find {B} sleeping on top of the covers... completely naked.',
	"{B} handing {A} a bowl of cream/chocolate/honey and telling them to spread them on their own body where they want it licked off by {B}. {A} eagerly complies, and everything starts (or ends) with a sloppy smear on {A}'s lips.",
	'{A} and {B} both buy lingerie and try to surprise one another with it on the same night.',
	'{B} leaning close to whisper something dirty {A}.',
	'{A} and {B} sending each other nudes.',
	'{B} moving their hand increasingly farther up {A}/s inner thigh while {A} is driving.',
	'{A} and {B} own a store together and on a particularly slow day, {B} finds themself pinned up against a wall in the stockroom by {A}.',
	'{A} and {B} showering together for the first time, having pure intentions that are eventually forgotten, leading to steamy shower sex.',
	'{A} and {B} have a long night of incredible, hot sex. It gets intense, and a little rougher than usual. The next morning, {A} wakes up holding {B} and notices bites and bruises they left all over their body. {B} wakes up and is a little sore and achy but very satisfied and happy with the night before. {A} is having guilt over the visible marks and {B} has to reassure them that it’s okay (and maybe even that they enjoyed it).',
	'{A} and {B} playing a game unknown to the people around them, in which {A} gradually moves their hand up {B}’s leg. The game is to see how far up {A} will let {B}’s hand get between their thighs before they chicken out and stop them.',
	'{B} buying sexy lingerie and having a boudoir photoshoot for {A}.',
	"It's summer and {B} decides to wear sundresses (and nothing else) so they can ride {A} anytime.",
	"Imagine {A} fucking {B} so good that {B} can't even get a full word out, only moans and half-uttered curses.",
	'{A} and {B} participating in No Nut November, but each of them are purposely making it very difficult for the other to succeed.',
	'{A} giving {B} VERY visible hickeys.',
	'Imagine{A} and {B} being new to dating and decide to take it one step farther in the bedroom. Due to them being so inexperienced, there is a lot of shyness, giggling, and blushing when it comes to sex.',
	"{A} fucking {B}'s mouth.",
	'{A} and {B} own a store together and are making out on the counter on a particularly slow day when a customer comes in. {A} stands to help the customer while {B} hides under the counter. {A} has to retain their composure while {B} starts to go down on them passionately.',
	'{A} and {B} both had a very long, frustrating day. When the two of them are home and alone together, they decide to fuck out their frustration, which ends with them both being calmer than they were before.',
	"{B} handcuffs {A} to their bed and rides them whilst only wearing {A}'s shirt.",
	'strong>{A} talking to someone on the phone, when {B} strips naked and sits on their lap, kissing their neck to distract/fluster them.',
	'{A} and {B} watching a movie when a sex scene comes on. {A} looks over at {B}, who is resting on their shoulder. {A}pauses the movie as {B} finds themself being kissed passionately by {A} and they have sex on the couch.',
	'{A} and {B} decide to exchange two sets of gifts for their holiday of choice; one suitable for public consumption, one not (be it lingerie, toys, etc). {A} however, mixes up which package iw which after wrapping, and puts the wrong one under the tree for the family opening of presents.',
	'Imagine {A}, the one who usually enjoys slow and romantic sex, begging {B} to fuck them so hard that they forget their name.',
	"{A} spits in {B}'s mouth. Why? That's up to you, friendo.",
	'Write what happens the first time {A} makes {B} cum.',
	"{B} finds out that {A} is a virgin (or hasn't had sex in a long while, and thus is practically virginal) and finds {A}'s overwhelm to be a huge turn-on.",
	'{A} wants {B} to try something {B} finds highly embarrassing. {B} reluctantly agrees.',
	'{B} talks dirty to {A}. And I mean, like, DIRTY. Make yourself cringe.',
	'{A} and {B} are in a Dominant/submissive relationship. {A} is in the midst of training {B} to cum on command. {B} wants to cum so badly...',
	'{A} and {B} are both interested in dominating the other. Uh-oh. How does that work out for them?',
	'{B} gets {A} a dirty present: a sex toy, lingerie, leather, etc. Excited, {A} uses the present immediately.',
	"{A} and {B} haven't fucked yet, and need to have a conversation about who's topping and who's bottoming...",
	'{A} and {B} look at porn together.',
	'{B} discovers {A} is hiding something under their clothes: a beautiful, fragile, highly sensitive pair of wings.',
	'{A} is touch-starved, and {B} finds more and more reasons to touch {A}.',
	'{B} has a tattoo kink. {A} is a willing canvas.',
	"{A} can't cum without being lightly choked. Is {B} into that?",
	'{B} revisits some sexts from {A} and gets so turned on, they initiate another round. (Bonus points if the encounter stays totally over text, but you do you.)',
	"{A} isn't really into penetrative sex but adores giving oral sex. {B} doesn't mind.",
	"{B} gets hyper aroused when {A} teases and lovingly humiliates them. {B}'s embarrassed by this, and of course {A} uses that fact against them.",
	'Ageplay. Occasionally {A} seems to be acting a little immature, especially after sex. Finally {B} realizes {A} is age regressing. {B} wonders if {A} wants to be little during sex, too, and puts it to the test.',
	"{A} and {B} can't wait for privacy, so they find a way to touch each other while out in public.",
	"{B}: Open your legs, {A}. I won't tell you again.",
	'{A} finds {B} has been dosed with a strong aphrodisiac.',
	'{B} loves to cross-dress but has only done it in private. {A} discovers their secret penchant and shockingly loves it. Bonus points: {B} lets {A} dress them from head to toe.',
	'Holy shit. {A} finds out {B} has a piercing in a very intimate place.',
	"{B} loves to worship {A}'s body, sometimes for hours, stripping {A} slowly, kissing and licking and showering {A} with praise and adoration.",
	'{A} loves to make {B} gape and uses a large dildo on {B} to make it happen.',
	'{A} fingers {B} before an outing, till {B} is wet and very horny. The whole outing, {A} teases and taunts {B} about how bad they need to cum, keeping {B} needy and turned on.',
	'{A} and {B} 69, both of them trying not to cum too fast.',
	'{B} is secretly very sensitive to touch, a fact they try to hide. {A} discovers it on accident and is thrilled with how much their touch affects {B}.',
	"{A} is in love with {B}, but it's completely unrequited. So how exactly did {B} and {A} wind up in bed together?",
	'{A} helps {B} shave.',
	'{B}. {A}. Sex pollen.',
	'{A} and {B} are making out, and it has become a competition. Each try to get the other to be the first to snap and use their hands. Playful competition? A bet? A matter of pride? Please, I wanna know what happens!',
	'{B} and {A} are trying to outlast each other, staving off their own orgasms but trying hard to make each other lose it.',
	"Shhh. {A} and {B} are hooking up somewhere they shouldn't be. It's a struggle to stay quiet, especially when people are so close by and the thrill of getting caught gets {B} so excited, they're biting back moans.",
	"Detailed oral. Write {A} going down on {B}, and don't skimp on the action or the sensory details: How {B} tastes or smells, the heat and flush of their aroused body parts, the spreading wetness, {A}'s own excitement. Go for it!!",
	'{B} fingering {A} with patient dedication, determined to make {A} cum with fingering alone.',
	"Cum play - so slippery on {B}'s skin. {A} loves the feel of it, how it looks, its sticky, sloppy shine.",
	"{A} and {B} only have a minute and can't do more than grope. Who grabs what?",
	'{B} rides {A} hard, skin slapping, thighs straining, and all {A} can do is hang on for the ride, encouraging {B} to make themselves cum. (Strap-on absolutely welcome.)',
	'{B} wears a lace thong for {A}.',
	"{A} likes to genderbend, and flirts with {B} while bent. What does {B} think of {A}'s genderfuckery? Is it startling? Intriguing? Arousing?",
	"Turns out {B} just doesn't really like to get naked.  They're very here for sex.  Just... not naked.  {A} might find this a little puzzling, but they're supportive, and {B} lets {A}'s hands into their clothes - and more.",
	"{A}'s going commando. Does {B} know? Did {B} tell {A} to lose the underwear? Or does {B} discover {A}'s lack of underwear on their own?",
	"No matter the partner, {A} loves a beautiful chest, and wants to look at, touch, and taste {B}'s.",
	"{A}'s got an oral fixation. {B} lets {A} suck on their fingers... amongst other things.",
	'Morning sex. {A} and {B} wake up in bed together.  Hands wander.  Lips meet.  The sheets twist around them as {B} rolls on top of {A}, sleep-warm and turned on.  What happens next?',
	"{A} is both tasteful and tactile, and loves for {B} to wear silk, satin, and/or lace. {B} complies, and {A} can't keep their hands off {B}.",
	"Clothes come off, and {B} is wearing a pair of cartoon underoos. {A} probably ought to laugh, but instead they're incredibly aroused.",
	"Hair play. {A} has a habit of touching {B}'s hair. Running their fingers through it. Smoothing it, messing it up. Before long {A} wants to brush it, pull it, wash it... whatever floats your boat. (This can be an act of caretaking, foreplay, sensation play, domination/submission... the list goes on. Do it your way.)",
	"{B} rims {A}, eating {A}'s ass like the juicy peach it is, and loves it.",
	"{A} has to borrow an item of clothing from {B} (hastily getting dressed in the morning? caught in bad weather? dressing for an occasion? your choice!), and they're both surprised by the intense, possessive thrill {B} gets from the sight of {A} in their clothes. The clothing either stays on during the urgent sex that ensues, or special attention is given to how it's removed.",
	"{A} has a thing for armpits. Maybe it's the musk, the sweat.  Maybe it's the vulnerability of this ticklish crook in the body.  Maybe it's the smooth curve or the way it's shaved, or the pit hair itself. {A} wants nothing more than to bury their face into {B}'s pit. Love to see how that goes. Please oblige.",
	'{B}: P-please, {A}, please, can I cum?',
	"Smell kink. The scent of {B} is enough to make {A} weak in the knees. {A} can't help but put their nose into {B}'s neck and take a deep whiff. Instant arousal.",
	"{A} is usually confident and open talking about what they like or want to try in bed, but {B} stumbles upon the one thing that {A} obviously enjoys but gets embarrassed about loving. Coaxing {A} to admit they enjoy it, or explain why it's an unusually intense button for them, becomes too fascinating for {B} to let go.",
	"{A} sarcastically says, 'Yes, Sir,' and {B} almost cums on the spot. Who knew?",
	"{B} is not on their best behavior. {A} decides {B} needs a spanking. For real. {B} is astounded by {A}'s conclusion, and by the way they are suddenly turned over {A}'s knee. Pants up? Pants down? Can't wait to find out.",
	'{A} and {B} have been apart for too long. The reunion sex is explosive after so much pent up need.',
	'{A} and {B} have tender reunion sex.',
	"{B} is {A}'s good little cockwarmer. (Strap-ons count!) They relax together while {B} keeps {A}'s junk snug and warm in their mouth.",
	"Praise kink. {A} is good in bed, and when {B} praises {A} about it, {A} gets so elated and aroused they're practically dripping. {B} keeps praising {A} and the sex gets off the charts good.",
	"{A} watches {B} strip. It's not for a sexual reason, but {A} becomes aroused anyway.",
	"{B} watches {A} strip, knowing they're about to have sex.",
	"At first it was just that neither of them wanted to hang up, but {A} and {B} stay on the phone so long that eventually they're listening to each other masturbate. Catching stifled gasps and sighs, both getting off on overhearing each other.",
	"{B} wants to try phone sex. {A} is not particularly into the idea, but is game to try, for {B}. On the phone, {B} ends up being shy. Meanwhile {A} is so good at phone sex, it's scary. {A} knows just what to say to drive {B} to the brink.",
	'{A} sexts {B} for the first time.',
	'{B} fucks {A} in front of a mirror and makes them watch as {B} takes them. Bonus points if {A} has a hard time looking and {B} grabs them by the hair or face to make sure they see themselves getting railed.',
	"{A} tenderly removes {B}'s shoes and kisses {B}'s feet. Can be in the context of worship, service, or humiliation. IDK - what do you think {B} gets out of it?",
	"Nothing's sexier to {A} than when {B}'s nipples are clamped. Even better when there's a chain on the clamps and {A} can pull it and get {B} to moan.",
	"{B}'s body is art. {A} tries to capture it in the nude, via drawing, photo, poem, or some other expression. {A} even tries to capture how sex with {B} feels in their chosen medium. #emotional",
	'{A} wants to watch {B} crawl.',
	'{A} puts {B} in a chastity device (belt, cage, garment) so no one else can touch {B}.  Not even {B} can touch {B}. Only {A}.',
	"{B} has to have {A}'s permission to cum.",
	'{A} and {B} watch each other masturbate.',
	'{A} sends {B} nudes. Is it an accident? Is it on purpose?',
	'Multiple orgasms. {B} is obsessed with making {A} cum repeatedly.',
	"There's just something about wearing stockings with garters that {A} loves. It feels so sexy to walk around with them on. {B} is a huge fan of how sultry and slutty stockings make {A}.",
	"{A} rides {B}'s face. {B} is in heaven with their mouth full of the taste of {A}. {B} doesn't let {A} stop, hanging on to {A} by the thighs.",
	'{B} and {A} share a shy first time. Bonus points if this shyness is very unexpected from one or both of them.',
	"One likes to fuck in a black silk teddy and high heels. The other likes to wear a suit. Who's wearing which outfit?",
	'{A} and {B} are in a luxury hotel, in a grand suite with a ginormous bed. Describe the room and bed, and describe what they do on the bed.',
	"{B} and {A} break the bed. Whoops. How'd that happen?",
	"Power's out. {A} and {B} make sweaty love by golden candlelight.",
	"{A} gets off on being called 'baby girl.' {B} calls {A} 'baby girl' shamelessly.",
	"{B} gets off on being called 'baby boy.' {A} calls {B} 'baby boy' shamelessly.",
	'{A} writes something lewd on {B} with ink. What does {A} write??',
	"{B} uses a magic wand vibrator on {A}. It's so powerful it overstimulates {A} quickly, but {B} doesn't stop till {A} cums.",
	'{A} bathes {B}, taking time to soap up each body part with thorough care, using soap in their preferred scent. {A} gets into every nook and cranny, hands wandering and rubbing, and rinses {B} clean. Then {A} gets {B} filthy again.',
	'{B} gets cloned somehow, and conspires with the original {B} to hook up with {A} together, at the same time. {A} is overwhelmed by all the hands bringing them pleasure.',
	'How did {A} get {B} into that maid outfit?',
	"{A} and {B} have been together for a while, but are taking it slow. They haven't had sex yet, for whatever reason. How do they proceed when the time is right?",
	"{B} is asexual but happily with {A}. {B} feels no sexual attraction, arousal, or need to have sex, but knows that {A} does, so {B} decides to seduce {A} and show them a great time, even if there's nothing in it for {B} outside giving {A} pleasure.",
	"{A} is blindfolded and at {B}'s mercy, feeling the things {B} wants them to feel and unable to see what's coming next.",
	'{B} is distracted by the need to be punished for a transgression, however real or imagined. {A} will take care of this. Bonus points in the zillions for aftercare!',
	'{B} makes {A} cum untouched.',
	'{A} is more of a giver in bed than a receiver. {B} enjoys being on the receiving end, but does wonder about it. Does {A} not like being touched? Or does {A} just not feel comfortable asking for what they really want in bed? {B} decides to pursue the issue. However this plays out is up to you.',
	"It's {A}'s birthday. {A} and {B} spend hours in bed doing whatever {A} wants.",
	'{B} and {A} find out they share the same taboo fantasy, and now they want to make it come true together.',
	'{B} is horny and wiggling around a lot while cuddling on the couch with {A}. {A} notices and encourages {B} to hump their hip or leg, touching them lightly just for guidance and telling them to make it feel good. Lots of encouraging {B} to get off, please!',
	"{A} has a hard time orgasming. Always has. It's an achievement, but when it happens, it isn't anything to write home about. Until {A} goes to bed with {B}, who excites them - mentally, emotionally, physically - so much they have the hottest sex of their life. (Whether {A} orgasms is your call. Maybe it's not the most important thing ever.)",
	'{A} loves to watch {B}. {A} watches {B} dress, undress, shower, masturbate, even do mundane chores. Does {B} know about this? You tell me.',
	"{A} wants to sexually submit to {B}, and {B} is down. {A} knows what filthy pet names they want to be called, but they don't know what {A} should call {B}. Sir? Master? Mommy? Daddy? My Liege...? What do they decide?",
	"Hypnosis kink. {A} helps {B} relax in bed with some soothing (and consensual) hypnosis. It works so well all of {B}'s inhibitions disappear.",
	"Hypnosis/CNC kink. {B} fantasizes about being hypnotized and taken advantage of while they're under. {A} agrees to try it out with them.",
	"{A} and {B} decide to sleep together for the first time, and it's awkward, full of embarrassing but sweet moments. Maybe {A} hits their head on something. Maybe {B} has to move {A}'s hands so {A} will touch them correctly. Maybe they require a lot of communication. The two laugh afterwards, talk it over, and decide to try again.",
	'{B} in nothing but a pair of little white cotton panties. How {A} responds to this is up to you.',
	"{B}: Not so fast, little one. You know you're supposed to call me Daddy.",
	"Five times {A} and {B} had 'platonic,' not at all serious sexual encounters, plus one time {A} caught feelings for {B}.",
	"{A} covers {B}'s throat in hickeys. Someone in {B}'s life comments about them. Little does this person know {B} also has hickeys elsewhere...",
	'{A} loves to watch {B} get fucked by other people.',
	'{B} gives {A} the messiest, most frantic oral ever, face shamelessly wet, mouth hungry and demanding.',
	'{A} gives {B} a thorough physical exam. (This scene can be part of a sexual roleplay scene, or a real situation where {B} needs to be looked over for injuries, etc.)',
	'{B} wakes up to {A} touching them.',
	"After an intense situation of your choosing, {A} comforts {B}. This turns into sex. {A} tries to be gentle, but {B} doesn't want it gentle. {B} wants {A} to be rough and demanding and fuck the intensity out of them. Bonus points for {B} being equally rough and demanding. Cathartic AF.",
	'{A} and {B} turn to each other for comfort in the midst of a difficult ordeal.',
	"{A} is a service sub who comes alive when they take care of {B}. When {B} has expectations of {A} that {A} can strive to meet. {B}'s not really sure about this situation, but since it seems to make {A} happy, {B} goes with it. After some growing pains, {B} settles into the new role and grows more comfortable taking the reins with {A}. Emphasis on {A} anticipating {B}'s needs, taking care of things for {B}, and living for every 'thank you' or scrap of approval. This can be a sexual or platonic situation.",
	"{B} has outrageously sensitive nipples. The slightest touch can be heaven or hell, depending. Perhaps {A} sucks {B}'s nipples tenderly, while {B} squirms. Or perhaps {A} pinches and tortures them.",
	'Accidental stimulation. {B} and {A} come into close contact, which leaves {A} aroused.',
	'{B} comes across {A} cooking or cleaning in an apron and is quite taken by the domestic sight. Bonus points if the apron stays on during sex.',
	'{A} gets a little rough with their teeth, nipping and biting {B} in sensitive places, leaving marks.',
	"{B}: If you didn't want me to fuck you, why'd you wear this pretty little skirt for me, {A}?",
	"{A}'s a pain slut, and {B} gives {A} a world of hurt. This can include spanking, whipping, caning, sounding, clamps, predicament bondage, knives... whatever you like. The point is: the pain brings arousal. It hurts so good for {A}, and whether {B} is merciful or sadistic with them, they understand {A} gets off on it.",
	'{B} is fully nude. {A} is fully clothed.',
	'{B} really likes {A} tied up with ropes. How {A} feels about that is up to you.',
	"{A} keeps {B} in long-term chastity, allowing {B} to masturbate, but not cum. {B} can't cum when {A} and {B} are having sex, either. Write either the everyday orgasm denial aspect, or when {A} finally allows {B} to cum. OR BOTH.",
	"{A} and {B} lie on a blanket in an empty field. They meant to star-gaze but instead they're having sex on that blanket, out in the open.",
	'{B} and {A} spoon. The big spoon uses this opportunity to caress the little spoon from behind.',
	'{A}: I can get you there. Tell me what you need, {B}.',
	"Clothes-sharing kink. {A} lets {B} borrow a shirt/jacket/piece of jewelry, and {B} feels so special wearing the item. {A}'s scent is embedded in it. It's soft, or starched and crisp, or old and worn... Please describe the item and include sensory details. Really kink out on how it makes {B} feel and incorporate the item into the scenario. Perhaps {B} wears it during sex and it feels like they're surrounded in {A}. Or perhaps {A} takes the item off them again when they're undressing {B}.",
	"Tickle kink. {B} discovers {A} is highly ticklish. How'd they learn this? And what do they do with the information?",
	"Tickle kink. Does {A} loathe being tickled, or is it actually a huge turn-on they're trying desperately to keep {B} from figuring out? (I think {B} should figure it out and tickle {A} till {A}'s breathless, teary-eyed, and begging for mercy. But that's just me.)",
	"{B} learns a long-held fantasy of {A}'s and decides to help make it come true. The weirder {A}'s fantasy is, the better.",
	"Whatever {A} and {B}'s dynamic is in daily public life, it's the exact opposite in the bedroom. Whatever people might assume, they're totally wrong. Write a bedroom scene where you make the most weird and 'off' dynamic work and feel IC for {B} and {A}.",
	'{A} puts makeup on {B}. The intimacy of all the face-touching brings {A} and {B} closer together, physically. (The makeup can be anything: classic beauty makeup, guyliner, clown makeup, war paint, eye black...)',
	'{A} and {B} hooking up in a vehicle: car, van, limo, trailer, plane, submarine, Gundam, Quinjet, zeppelin, space ship, escape pod...',
	"{B}'s got a pair of handcuffs. {A}'s not going anywhere.",
	'{A} finds a unique way to restrain {B}.',
	"Thanks to a spell/serum/curse/psychological conditioning, {A} can only tell the truth, no matter how hard they might try to lie. And the truth is, {A} wants in {B}'s pants.",
	'{B} backs {A} up against the wall, then sinks to their knees and goes down on {A} right there.',
	"There's a vibrator inside {A}, and {B} has the remote control.",
	"{B} drips wax on {A}'s body. The wax pools along {A}'s skin, dribbling down ripples of musculature, pooling in valleys, till {A} is streaked like a Jackson Pollock painting. {A} is {B}'s masterpiece.",
	"A desperately-needed back massage leads to oiled-up backdoor exploration. {A} circles {B}'s hole, breeches it, makes {B} cum fingering it. (That's all part of a massage, right?)",
	'{A} loves to bring {B} to the brink, then deny {B} release over and over. {B} gets increasingly desperate. {A} wants {B} to beg.',
	"Nothing settles {A}'s anxiety and stress like a good, hard spanking from {B}. {A} gets one every night for maintenance, but {B} can see when {A} needs one in the middle of the day too.",
	"Clothed sex. Whether there's no time to get fully naked or one of them just really likes the other's outfit, {B} and {A} do it moving the bare minimum of what they're wearing.",
	"Nudity kink. For whatever reason of your choosing, {A} undresses {B}, gradually revealing and appreciating {B}'s body. ({A} remains dressed; this is all about {A} getting {B} naked.) Please include descriptions of {B}'s body, whether romanticized or unflinchingly realistic.",
	"Free use kink. {A} and {B} have agreed that {A} can have sex with {B} anytime they want, even if {B} is otherwise occupied, not in the mood, etc. It's a big turn-on for {A} to be able to use {B} for pleasure at literally any time, any place. (How {B} handles it is up to you!)",
	'Write the first time {B} and {A} try anal of any kind. (Fingers, tongue, toys, penetration, no penetration...)',
	'Piss kink. {A} wants to watch {B} wet themselves. I wonder how {B} feels about that??',
	"Piss desperation kink. {A} needs to go so bad, but can't (for a reason of your choosing), and {B} notices. The struggle, the discomfort, and the stakes of {A} possibly wetting their pants before getting to a toilet makes for a super heightened experience for one or both of them.",
	'{B} wants to get {A} pregnant and fantasizes about it.',
	"Lactation kink. {B} is leaking through their shirt. {A} helps relieve the pressure, either by helping {B} pump, squeezing the milk out with their hands, or sucking it out themselves. (Doesn't necessarily have to involve pregnancy!!)",
	"Pregnancy kink from the POV of the pregnant partner (the name swap feature may come in handy here). {A}'s been extra horny since they got knocked up. They think about how aroused they are to be pregnant and have a baby with {B}. Swollen and claimed. So full. So fertile. {A} cums extra easy and is constantly wanting more.",
	'Size difference. Find a difference in size between your characters and exploit it. If {A} and {B} are similar sizes, or averagely sized in all ways, enlarge or shrink one or both in some way that excites you (or would excite your characters).',
	"It's {B} and {A}'s anniversary. They go all out in the bedroom, doing things they don't normally do.",
	'Hate sex. {A} and {B} are fighting. It turns into rough sex. They shove each other against walls, pull hair, cuss each other out, continue to fight even as they fuck.',
	'{B} has a talented tongue. {A} cannot believe the things {B} can do with it.',
	"There's a heatwave, and {B} is sweating through their summer clothes, skin glistening with perspiration and clothes clinging uncomfortably to them. {A} suggests {B} remove some clothes. Maybe all their clothes...",
	"Public sex. {A} and {B} hook up in public, barely out of sight - or in plain sight! It's like at least one of them gets off on the idea of being caught, huh? Or is it the sneaky factor??",
	'Public sex, but in an alternate universe where public sex is normalized and part of everyday life. {A} and {B} fondle or even fuck front of others in various public places or functions, and no one bats an eye.',
	'No one knows that {B} is wearing a butt plug. No one but {A}, that is.',
	'{A} masturbates for {B}, who tells {A} what to do.',
	"{B} to {A}: You've got such an oral fixation, I thought you might like this.<br><br>(...It's a pacifier.)",
	'{A} and {B} want to roleplay but have different ideas about what they should play. They compromise and mesh their two fantasies.',
	'{A} has a wet dream about {B}.',
	'Praise kink. {B} loves to compliment {A}. {A} will do just about anything for more compliments from {B}.',
	'<em>[CW: dub-con/non-con.]</em> {A} and {B} are captured and thrown together in a dank cell. Whoever put them there wants them to have sex. {A} and {B} refuse. But their captor is determined.  Threats, incentives, turning up the heat, turning them against each other by making at least one of them want it, putting hormones in the air supply... what gets {A} and {B} to break?',
	'Genderswap time. Will it be {A} or {B}? (Maybe BOTH?)',
	"I am once again asking for more threeway fics. Write {B} and {A} deciding to do this, excitedly choosing and seducing a third. (Who? I'm sure you already know, in your heart!) Whether you want to swing it towards a polyam situation or have {A} and {B} primarily enjoying the thrill of watching each other with another person is up to you!",
	"{A} is {B}'s Dominant and loves to put {B} in subspace. Describe what {B} is like in subspace from {A}'s perspective, or go deep with {B} and describe things from the sub's perspective.",
	"{B} is {A}'s Dominant. {B} has {A} keep a journal, blog, or Twitter all about their submissive journey: their feelings, triumphs, challenges, fantasies, daily tasks. Write some of {A}'s entries or tweets.",
	"Look, I don't know how it starts, but I do know it ends with {A} licking their own cum out of {B}'s mouth.",
	"{B} is obsessed with the idea of {A} masturbating. Imagining what {A} does, imagining {A}'s fantasies and wondering what turns {A} on. {B} finally goes so far as to set up scenarios where they can get {A} to masturbate, or get {A} to admit to masturbating. Maybe {B}'s in a position where they get to watch {A} do it, or maybe {B} is stuck just imagining it. Either way {B} loves the idea of {A} touching themselves.",
	"Turns out {A} does not have genitals that match their outward gender presentation. But as it happens, {B} is extremely turned on by this discovery. (Non-binary or trans!{A} welcome; magical genderswap scenarios welcome; really any genderfuckery scenario welcome! The point is, {B} is taken by total surprise by what {A}'s working with, but is unexpectedly into it.)",
	"Pet play. {B} wants to make {A} into their pet.  Cat, dog, bunny, sheep, cow... whatever feels right. {B} goes about acquiring the necessary accessories and materials for {A}'s pet persona. {A}'s stance on this, and how {B} broaches the subject with them, is up to you.",
	"Pet play. {A} has always thought they have some traits like a certain animal (of your choice). But when {B} points that very thing out, {A} gets flustered beyond belief. {A} wants to hear {B} say it again and again. {B} notices this and begins to experiment: calling {A} a nickname that recalls that animal, getting them ears and/or a tail, petting them, talking to them like they'd talk to that animal. The play makes them both {A} and {B} happy and excited. (Bonus points if your characters are already anthro and you write them wanting to play another animal!!)",
	"{B} watches {A} dance at a club or party. Whether {A}'s good or bad at it, {B} loves watching {A}'s body move and asks {A} to dance for them privately.",
	"{A} is not allowed to use their hands as they perform oral on {B}. If {A} can't manage, {B} just might have to tie {A}'s wrists...",
	"Give {A} or {B} a riding crop and leather gloves. (That's it, that's the prompt. Please and thank you.)",
	"Thigh kink. You know better than I do whose thighs ought to be caressed, licked, objectified, fucked. Stick a garter on them thangs. Stockingify them. Strap a holster on 'em. Miniskirt it up. Make them close tight, or open up wide. Just write some porn heavily featuring {A} or {B}'s thighs.",
	"According to {A}, {B} needs to learn to cum from being fucked in the ass, or {B} won't get to cum at all. Ever.",
	"Sissification kink. The more feminine {B} dresses, the better, in {A}'s opinion. So {B}'s wardrobe begins to expand. Glossed lips, fluttery florals, high heels, delicate jewelry. {A} and I want to see {B} all dolled up.",
	'{A} is in a chastity device, and trying to get off by humping a pillow (or other object of your choice). Does {B} have mercy on them, or delight in their desperation?',
	"<em>[CW: Ageplay/possible wetting or messing kink/dub-con.]</em> {B} wants to diaper {A}, while {A} is nervous about the prospect. {A} does like being {B}'s little, so {A} agrees, but doesn't want to actually <i>use</i> the diaper. That's just too weird, too embarrassing! But {B} urges {A} to use it, and if you want, possibly even forces them to. Then {B} changes {A}, praising a tearful {A} for using their diaper.<br><br>If you prefer non-sexual ageplay, end it here. But if you like sexual ageplay, push it further, with {B} rewarding {A} with an orgasm before diapering them again.",
	"Ageplay. Caregiver!{A} and little!{B} have a nice morning together, doing some of {B}'s favorite little activities. Yay! {B}'s feeling super cuddly and lovey-dovey after all the attention and fun, and {A} gets lots of kisses.<br><br>If you prefer non-sexual ageplay, end it here. But if you like sexual ageplay, {B} can ask {A}, 'Can we play grown-up games too? Pleeease??'",
	"Ageplay. Little!{A} is having a terrible, horrible, no-good, very bad day. They are grumpy and naughty, making messes and acting out for attention. Caregiver!{B} knows just what little!{A} needs. Whether that's a lecture, a spanking, lots of love, or something else entirely is up to you.<br><br>If you prefer non-sexual ageplay, end it here. But if you like sexual ageplay, have {A} be a good, obedient little for {B} next.",
	"Role-reversal kink. {A} is a Dom. Has always been a Dom. Will always be a Dom. Doesn't remotely question it. Until {A} gets with {B}, who activates a submissive instinct {A} has never experienced before. {B} makes {A} work hard for their attention...",
	"Role-reversal kink. {B} takes their role as top for granted. It's natural for them, and it works well, since {A} likes to bottom. But one day, {B} and {A} are making out while {A} is lying on top of {B}, and it's so steamy that it inspires {A} to give topping a try. How {B} takes it (...literally?) is up to you!",
	'<em>[CW: dub-con/non-con.]</em> Somnophilia. {A} touches {B} in their sleep, moving slowly and carefully, so as not to wake them. Whether {B} wakes or remains none the wiser, you tell me.',
	'Virgin!{B} and extremely experienced!{A}.',
	"{B} and {A} are actually both asexual, but neither of them realize the other's a fellow ace. But both want to please the other, so they have sex anyway. Or they try to, before they discover what's up. Where they each fall on the grayscale could be really fun to play with. Maybe one's hypersexual without the attraction factor, and maybe one's actually sex-repulsed but has hidden it super well. Maybe they stop before they actually have sex, or maybe they see it through, out of curiosity. Go nuts.",
	"Safe sex. Wait! Before you skip this prompt, let me challenge you to write sex with a condom or dental dam and make it the hottest fucking sex imaginable. Don't gloss over the application of the prophylactic. It's not sexy? Find a way to make it sexy. Kink out on it. Describe it. Add in sensory details about it. Protect {B} and {A}, please!",
	'{A} brats it up specifically so {B} will spank them.',
	"{B} walks in on {A} undressing. It's a total accident, but it excites {B} so much that they start finding ways to glimpse {A} in private moments. Whether {A} knows this is happening or not is up to you.",
	"{A} catches {B} watching them, and decides to put on a show. {B} watches {A} undress, shower, put on makeup, try on outfits, or anything that tickles your fancy, while remaining none the wiser that {A} knows they're watching.",
	"<em>[CW: dub-con/non-con.]</em> Somnophilia. {A} is sick or injured, and {B} is taking care of them: 	mopping their brow, feeding them, giving them medicine, etc. With the blurring of physical boundaries, {B} starts feeling like they can touch {A} however they want, even while {A} is passed out. It's up to you whether {A} consents to this, or doesn't know it's happening.",
	"Due to a spell or scientific mishap, {A} grows tentacles. {B} is trepidated at first, but is soon caressing the suckers dotting {A}'s wiggly new appendages.",
	"{A} has a secret degradation kink, which {B} is reluctant to enjoy. It just feels wrong and mean to speak to anyone that way. Write {B} getting into calling {A} a filthy slut (or what have you) for the first time. The psychology of this could be very dependent on your characters. What kind of degradation would work best for them as individuals? It'd be fun challenge to make it believable for them.",
	'Blood kink. {A} is handling a knife (in the kitchen, at work, while enjoying a hobby) and cuts themselves. What a way for {B} to find out they want to lick the blood off {A}... maybe even suck it out of {A}.',
	'Masturbation. Write {B} getting off while thinking about {A}.',
	"Mutual masturbation. {A} and {B} end up masturbating together. The only guideline here is that they don't touch each other. They can keep their eyes shut and ignore each other, watch each other, instruct each other... anything goes, as long as there's no touching during the encounter. This might make a great phone/cyber sex scenario.",
	'Praise kink. {A} notices that {B} is very responsive to praise. So much so that {A} could probably get {B} to do pretty much anything, with enough praise, or the right kind of praise. {A} starts experimenting.',
	'<em>[CW: amputation.]</em> {B} loses a limb, and the physical adjustment is hard enough already, but the emotional adjustment is even more so. But {A} is tender with {B}, gently caressing and worshiping their entire body - including the affected area.',
	"<em>[CW: amputation.]</em> After the loss of a limb, {A} feels phantom pains. {B} massages their body, easing {A}'s discomfort and rousing other sensations.",
	'Hate sex. {B} could not hate {A} more, and the feeling is mutual. So of course {B} and {A} have insane sexual chemistry, fueled by the humiliation and indignation they feel at being so aroused by each other. What are they supposed to do, NOT bang it out??',
	'Exhibitionism. While out in the wilderness with friends, family, or a tour group, {A} and {B} fuck in their tent, getting off on the idea that someone could possibly hear them. Bonus points for a member of their party catching them and watching them or listening to them, but not saying a thing.',
	'Masturbation. {A} is talking to {B}, either on the phone or in another room, but is also stealthily getting off. {A} loves getting away with it, and gets super hot imagining {B} hearing them or catching them at it.',
	"<em>[CW: invasion of privacy.]</em> {B} winds up gaining access to {A}'s phone. Nothing wrong with a little poking around, right? On the phone, {B} finds a trove of NSFW content. Whatever sort you like: pictures, videos, sexts, spicy fanfic. {B} is shocked and turned on. This is content {A} never meant for {B} to see... but {B} can't just pretend they never saw it. What happens next?",
	'{A} masturbates solely through their underwear, just too sensitive for direct touch. Does {B} touch {A} that way too? Gently and respectfully, through their underwear? Or does {B} overstimulate {A} by getting their hands in that underwear and touching {A} directly?',
	"Exhibitionism, BDSM. {B} is enjoying a drink at a kink-friendly event (bar, private party, demonstration) with {A}'s head in their lap, receiving their due worship. {A} is dressed exactly how {B} likes. Some people are watching them, which {A} loves. {B} is proud and egging {A} on, receiving compliments on {A}'s dress, behavior, mouth, etc. Whether this is their first time in public or a regular occurrence is up to you.",
	"Sexual dysfunction kink. {A} can't orgasm, for the reason of your choosing. This would totally kill some relationships, but {B} makes it into a kink for them both by praising {A} for their control... for never letting go and cumming when they aren't supposed to... for dripping with excitement but holding back. (Or, conversely, {B} harnesses {A}'s shame and embarrassment and kinks out on that.) {A} never cums, but encounters with {B} are earth-shakingly exciting for them and they are always hyper aroused. (Orgasm denial, dirty talk with either praise or degradation, and D/s would all work great with this!)",
	'Shower sex - hotter in concept than in execution. Can you make it work for {A} and {B}? I dare you to try.',
	'{B} and {A} have a one night stand. They wake up in bed together, naked and utterly shocked at what happened between them. Write them awkwardly discussing their encounter in the cold light of day. Bonus points if they hook up again.',
	'Oh my god {B} and {A} are roommates. What happens when they have to share living space and {A} accidentally walks in on {B} naked or hooking up or something??',
	"Telepathy. One morning {B} wakes up and discovers they can read {A}'s mind. Not only that, but {B} can physically taste what {A} tastes and feel what {A} feels. {A}, unaware of {B}'s predicament, goes about their usual business, accidentally projecting private and sometimes prurient thoughts right into {B}'s brain. This could go sooo many places. Go wild.",
	"{A} and {B} telepathically connect. It's a hall of mirrors having sex, seeing themselves via each other, reflected and refracted into infinity, and feeling each other's each and every shudder of excitement like an unending echo. They know exactly how and where to touch each other, exactly what to think and do in unison. Orgasming together is a brain-bending oblivion.",
	"{B}'s got a secret side hustle: cam work. {B} is actually getting pretty popular, livestreaming and taking sexy requests from customers. Little does {B} know that {A} is one of their dedicated customers. {A}, under a random username, makes all kinds of requests of {B}, and pays handsomely for custom content. {A} sometimes buys {B} gifts: things to wear and toys to play with on cam, silly trinkets, even birthday presents. {B} starts looking forward to requests from {A}.",
	"Porn star AU. It started with solo cam work, but now {A}'s going to star in their first-ever video with another person: {B}, known for breaking in newcomers. {A} is incredibly nervous and watches a lot of {B}'s videos before meeting {B} for the first time. What's {B} like in person? What kind of video will {A} and {B} make together? How does that go?",
	"Dacryphilia. It makes {B} feel horrible, but they get very excited when people cry. The more uncontrollable the crying, the more it affects {B}. That obviously makes {B} a bad person, right? {B} would never make anyone cry on purpose... But when {A} tears up over something, {B} suddenly can't hold back. {B} encourages {A} to let it all out, becoming extremely turned on as {A} sobs. Whether {A} catches on and how they handle it is up to you.",
	"Dacryphilia. {A} loves to make {B} cry during sex, often outright saying, 'Cry for me, {B}' and holding their face so they can look into {B}'s teary eyes. Whether it's a tender or rough scenario is your call.",
	"Dacryphilia. While upset and weeping, and being comforted by {A}, {B} notices visible signs of arousal on {A}'s part. {B} can tell {A} is excited by their crying. What does {B} do?",
	"After commiserating about how neither of them are getting what they need, {A} and {B} decide to become friends with benefits. They're definitely not dating. It's just that {B}'s tired of the dating scene, and {A} wants to experiment. (Or whatever reasons suit your characters best!) Write any part of this scenario that interests you: one of their encounters, their first time, how they agreed to start fucking around... or the inevitable moment feelings get in the way of their arrangement.",
	"{B} and {A} don't really do the whole penetration thing. They don't want or need to. {A} can make {B} cum with caresses alone, fingers squeezing and sliding, palm warm and sweaty.",
	"{A} loves receiving oral more than anything on this planet. Nothing makes {A} cum faster or harder than {B} going down on them. {B} loves how much {A} loves it and could spend hours between {A}'s spread legs, using their mouth till {A}'s a babbling mess.",
	'Mouth + fingers = an unbeatable combination. {A} uses their mouth on {B}, either north or south of the hemisphere, while simultaneously fingering whatever orifice drives {B} mad for more. (Penetration not strictly necessary.)',
	"The world needs so much more aftercare in fic! Sure, sex is great, but have you tried bringing your partner some water and tucking them in? :)<br><br>Write {B} indulging in some aftercare with their beloved {A}. This could include checking in with {A}, making sure {A} has a drink or snack if needed, helping {A} get comfortable, or cleanup. {B} and {A} could cuddle, watch TV or movies together, or talk about what they did together. It could be especially fun to explore if one of them isn't accustomed to aftercare.",
	'Post sex, {B} tends to get a little depressed, emotional, or otherwise troubled. However wonderful and pleasurable it was, the more intense the experience, the worse {B} feels afterwards. {A} does whatever they can to buoy {B} with comforting conversation, gentle touch, and other reassurances.',
	'{A}? Werewolf. {B}? Has no idea. Until one full moon, when {B} witnesses {A} transforming. {B} should be terrified of the fangs and claws, the fur, the animalistic prowling of {A} coming closer and closer to them. Instead {B} is primally excited, and reaches out to touch {A}... {B} touches everywhere {A} will let them touch.',
	"{A}'s partner, {B}, is a werewolf. As a couple they've been dealing well with the monthly transformations, {B}'s enhanced senses and predatory instincts, and the occasional claw marks around the house. Everything's under control until {B}'s pack wants to welcome {A} officially into their fold, with a mating ceremony to take place in front of the pack leaders. That means {B} fucking and claiming {A} as their mate in front of a bunch of salivating, horny werewolves. Write the mating ceremony in glorious detail. Be as wolfy and bestial as you want.",
	"<em>[CW: non-con.]</em> While out in the wilderness, {B} and {A} are beset upon by a terrifying creature of your design. The creature is interested in {A} and manages to ensnare them - only to tear {A}'s clothes off and begin to sniff and lick {A}, while {B} can do nothing but watch. The creature's intent and how {A} and {B} deal with it is up to you.",
	"{A} wakes in the middle of the night. Something is in the room with {A}. Something is... bending over {A}, sniffing them. Smelling them. Something, someone, is dragging hot teeth over {A}'s exposed neck. It's vampire!{B}, who's there to seduce {A} into letting {B} suck their blood. {A} feels weak, trembles, <i>craves</i> {B}'s body on theirs and {B}'s fangs in their throat... Can {A} resist?",
	"<em>[CW: blood.]</em> {A} is a vampire, and their favorite place to feed is directly from {B}'s inner thigh. The blood flows so hot, so viscous and plentiful. It smears {A}'s chin and leaves a copper tinge in the air. {B}'s thigh is peppered with bite wounds and blood and the slick evidence of their arousal as {A} feeds from them greedily...",
	'Vampire!{B} fucks {A} in or on top of their creepy coffin. Bonus points if {A} is in some kind of gothic, dramatic hero/ine getup. Double bonus points if they break the coffin going at it. Triple bonus points if {A} bites {B}, when they are not even a vampire... (Yet?)',
	"Hooker AU. You know how prostitutes aren't supposed to kiss clients on the lips? {A} can make an exception for {B}... just this once.",
	"Hooker AU. {A} wants the girlfriend/boyfriend experience in bed, and is willing to pay {B} for it. The money's great, but the lines have never blurred so fast for {B}.",
	"{A} licks their own cum off {B}'s fingers.",
	"It's {B}'s fantasy to host a party for friends and have {A} serve the guests... naked. Take everyone's coats, naked. Offer everyone drinks and food, naked. Carry trays, naked. All other partygoers, including {B}, remain entirely clothed. {A} is the only one in the nude, an ornament for all the guests to admire or ignore as they please. Whether {A} is made terribly nervous and clumsy by this, or is thriving as the center of attention, is your choice...",
	"Jealous of attention {A} receives from a third party, {B} decides to remind them to whom they belong. {B} takes {A} to bed, touching and handling them possessively, covetously.<br><br>Dialogue options: <i>'You're all mine. They can never have you, not like I'm having you now. Say you belong to me only! Say my name!'</i>",
	"{B} may look normal, wearing their typical clothes. But underneath their clothes, there's a starfield of bite marks and hickeys left on them by {A}. There are bruises and love bites and scrapes and flushed patches all over them, anywhere and everywhere people wouldn't normally see.",
	"{A}'s gained a little extra weight lately, and {B} <i>loves</i> it. The shape, the softness, the jiggle... Or, if it's muscle mass {A}'s gained: The added bulk, the flexing muscles and tendons, the increased strength. Whatever it is and however {A} feels about it, {A}'s never looked or felt better to {B}, and {B} is eager to get their hands all over {A}'s bigger body.",
	"{A}'s an exhibitionist and comes up with a scheme for {B} to catch them undressed. The very notion of {B} seeing them naked excites {A} to the core.",
	"{B} writes erotica as a private hobby. {A} discovers it, and reading {B}'s works reveals the unplumbed depths of {B}'s sexual imagination. The idea that {B} even thought of some of this stuff is incredibly shocking and exciting to {A} - who now has to get up the nerve to approach {B} and ask if they can re-enact a certain scene from {B}'s work.",
	"{A} is a total drooling, stupid, subby simp for a certain Dominant online who's particularly skilled at humiliating and degrading them. (That'd be {B}.)",
	"<em>[CW: shame/humiliation.]</em> Piss kink. {A} loves to wet themselves. It's humiliating and disgusting of {A}, but {A} indulges on their own time, in private. They're not hurting anyone by letting go and drenching themselves in a hot flood of urine - for them, it's the ultimate relief and ultimate taboo. But of course, {B} finds out. And when that happens, {A} has never felt more humiliated, ashamed, and aroused. Whether {B} is sweet and kind about it or embarrasses {A} further is up to you.",
	"Piss kink. In a moment of duress, {B} loses bladder control. {A}'s... well. Into that, as it turns out.",
	"<em>[CW: non-con, depending.]</em> Somnophilia. {B} pretends to be asleep while {A} touches them, carefully rearranges their limp limbs, and uses their sleeping form to get off. This could be a mutual fantasy they're playing out, or {A} could think {B}'s legitimately asleep. Tackle it how you like.",
	"BDSM. It turns out that {B} really likes to be slapped across the face. It's jarring but {B} is totally capable of taking the hit, and that makes their adrenaline pump. {B} even likes the fireworks sensation left behind by a good slap. {B} asks {A} to slap their face. How does {A} react?",
	"BDSM. {A} ties {B} up and watches {B} struggle in their bonds. The helpless wiggling and pulling and increasing panic as {B} realizes they can't get free is a huge turn-on for {A}.",
	"Objectification. {B} acts as {A}'s footstool, kneeling on all fours and propping {A}'s feet up on their back. It's uncomfortable. {B}'s knees and back hurt quickly. It's a struggle to keep from moving. But {B} tries their hardest to be a good footstool for {A}, all while {A} enjoys a drink, a magazine, a TV show, or a phone conversation with someone.",
	"{A} gives {B} soft, gentle oral. It's almost more of a tease than anything else - the slow brushes of tongue, the ghosting lips and hints of kisses, the puffs of breath firmer than any lick or suck given. But {B} is eventually swept away and sees stars.",
	'{A} and {B} join the Mile-High Club.',
	'Role-reversal kink. {A} bottoms, but has been such a good student of the way {B} tops that they want to apply their newfound knowledge... to {B}. {B} is conflicted. They prefer to top. But they relent, and to their surprise, they really like {A} topping.',
	"{B} is always too gentle. {A} wants {B} to hurt them and fuck them roughly, but doesn't know how to ask without scaring {B} off.",
	'{A} gives {B} oral from under their desk... while {B} is teleconferencing/on the phone/talking to a subordinate.',
	'{B} convinces {A} to strip down and let them take nude and erotic photos of {A}.',
	"{A}, for a sex pollen-esque reason of your choosing, has become insatiable in bed. {A} can (and needs to) go for hours to be satisfied. {B} is the one to deal with {A}'s ridiculous libido.",
	'When {B} and {A} get together, {B} fully anticipates {A} topping. Come to find out, {A} likes to bottom as well. Cue lighthearted squabbling over who gets to bottom.',
	'{A} teaches {B} something new in bed.',
	'In need of emergency funds, {A} auctions their virginity to the highest bidder: {B}.',
	"<i>[CW: dub-con, depending.]</i> Body swap. {B} and {A}'s minds are transferred to each other's bodies, and {B} takes the chance to explore all the nooks and crannies {A}'s been hiding.",
	"Slave AU. Damaged and abused - but a gem in the rough - {B} is acquired from the slave market and trained to be {A}'s personal body slave. The training is thorough and {B} must learn to satisfy {A}'s every whim if they want to survive.",
	'{A} can cum from nipple stimulation alone - a fact {B} takes advantage of, at inopportune times.',
	"<em>[CW: incest.]</em> {A} and {B} roleplay that they're related - siblings, parent/child, step-family, whatever butters your muffin.<br><br>If your characters are already related, make them pretend they're not.",
	"{B} brushes their finger over {A}'s lips. {A} sucks it without hesitating.",
	'{B} is a vampire, and {A} is ready to give {B} all the blood, sex, and moonlight {B} needs to stay alive.',
	"Zombie/apocalypse AU. {B} and {A} are a few of the only uninfected left in a ruined world. They're forced to rely on each other for everything, including intimacy.",
	'{A} has developed the miraculous ability to modify their body to include any and all parts they desire. {B} likes to have fun with <em>all</em> the parts.',
	"{B} hasn't dated anyone in a while and they are rusty. Really rusty. Enter {A}, who suggests they give {B} some practice in the sack.",
	'BDSM. {A} is tightly bound and being drilled mercilessly by a fucking machine, while {B} watches.',
	"Amnesia. {B}'s lost their memory and doesn't remember being with {A}. When {B} and {A} sleep together again, it's like the first time for {B}.",
	"<em>[CW: non-con.]</em> Mind control. {A}: 'Please, {B}. You don't want to do this. They're making you do this.'",
	"{A} can switch genders at will. {B} likes whatever {A}'s got going.",
	'{B} and {A} have an arranged marriage. They meet for the first time on their wedding day. Cue the honeymoon...',
	"{A} likes {B} shaved completely free of all hair below the neck. {A} runs their hands all over {B}'s body, relishing the smooth skin they find.",
	"{B} helps rub lotion, oil, sunscreen, or some other slippery substance on {A}. If {B}'s hands wander a little in the process, well...",
	"Sugar baby AU. {A} is in financial need, and {B} steps in. {B} pays for bills, meals, outings, clothes, and even totally frivolous expenses, all so {A} doesn't have to worry and can live an easier life. All {B} asks for in return is {A}'s interest and occasional company. Sure, {A} can fake a little bit of flirting. But what starts off as a convenient and non-sexual arrangement snowballs into something more.",
	"{A} thinks {B}'s got a gorgeous chest and decides to have some fun with it. Go wild with nipple play, flattering rope bondage, body worship, dressing {B} up in tight t-shirts or lingerie, tattoos and piercings...",
	'{B} is a submissive top. {A} is a dominant bottom.',
	"{A} keeps a detailed diary of all their sexual encounters. Write a sample diary entry from {A}'s perspective about an encounter with {B}.",
	'<em>[CW: CNC.]</em> {B} has a non-con kink. {A} indulges it, allowing {B} to forcefully take them whenever {B} wants, with {A} crying and protesting and struggling the whole time - all stuff that {B} loves.',
	"{B} uses telekenetic powers to tease {A}'s body from afar, popping buttons and sliding zippers, tweaking sensitive places with their mind alone.",
	"Uniform kink. {A} admires how {B} looks in uniform, no matter how official and regimented (military, clergy, etc) or typical and mundane (school uniform, fast food restaurant employee garb, etc). In fact, it kind of gets {A} going. {A} has {B} stay in uniform during sex.<br><br>({B} doesn't have a uniform? Put 'em in one!)",
	'{B} and {A} try hard to cum in unison.',
	"{A} sits on {B}'s lap. 👀",
	'{B} dreams about being physically overwhelmed by someone stronger - {B} wants to feel totally pinned down and helpless. {A} helps them achieve their fantasy.',
	"{A} and {B} are each other's first.<br><br>(No, they aren't, you say?? Well, in <em>your</em> AU, they are!)",
	"{A} is not a virgin, but {A} and {B}  like to roleplay otherwise. Cue {B}  pretending to lead {A} through their 'first time,' assuring them it won't hurt and that there's no need to be scared.",
	"{B}  greatly enjoys giving oral sex. They relish feeling like they're in control and love showing {A} a great time. {A} wants to reciprocate. The thing is, {A} has never tried giving oral before. {A} tries their best, and {B}  helps out, telling {A} exactly what to do.",
	"Dacryphilia. When {B}  cries, {A} teases them about it, calling {B} a crybaby. {B} finds the teasing unexpectedly exciting, and as a result {A} begins relentlessly saying things like, 'Crybaby gonna cry?' and 'Gonna cry like a baby, huh?' The teasing and taunting and tears gets them both off.",
	"I don't care how you do it, but please, put {A} in a corset. Have {B} help lace them up nice and snug. {A} just looks so good with an itty-bitty waist.",
	"After a particularly hard day, it's obvious {B} needs some special attention and reassurance. {A} takes them to bed and gives them long, emotionally gratifying comfort sex. That can be defined however you want, but might include: lots of praise, words of affirmation, eye contact, or especially intense forms of contact.",
	"{B} is only a ghost, but visits {A} nightly to pleasure {A} in their sleep. {A} thinks they're just having intense and strange wet dreams, but it's all because of {B}.",
	"In the steamy bathroom, {A} watches {B} shave their body (or a specific area of their body), at {A}'s special request. The anticipation is as thick in the air as the shaving cream on {B}'s skin. It's almost like a ritual: {B} loves to be watched as they lather, shave, and rinse, and {A} loves to watch.",
	"{A} calls {B} with the idea of getting some phone sex, but {B} is otherwise occupied: out in public, with other friends, perhaps in an Uber. But {A} isn't dissuaded. {B} ends up listening to {A} get off on the other side of the line. Whether {B} is red-faced because they're flustered or turned on, you tell me. Bonus points if {B} finds a way to talk {A} off without being overt about it.",
	"{A} fucks {B}'s mouth. (Fingers and toys can be put to use here too!)",
	'{B} trains {A} to deepthroat. (Strap-ons welcome!!) {B} loves how {A} looks with their eyes wide open, mouth stretched, and throat convulsing.',
	"<em>[CW: invasion of privacy.]</em> {B} records their favorite sexual fantasies in their journal. It's meant to be private, of course, but {A} finds the journal and reads it. This could go any number of directions: {A} could make one of {B}'s fantasies come true; it could inspire {A} to share their fantasies with {B} too; {A} could blackmail {B}... just a few ideas!",
	'{B} and {A} visit a nude beach. Tan lines, wandering eyes, and sexual tension - oh, my!',
	"{A} promised {B} they could go for a certain amount of time without an orgasm. But right now, {A}'s not so sure they're gonna make it.",
	'{A}: You want me, {B}? Prove it.',
	"{B} and {A} let a third party watch them. It could be that they just kiss and do a little over-the-clothes touching. Or they could go all the way with an audience. Writer's pleasure.",
	"First time rimming. {B} kisses their way down {A}'s back. {A} is a bit shy or nervous about where {B} is going, but {B} asks {A} to trust them.",
	"Impact play. {A} starts out soft, with flicking fingers just swiping {B}'s skin. {A} soon graduates to full-on smacks of their palm and {B}'s skin is tingling like a live wire. Maybe it starts and stops with hands, or maybe {A} uses whatever's nearby to deliver sound cracks, echoing thumps, or stinging whips to {B}'s body, wherever {A} wants {B} to feel them the most.",
	"{A} is masturbating, getting closer and closer to the edge, but never actually hitting their peak. {A}'s desperation begins to mount as the minutes strain by and their attempts fail and fail and fail. They're trembling, sweating, cursing, almost crazed. {A} finally seeks out {B}'s help to cum.",
	'{B} rides {A} in nothing but a pair of boots and a cowboy hat. Yee-haw.',
	"{A} lets {B} tattoo them. Just how this even happens is a prompt unto itself, but to take it further, let's say {A} and {B} both find the inking process so hot, they barely finish the tat before they're all over each other.",
	'{A} acts like a prude, but in actuality, is a total slut. Not everyone knows this. But {B} does. Hell, {B} has <em>proof</em>: texts, pictures, videos, letters, stories from prior lovers - whatever you can think of.',
	"{A} and {B} take a mutual soak in a hot tub or hot spring. Their skin grows flushed. Beads of sweat begin to roll. If they're wearing swimsuits, those come off. If they're nude, eyes wander. Hands drift through the water to find the other person. Bonus points if they hook up in the water. Quadruple bonus points if they're getting away with it while others are around.",
	"Beach hook-up time. Private or public beach? Up to you. Day or night? Whatever you want. The one thing for sure is that {A} gets sand in places sand should never be, and it's {B}'s fault.",
	"{A} must deflower {B} as part of a ritual ceremony (political alliance, magic spell, etc), and there must be witnesses to the act.<br><br>(Even if {B}'s a character with some - or a lot - of experience, there's still likely some sort of sexual act they've never tried. For our purposes, that totally counts. Or you can just shamelessly enjoy some tender virgin!{B}.)",
	"{B} gives {A} a sloppy blowjob. (Strap-ons count.) The wetter the better. {A} likes it messy and gets {B}'s face wet and dripping, makes {B} drool and choke on their dick.",
	"{A} won't let {B} touch them. But {A}? Oh, {A} can touch {B} all they want. And they do, teasing {B} several times a day with gropes and caresses, till {B} is hugely pent up - all while smacking {B}'s wandering hands away. Damn, {A}'s such a tease.",
	"<em>[CW: non-con/dub-con.]</em> Mind control. {B} has the power to influence or outright puppet others, and uses it to make {A} do whatever they want: show more skin, break up with their SO, ditch their family and friends, get a tattoo of {B}'s choosing, become {B}'s willing sex slave... it's really up to {B}, isn't it? Whether {A} realizes what's happening at any point is up to you.",
	"Nobody puts Baby in a corner? Well, {A} does. Because {B}'s a brat. {A} swears {B} <em>likes</em> getting in trouble.",
	"Mommy kink. When in need of some comfort and stability, {B} and {A} pretend that {B} is {A}'s Mommy. Whether {A} is into age-regressing or stays their typical self is your call, but {B} leans into the caregiving role, wearing an apron and calling themselves 'Mommy,' 'Mama,' or whatever special name they have. They see to {A}'s comfort by offering anything from mother hen-ish scolding to special treats to cuddles to strict rules and punishments. Push things however far you like. Ultimately it's about love and comfort for {A} and {B}.",
	"{A} is a plushophile, and has the plushie collection to prove it. But {A} only gets off with one very special plushie, which they keep hidden. When {B} finds their special plushie, {A} is mortified, but {B} is intrigued. {B} figures it all out and somehow convinces {A} to demonstrate what they do. {B} holds the plushie for {A} and helps {A} rub off on the velvety fur, talking about how soft and cute the plushie is and encouraging {A} to 'cuddle' with it - and even cum all over it. No one has ever understood {A} like this. It's overwhelming.",
	"Rumors about {A} and someone else reach {B}. Dirty rumors. Whether or not they're true, {B} can't stop imagining {A} doing the things the rumors claim. {B} has got to find out for themselves if {A} has really done those things, and/or find out what it's like to do them with {A} themselves.",
	'{B} could get off just listening to {A} talk. {A} decides to see if they can make it happen.',
	"All thanks to the wild escalation of a bet, {B} wins a night with {A}. Even if they joke about it, {B} doesn't actually intend to treat {A} like a prize to unwrap and enjoy. But {A} is surpisingly willing to be just that.",
	'Slave AU. {A} has an entire retinue full of beautiful, worshipful slaves. But {B} is their favorite. And ornamented accordingly.',
	"{A} and {B} attend a fetish ball. This is your chance to dress them to the nines, whether that's in leather, latex, fetish gear, or a simple collar and leash.",
	"Human/animal hybrid AU. {B}'s taking a walk around town when they spot the <em>cutest</em> puppy/kitty/etc in the pet store window. {B} has to stop and look, gazing at the adorable creature through the glass. {A} gazes back dolefully, and {B}'s heart melts. Seriously, how has no one adopted {A} yet?? Meanwhile, {A} doesn't dare hope that they just made eye contact with their new owner...",
	"What's it gonna take to get these two skinny dipping???",
	"For a while now, {B} has been hiding something: When wet, they sprout tentacles. Yep. Tentacles. It's been exhausting worrying about people finding out, worrying about getting caught in the rain, worrying about what else their body might start to do. It's almost a relief when {A} finds out. Almost. Except there's something about the way {A} <em>looks</em> at {B}'s tentacles. Like {A}... wants something...",
	'{B} gets their tongue pierced. {A} discovers firsthand the piercing really does feel as good as everyone says.',
	"At {B}'s request, {A} gets their nipples pierced.",
	"Bruise kink. Not only does {A} love to leave {B} bruised, they love to press on {B}'s old and randomly acquired bruises to make them ache and worsen.",
	"Vampire!{A} has never fed on {B} before. It's a line they won't cross. But then, {B} has never smelled so mouth-watering before. All of a sudden, {A} is really jonesing for a hit of {B}'s blood, and the need is getting worse and worse. Is {A} prepared to break their resolve and get a taste of {B}? Would {B} let them?",
	"{B} is so excited - it's their first ever furry convention, and the debut of their fursuit. But who should they run into at the con but {A}? Who's a fellow furry...? What? And really into {B}'s fursuit? Huh??",
	'{A} takes {B} shopping for sex toys and says {B} can get anything they want.',
	"{B} sometimes wears a butt plug during their daily life. It's their perverse little secret. {B} just likes the feeling of fullness and the way it makes their libido thrum. No one's supposed to be able to tell from the outside. So it's a genuine shock when {A} comes up to them and asks, 'Does that plug feel good in you, {B}?'",
	"{B} keeps {A} stretched and ready with a butt plug so they can fuck {A}'s ass at any time.",
	"BDSM. {A} and {B} practice a 1950s-inspired version of 'domestic discipline,' where {A} is in charge of the household and {B} is the obedient little wife. The home is kept spotless, the yard is always mowed, and {A} is made happy by {B}'s conscientious and gracious servitude. Of course, every now and then, {B} needs a reminder of who wears the pants around here and gets put over {A}'s knee.",
	'{A} gives {B} kissing lessons.',
	"{A} and {B} are stuck in an elevator and it'll take a while to get rescued? No big deal. Gives {B} time to get in {A}'s pants.",
	"Dirty, nasty, wet sex. {B} makes {A} sweat, cry, drool, cough up phlegm, drip cum or snot or body fluids of any type - whatever presses your buttons. Have {A} and {B} leave a mess all over the place. Give new meaning to 'rode hard and put away wet.'"
];


export default nsfwPrompts