const prompts = [
	'Them resting together and talking to each other before falling asleep.',
	'Forehead touching. Forehead kisses.',
	"Them exploring each others' bodies, but not in a sexual way. Finding their different birthmarks, looking over each others' scars and sharing the stories behind them, running their hands over one another and just appreciating the feeling of the other person next to them.",
	'<b>{A}</b> and <b>{B}</b> go to a fair/amusement park and <b>{A}</b> wants to go on the roller coaster and <b>{B}</b> agrees. Later, <b>{B}</b> regrets their decision and ends up clinging onto <b>{A}</b> for dear life.',
	'They are on a ferris wheel, and everything is going great - until it gets stuck at the very top. For thirty whole minutes.',
	"<b>{B}</b> won't let <b>{A}</b> get out of bed by cuddling them. ",
	"<b>{A}</b> is about to leave for work. <b>{B}</b> asks them if they've forgotten anything, and <b>{A}</b> gives them a kiss. <b>{B}</b> turns red and opens their hand to reveal <b>{A}</b>'s keys/wallet/etc., saying 'I meant this, but thanks.'",
	'<b>{A}</b> buys a box of sweets and puts them in the cupboard. <b>{B}</b> spontaneously eats them all in the middle of the night and tries to keep it a secret.',
	"<b>{A}</b>: Is it hot in here or is it just me? <br> <b>{B}</b>: It's you. <br> <b>{A}</b>: What? <br> <b>{B}</b>: What?",
	"Them playing with sidewalk chalk like they're kids again.",
	'Them accidentally (or purposefully) dozing off in a hammock together as the sun sets and the air cools down.',
	'Them huddled by the fireplace at night after making snow angels in the fresh snow.',
	'Their first holiday season together.',
	'<b>{B}</b> wants to use their laptop on the couch, but <b>{A}</b> always occupies the space in their lap.',
	"<b>{A}</b> doesn't like talking on the phone, but <b>{B}</b> always calls them instead of texting. <b>{B}</b> admits that it's because they want to hear <b>{A}</b>'s voice.",
	'<b>{A}</b> wakes to find that it had snowed overnight and gets excited about playing in it. <b>{B}</b> gets excited because this means that when <b>{B}</b> comes inside, it will be time for cuddling by the fire.',
	"<b>{A}</b> and <b>{B}</b> reveal their tumblr blogs to each other. <b>{B}</b> turns out to be <b>{A}</b>'s #1 tumblr crush.",
	'<b>{B}</b> drags <b>{A}</b> into the freezing cold to make a snowman.',
	'<b>{A}</b> and <b>{B}</b> sending each other sexy and silly selfies.',
	'Them meeting at the age of five years old on the first day of kindergarten.',
	'Them getting a puppy/kitty, and arguing over names.',
	"<b>{A}</b> being careful (or not at all careful) taking off <b>{B}</b>'s shirt because <b>{B}</b> is extremely ticklish.",
	"<b>{A}</b> taking <b>{B}</b> out for Valentine's Day to cheer them up after their original plans with someone else fell through. As <b>{A}</b> tries their best to make <b>{B}</b> happy and succeeds after only a few attempts, <b>{B}</b> realizes they would have rather been with <b>{A}</b> anyways.",
	'<b>{B}</b> hurt their ankle and is laid up with a cast and crutches. <b>{A}</b> is sitting next to them, doodling little hearts on their cast to cheer them up.',
	"<b>{B}</b> lends their sweater to <b>{A}</b>. When <b>{A}</b> is home, they realize they still have <b>{B}</b>'s sweater and find <b>{B}</b>'s iPod. Out of curiosity, <b>{A}</b> looks through <b>{B}</b>'s music and finds a playlist titled with <b>{A}</b>'s name.",
	'<b>{A}</b> is alone in the rain because they forgot to bring an umbrella, <b>{B}</b> offers to share theirs.',
	'<b>{B}</b> telling really dumb or corny jokes to <b>{A}</b>, thinking they are so clever and funny. <b>{A}</b> just thinks <b>{B}</b> is adorable for thinking the jokes are funny.',
	"<b>{A}</b> teaching <b>{B}</b> how to kiss, and <b>{B}</b> ends up kissing <b>{A}</b> really quick, nervously asks 'Like that?' and leaves <b>{A}</b> silent and flustered for a moment.",
	'<b>{B}</b> absolutely loves the taste of the chap stick/lip balm <b>{A}</b> uses, so they keep stealing kisses from <b>{A}</b>.',
	"<b>{A}</b> and <b>{B}</b> falling asleep together with their heads on the other's shoulder/head in the backseat of the car while their friend is driving.",
	'<b>{B}</b> holding a sobbing <b>{A}</b>. <b>{A}</b> cries themselves to sleep with their face buried into <b>{B}</b>.',
	'<b>{A}</b> and <b>{B}</b> sleeping on top of each other (in the bed, couch, where ever you prefer) when <b>{B}</b> flops down on the floor.',
	"<b>{A}</b> seeing some of <b>{B}</b>'s night blogging.",
	'<b>{B}</b> burns their tongue on something hot, <b>{A}</b> kisses it better.',
	"<b>{B}</b> is a prince or princess, falling for <b>{A}</b>, the castle gardener who tends to the foliage surrounding <b>{B}</b>'s balcony.",
	"<b>{A}</b> and <b>{B}</b> watching a horror movie. <b>{A}</b> can't sleep that night and <b>{B}</b> comforts them in a cuddle.",
	"<b>{B}</b> tossing snowballs at <b>{A}</b>'s window, not knowing the window is open and has no screen.",
	"<b>{A}</b> and <b>{B}</b> sleeping together. <b>{A}</b> wakes up first and contemplates waking <b>{B}</b> with a kiss.<b>{A}</b> leans in only to hesitate centimeters away out of embarrassment. <b>{B}</b> opens their eyes and says, 'Well if you won't do it, I will.'",
	'<b>{B}</b> gets the hiccups, causing <b>{A}</b> to laugh every time they try to talk until <b>{A}</b> gets the hiccups too.',
	'<b>{A}</b> and <b>{B}</b> not speaking each other languages, falling in love and learning together.',
	'<b>{B}</b> and <b>{A}</b> break up, but they have a pet and neither of them want to give it up. Then they spend a few days each with the pet separately. But it kinda helps them get together again.',
	'<b>{A}</b> and <b>{B}</b> dancing in the moonlight.',
	'<b>{A}</b> and <b>{B}</b> at a theme park or carnival, and walking towards one of the many games to win a large stuffed animal. <b>{A}</b> is sure that they can win the game, but after many attempts (and a lot of cash down the drain) <b>{A}</b> gives up. <b>{B}</b>, however, tries and succeeds on their first go.',
	'<b>{B}</b> and <b>{A}</b> eating spaghetti like the lady and the tramp did in that animated film.',
	"<b>{B}</b> is a ghost who falls in love with <b>{A}</b>, but <b>{A}</b> can't see them. Does <b>{B}</b> do anything to make <b>{A}</b> notice them?",
	'<b>{A}</b> and <b>{B}</b> unable to sleep after watching a horror movie, but neither will admit that the movie scared them.',
	'<b>{B}</b> and <b>{A}</b> play Twister. Things get embarrassing and awkward fast.',
	'<b>{A}</b> trying to get something on their computer to work. While they’re getting frustrated and flipping out, <b>{B}</b> is sitting nearby cracking up.',
	"<b>{B}</b> likes stealing <b>{A}</b>'s phone to change <b>{A}</b>'s phone wallpaper into something stupid (like unattractive pictures of <b>{A}</b>'s face or doing something like picking their nose). <b>{B}</b> is doing another routine swipe of <b>{A}</b>'s phone, but doesn't have the heart to change it because this time because <b>{A}</b>'s phone wallpaper is a cute picture of the two of them (like their first date together, or the only picture they have together).",
	"<b>{A}</b> cuddling with a body pillow, pretending that it's <b>{B}</b>...",
	'<b>{B}</b> getting shy about being naked in front of <b>{A}</b> for the first time.',
	'<b>{A}</b> getting to go back in time and change something bad that happened in their past with <b>{B}</b>.',
	'<b>{A}</b> has amnesia and <b>{B}</b> is taking care of them. <b>{B}</b> tries their best to help <b>{A}</b> remember them.',
	"<b>{B}</b> and <b>{A}</b> were separated for several years for reasons they couldn't help. They finally find each other and have a heartfelt reunion.",
	'<b>{B}</b> and <b>{A}</b> stranded on a raft in the middle of a lake.',
	"<b>{A}</b>'s mom gives <b>{A}</b> and <b>{B}</b> very cheesy, matching shirts/sweaters/scarfs. <b>{B}</b> does their very best to pretend that they love it.",
	'<b>{B}</b> having to help <b>{A}</b> undress after an injury.',
	'<b>{A}</b> and <b>{B}</b> adopting an orphan.',
	"<b>{B}</b> snuggling up to <b>{A}</b> because i's cold.",
	"<b>{A}</b> using <b>{B}</b>'s lap as a pillow.",
	'<b>{B}</b> buying <b>{A}</b> a special treat when they go out shopping.',
	'<b>{A}</b> giving <b>{B}</b> a tight hug that makes them lose their breath.',
	'<b>{A}</b> staying up half the night to finish a game with <b>{B}</b>.',
	'<b>{B}</b> giving <b>{A}</b> a back massage when they flop on the couch or bed.',
	'<b>{B}</b> making a goofy face until <b>{A}</b> notices and laughs.',
	'<b>{A}</b> letting <b>{B}</b> warm their cold hands under their shirt.',
	'<b>{B}</b> trying their best to be quiet while <b>{A}</b> is taking a nap.',
	'<b>{A}</b> helping <b>{B}</b> dry and brush their hair after a shower.',
	'<b>{B}</b> running out in the middle of the night to get a food item that <b>{A}</b> is craving.',
	'<b>{A}</b> wrapping a blanket around <b>{B}</b> when they are sitting on the couch and watching a show.',
	"<b>{B}</b> tucking <b>{A}</b>'s hair behind their ear to help them get it out of their face.",
	'<b>{A}</b> sharing a drink with <b>{B}</b> from the same straw.',
	"<b>{A}</b> doing a chore they know <b>{B}</b> isn't fond of.",
	"<b>{B}</b> wearing clothes in <b>{A}</b>'s favorite color.",
  '<b>{A}</b> and <b>{B}</b> sharing a really long scarf.',
	'<b>{B}</b> tracing their names together in the sand.',
	'<b>{A}</b> writing <b>{B}</b> name in a heart/under the love umbrella/etc. in their notebook together with their own name.',
	'<b>{B}</b> and <b>{A}</b> sharing a soft smile across a crowded room.',
	"<b>{A}</b> and <b>{B}</b> having a tickle fight until they're breathless.",
	'<b>{B}</b> calming <b>{A}</b> down when they have a bad dream.',
	"<b>{A}</b> playing their fingers through <b>{B}</b>'s hair while sitting next to them on the couch.",
	"<b>{B}</b> following <b>{A}</b>'s family traditions that they enjoy.",
	'<b>{A}</b> telling <b>{B}</b> a dumb joke just to see their smile.',
	"<b>{A}</b> participating in <b>{B}</b>'s hobby even if it doesn't personally interest them.",
	'<b>{B}</b> buying <b>{A}</b> something unrequested because it made <b>{B}</b> think of them.',
	'<b>{B}</b> lightly kissing <b>{A}</b> on top of a freshly formed bruise.',
	'<b>{A}</b> giving <b>{B}</b> a kiss before going to work and they are still in bed.',
	'<b>{B}</b> making <b>{A}</b> their favorite meal when they are having a hard day.',
	'<b>{A}</b> helping <b>{B}</b> dry and brush their hair after a shower.',
	'<b>{B}</b> traveling long distances just to see <b>{A}</b>.',
	'<b>{B}</b> tucking the sheets around <b>{A}</b> when they stir during the night.',
	"<b>{B}</b> holding <b>{A}</b>'s hands when they are shaking.",
	'<b>{A}</b> and <b>{B}</b> spending the night on the perfect hill for stargazing.',
	'<b>{A}</b> and <b>{B}</b> on a large field with a fresh foot of snow.',
	'<b>{B}</b> and <b>{A}</b> throwing food for the ducks at the duck pond.',
	'<b>{B}</b> and <b>{A}</b> sitting on the couch that is really soft and sinking into the cushions..',
	'<b>{A}</b> and <b>{B}</b> under a large fruit tree in the middle of summer.',
	'<b>{B}</b> and <b>{A}</b> playing games in the small arcade.',
	'<b>{A}</b> and <b>{B}</b> going to explore an abandoned house on the edge of town.',
	'<b>{B}</b> and <b>{A}</b> chilling out on beds and couches at a furniture store.',
	'<b>{A}</b> and <b>{B}</b> playing on the swings at a small playground that nobody goes to anymore.',
	'<b>{A}</b> and <b>{B}</b> lighting fall-scented candles.',
	'<b>{B}</b> and <b>{A}</b> carving faces in pumpkins.',
	'<b>{A}</b> and <b>{B}</b> making crafts.',
	'<b>{A}</b> and <b>{B}</b> decorating their house with seasonal decorations.',
	'<b>{B}</b> and <b>{A}</b> raking up leaves and jumping into them.',
	'<b>{A}</b> and <b>{B}</b> drowning in oversized sweaters during chilly days.',
	'<b>{A}</b> and <b>{B}</b> finger painting with their child.',
	"<b>{A}</b> and <b>{B}</b>'s child coming to sleep with them after having a bad dream.",
	'<b>{A}</b> and <b>{B}</b> remembering their first kiss… and they have very different takes on it.',
	'<b>{B}</b> hiding in a closet to jump out and surprise <b>{A}</b>, but <b>{A}</b> just keeps not going near the closet by chance.',
	'<b>{B}</b> and <b>{A}</b> making wishes.',
	'<b>{A}</b> and <b>{B}</b>  living together for the first time.',
	'<b>{B}</b> and <b>{A}</b> backpacking across the world.',
	'<b>{B}</b> and <b>{A}</b> texting. Or better yet, writing letters to each other.',
	"<b>{A}</b> and <b>{B}</b> holding hands because there's a crowd but not letting go when they get out of it.",
	'<b>{A}</b> having to rescue <b>{B}</b> from a pack of kittens/puppies.',
	"<b>{A}</b> and <b>{B}</b> meeting on a train when <b>{B}</b> falls asleep on <b>{A}</b>'s shoulder.",
	'<b>{B}</b> and <b>{A}</b> playing in water and splashing each other.',
	'<b>{A}</b> and <b>{B}</b> shopping, with one of them being way more excited about it than the other who just kinda drags around and carries their bags.',
	'They meet when <b>{A}</b> sees <b>{B}</b> walk into a street sign.',
	"<b>{B}</b> breaking into <b>{A}</b>'s room through their window.",
	'<b>{A}</b> and <b>{B}</b> cooking something without the recipe, because <b>{B}</b> is confident they know how to cook it from memory.',
	'<b>{B}</b> and <b>{A}</b> taking couple quizzes on the Internet.',
	'<b>{A}</b> is scared of the thunder and <b>{B}</b> tries to calm them down during an particulary heavy strom.',
	"<b>{B}</b> kissing away <b>{A}</b>'s tears.",
	'<b>{A}</b> and <b>{B}</b> sharing ice cream/cake/a dessert.',
	'<b>{A}</b>: guess what <br> <b>{B}</b>: what <br> <b>{A}</b>: i love you <br> <b>{B}</b>:  O:',
	'<b>{A}</b> and <b>{B}</b> are a pair of ghosts haunting a house, and every day they try to outcompete each other in scaring whoever comes in.',
	'<b>{B}</b> gets into a heated argument with someone. <b>{B}</b> begins threatening them, so <b>{A}</b>, picks up <b>{B}</b> and carries/drags them out of the room before anyone gets hurt.',
	'<b>{A}</b> and <b>{B}</b> becoming YouTubers/vloggers.',
	"<b>{B}</b> and <b>{A}</b> aren't together yet, but they like each other and they are mutuals on twitter/tumblr. <b>{A}</b> accidentally publishes a tweet/post about their crush on <b>{B}</b> on their main account, when they meant to put it on a private side account. <b>{B}</b> is too dense to realize it's obviously about them, but it still worries them enough to ask a rather mortified <b>{A}</b> about it.",
	'<b>{A}</b> is a special effects make-up artist and <b>{B}</b> always volunteers as their model when they want to try something new.',
	'<b>{B}</b> showing <b>{A}</b> some of their favorite viral videos/memes.',
	'<b>{B}</b> and <b>{A}</b> getting locked in a store.',
	"<b>{B}</b> getting up in the middle of the night to make a snack and accidentally waking up <b>{A}</b> because they didn't stop the microwaves obnoxious beeping in time.",
	'<b>{A}</b> and <b>{B}</b> burning something together.',
	'<b>{B}</b> and <b>{A}</b> wearing each other’s clothes.',
	'<b>{A}</b> and <b>{B}</b> just booping noses.',
	"<b>{B}</b> and <b>{A}</b> each other. <b>{A}</b> makes a spectacular drawing and <b>{B}</b>'s drawing does turn out to be that good. However, <b>{A}</b> keeps <b>{B}</b>'s drawing and treasures it.",
	'<b>{A}</b> and <b>{B}</b>  reading mean tweets/comments about themselves and laughing it off.',
	'<b>{B}</b> and <b>{A}</b> getting lost in IKEA.',
	"<b>{B}</b> trying to mooch off of <b>{A}</b>'s wifi and jokingly putting their own name in as the password, then being shocked that it actually works and they're now connected to <b>{A}</b>'s wifi...",
	'<b>{A}</b> having to comfort <b>{B}</b> because <b>{B}</b> just encountered a very large, unpleasant bug outside that scared them.',
	"<b>{B}</b> and <b>{A}</b> go on a camping trip. <b>{B}</b> forgets to bring a sleeping bag, so they have to squeeze into <b>{A}</b>'s sleeping bag with them.",
	'<b>{B}</b> catches a cold so <b>{A}</b> makes them breakfast in bed.',
	"<b>{A}</b> falling asleep in <b>{B}</b>'s lap. <b>{B}</b> holds <b>{A}</b> close and doesn't move from their spot for hours.",
	"<b>{B}</b> making a video 'proving' that <b>{A}</b> is the Illuminati, complete with The X-Files theme.",
	'<b>{A}</b> and <b>{B}</b> as characters in a really crappy free-to-play MMORPG with super skimpy armor.',
	'<b>{B}</b> giving <b>{A}</b> a piggyback ride.',
	'<b>{A}</b> princess carrying <b>{B}</b>.',
	"<b>{B}</b> and <b>{A}</b> as a superhero/sidekick duo, but <b>{B}</b> is constantly messing up and getting in <b>{A}</b>'s way during their crime-fighting missions.",
	"<b>{A}</b> and <b>{B}</b> going to a drive-thru fast food place. When they get home, it is discovered that the staff did not prepare <b>{A}</b>'s order properly. Despite <b>{A}</b> insisting they don't mind, <b>{B}</b> drives back to the fast food place to demand a new meal be made for <b>{A}</b>.",
	"<b>{B}</b>  trying to set up their character with <b>{B}</b>'s character in a life simulation game. After months of trying to get the two together, they scream in triumph when it finally works.",
	"<b>{B}</b> screaming over a picture of <b>{A}</b> from long before they met. <b>{B}</b> describes the younger <b>{A}</b> as a tiny precious child, then looks at <b>{A}</b>, and says 'Well, you're still a tiny precious child'.",
	'<b>{B}</b> and <b>{A}</b> attending a school for kids with disabilities.',
	'<b>{A}</b> and <b>{B}</b> trying to do a three legged race.',
	"<b>{B}</b> holding <b>{A}</b> very close, close enough to smell their hair. They whisper into <b>{A}</b>'s ear: 'I don't like your new shampoo'",
	"A friend drawing on <b>{A}</b> and <b>{B}</b>'s faces when they sleep. They wake up to see each other faces covered in silly doodles.",
	"<b>{B}</b> is playing a video game/reading a book/watching a show and is talking about how they ship two of the characters together because of [insert cute reason here], and then <b>{A}</b> says 'that sounds like you and me right there'.",
	'<b>{A}</b> hogs all the blankets and <b>{B}</b> gets cold so they cling tightly to <b>{A}</b> for warmth.',
	"<b>{B}</b>:I'm gonna do the thing <br><b>{A}</b>:That's probably a bad idea <br><b>{B}</b>:*does the thing* <br><b>{A}</b>:holyshit.",
	'<b>{A}</b> and <b>{B}</b> discovering a hidden treasure.',
	'<b>{A}</b> coming home from a cuddly date with <b>{B}</b> and realizing that their shirt smells like <b>{B}</b>. <b>{A}</b> pulls their shirt up to their face to smell it before it fades away.',
	'<b>{B}</b> giving <b>{A}</b> a back massage when they flop on the couch or bed.',
	"<b>{B}</b> falls asleep in <b>{A}</b>'s lap and <b>{A}</b> has a conversation with someone else while stroking <b>{B}</b>'s hair as if they were a sleeping cat.",
	"<b>{A}</b> and <b>{B}</b> and their friends end up having to all sleep in the same room.  Nobody can get any sleep because <b>{B}</b> is snoring incredibly loud... Except for <b>{A}</b>, who's completely used to it.",
	'<b>{B}</b> and <b>{A}</b> wearing matching Halloween costumes or ugly Christmas sweaters. Or any matching outfits.',
	'<b>{A}</b> knitting something for <b>{B}</b>.',
	"<b>{B}</b> captioning everything <b>{A}</b> does with 'That's hot/cute'.",
	'<b>{A}</b> and <b>{B}</b> sucking helium and talking in very high-pitched voices.',
	"<b>{B}</b> reading in bed while <b>{A}</b> rests their head on <b>{B}</b>'s shoulder, sleeping.",
	"<b>{A}</b> goes over to <b>{B}</b>'s home after staying up all night. Even though they do their best to stay awake, they end up falling asleep while cuddling <b>{B}</b>. <b>{A}</b> is quite embarrassed (and half-asleep) when they wake up, but <b>{B}</b> doesn't mind.",
	'<b>{A}</b>:Ah shit <br><b>{B}</b>Watch your fucking language',
	'<b>{B}</b> and <b>{A}</b> struggling to find each other in a crowded place. Fortunately, <b>{B}</b> knows just the thing.',
	"<b>{B}</b> and <b>{A}</b> carrying around balloons so they don't get lost in the crowd.",
	'<b>{A}</b> posts a picture of <b>{B}</b> somewhere and it becomes a meme.',
	"<b>{B}</b>: What am I supposed to do while you're gone <br><b>{A}</b>: ... What do you usually do when I'm gone <br><b>{B}</b>: Wait for you to come back",
	'<b>{A}</b> and <b>{B}</b> as the main characters in the last show you watched/book you read/game you played.',
	'<b>{B}</b> spending all their money on <b>{A}</b>, who scolds them for it.',
	'<b>{A}</b> and <b>{B}</b> playing a co-op video game and <b>{A}</b> keeps dicking around and <b>{B}</b> just wants to get past the first level god dammit.',
	"<b>{B}</b> staring admiringly at <b>{A}</b> from across the room. A friend whispers into <b>{B}</b>'s ear: 'Why are you so thirsty?'",
	"<b>{A}</b> booping <b>{B}</b>'s nose with their finger.",
	"<b>{A}</b> is a genie. <b>{B}</b> stumbles upon <b>{A}</b>, and they wish for <b>{A}</b> to be free so they can be <b>{B}</b>'s new friend. This seems awkward to <b>{A}</b> at first, but they warm up to <b>{B}</b> and end up crushing on them.",
	"<b>{A}</b> touching <b>{B}</b>'s face and telling them that their face is really soft.",
	'<b>{B}</b> and <b>{A}</b> are about to kiss when instead they accidentally hit foreheads really hard and have matching bruises.',
	'<b>{A}</b> giving <b>{B}</b> a kiss before going to work and they are still in bed.',
	"<b>{B}</b> telling <b>{A}</b> a story but <b>{A}</b> isn't paying attention at all because they;re too busy thinking about what a cutie <b>{B}</b> is.",
	"<b>{A}</b> is the barista at a coffee shop and always screws up <b>{B}</b>'s name on purpose.",
	'<b>{B}</b> and <b>{A}</b> getting sick at the same time.',
	'<b>{B}</b> sings extremely well but has a lot of difficulty playing musical instruments and <b>{A}</b> can play their musical instrument very well but their singing voice is terrible.',
	"<b>{B}</b> and <b>{A}</b> haven't kissed yet. Each time <b>{B}</b> sees <b>{A}</b> they think to themselves 'I've gotta do it this time' but they keep being too shy to do anything. One day a friend asks <b>{B}</b> if <b>{A}</b> has ever tried to kiss them and <b>{B}</b> just screams.",
	'<b>{A}</b> and <b>{B}</b> literally sitting in a tree, kissing..',
	'Imagine <b>{A}</b> and <b>{B}</b>.',
	"<b>{B}</b> pressing their forehead against <b>{A}</b>'s forehead to check if they have a fever.",
	"<b>{B}</b> reminiscing about the time they first met <b>{A}</b>. They're still in awe of how far they've come.",
	'<b>{A}</b> making <b>{B}</b> some hot chocolate.',
	'<b>{B}</b> and <b>{A}</b> having a snowball fight.',
	"<b>{A}</b> and <b>{B}</b> spending their New Year's Eve on a party with their friends and sharing their New Year's kiss in front of everyone.",
	'<b>{B}</b> and <b>{A}</b> walking through town, holding hands while it snows.',
	"<b>{A}</b> and <b>{B}</b> trying to hide their relationship. However, it turns out everyone knows they're dating.",
	'<b>{B}</b> makes breakfast for <b>{A}</b> after staying the night.',
	'<b>{A}</b> and <b>{B}</b> makes breakfast together, after spending the night together.',
	'<b>{A}</b> does house chores.',
	'<b>{A}</b> and <b>{B}</b> does chores around the house, dividing the work.',
	'<b>{A}</b> and <b>{B}</b> does chores around the house, but <b>{B}</b> slacks off.',
	'<b>{B}</b> is reading a book.',
	'<b>{A}</b> goes through their morning routine.',
	'<b>{A}</b> and <b>{B}</b> goes through their morning routine, chatting about the plans for the day.',
	'<b>{A}</b> goes through their bedtime routine.',
	'<b>{A}</b> and <b>{B}</b> goes through their bedtime routine, chatting about the things that happened during the day.',
	'<b>{A}</b> is grocery shopping.',
	'<b>{A}</b> and <b>{B}</b> is grocery shopping together and <b>{A}</b> keeps trying to buy random stuff.',
	'<b>{A}</b> leaves a note for <b>{B}</b>.',
	'<b>{A}</b> and <b>{B}</b> is packing for a trip together.',
	'<b>{A}</b> and <b>{B}</b> is packing for a trip together and <b>{B}</b> is procroastinating.',
	'<b>{B}</b> leaves for work/school/errands in the morning and says goodbye to <b>{A}</b>.',
	'<b>{B}</b> experiences disappointment.',
	'<b>{A}</b> celebrates an anniversary.',
	'<b>{A}</b> and <b>{B}</b> celebrates an anniversary.',
	'<b>{A}</b> and <b>{B}</b> share a hobby.',
	'<b>{A}</b> and <b>{B}</b> commute together.',
	'<b>{B}</b> commutes to work/school/errands.',
	'<b>{A}</b> and <b>{B}</b> try to stay cool on a hot day.',
	'The car breaks down.',
	'<b>{A}</b> has had an argument and <b>{B}</b> helps them calm down.',
	'<b>{A}</b> and <b>{B}</b> had an argument.',
	'<b>{A}</b> and <b>{B}</b> was caught in the middle of an argument.',
	'<b>{A}</b> is bored.',
	'<b>{A}</b> and <b>{B}</b> goes to the movies.',
	'<b>{A}</b> and <b>{B}</b> has a date night.',
	'<b>{B}</b> lost the keys.',
	'<b>{A}</b> has bad news.',
	'<b>{B}</b> has bad news for <b>{A}</b> and doesnt know how to break the news.',
	'<b>{B}</b> has good news for <b>{A}</b> and cant wait to share the news.',
	'<b>{A}</b> is standing in line for frozen yogurt, eavesdropping on two girls in line.',
	'<b>{A}</b> and <b>{B}</b> is standing in line for frozen yogurt, eavesdropping on two girls in line.',
	'<b>{B}</b> is daydreaming.',
	'<b>{B}</b> is waiting to be picked up.',
	'<b>{B}</b> teases someone and blames it on <b>{A}</b> before running away laughing.',
	'<b>{A}</b> approaches <b>{B}</b> to talk but gets flustered and leaves without saying a word.',
	'<b>{A}</b> is approached by <b>{B}</b> who stands there not saying a word, before leaving from getting flustered, confusing <b>{A}</b>.',
	'<b>{B}</b> gets embarrassed.',
	"<b>{B}</b>'s mind goes blank after <b>{A}</b> smiles at them.",
	"<b>{A}</b> gets sad when <b>{B}</b> isn't where they usually are.",
	'<b>{B}</b> is ignored by <b>{A}</b>.',
	'<b>{A}</b> and <b>{B}</b> share an umbrella.',
	'<b>{A}</b> forgets their umbrella.',
	'<b>{A}</b> and <b>{B}</b> has an afternoon tea together.',
	'<b>{B}</b> sees <b>{A}</b> and runs after them.',
	'<b>{A}</b> sees <b>{B}</b> and runs after them, scaring them from the sudden charge.',
	'<b>{A}</b> helps <b>{B}</b> lift the grocery bags.',
	"<b>{B}</b> show's an embarrassing photo to <b>{A}</b>.",
	'<b>{A}</b> prepares their home for <b>{B}</b> to come visit.',
	'<b>{B}</b> is extremely overjoyed from talking with/dating <b>{A}</b>.',
	'<b>{B}</b> jumps with joy.',
	'<b>{A}</b> wraps their jacket around <b>{B}</b> on a cold night.',
	'<b>{A}</b> wraps their jacket around <b>{B}</b> on a cold night, sharing the jacket together.',
	'<b>{A}</b> and <b>{B}</b> reaffirms their love.',
	'<b>{A}</b> takes funny photos of <b>{B}</b>.',
	'<b>{B}</b> secretly takes a picture of <b>{A}</b>.',
	'<b>{B}</b> gets sick.',
	'<b>{B}</b> takes care of a sick <b>{A}</b>.',
	'<b>{B}</b> has a nightmare.',
	'<b>{A}</b> consoles <b>{B}</b> after a nightmare.',
	"<b>{A}</b> doesn't want to take medicine, since it takes bad.",
	'<b>{B}</b> dances in the rain with an umbrella.',
	'<b>{B}</b> dances in the rain without an umbrella.',
	'<b>{A}</b> consoles <b>{B}</b> after an episode from mental scarring.',
	'<b>{A}</b> finds <b>{B}</b> waiting somewhere.',
	'Clothes got wet and has to be dried off.',
	'<b>{B}</b> unexpectantly hugs <b>{A}</b> to save them from something.',
	'<b>{A}</b> unexpectantly hugs <b>{B}</b> to save them from something and they linger.',
	'<b>{A}</b> and <b>{B}</b> hugs.',
	'<b>{A}</b> feeds <b>{B}</b>.',
	'<b>{B}</b> feeds <b>{A}</b> and share an indirect kiss.',
	'<b>{A}</b> thinks <b>{B}</b> is going to feed them and <b>{B}</b> laughs lovingly at <b>{A}</b>.',
	"<b>{A}</b> gets <b>{B}</b>'s phone number.",
	'<b>{A}</b> and <b>{B}</b> displays PDA.',
	'<b>{A}</b> and <b>{B}</b> is lovey-dovey in front of friends.',
	'<b>{B}</b> waits for <b>{A}</b> to show up on their usual route, pretending to just arrive but has secretly been waiting.',
	'<b>{A}</b> and <b>{B}</b> tries to get past each other in a doorway, awkwardly mirroring each other.',
	"<b>{B}</b> laughs at <b>{A}</b> and makes <b>{A}</b>'s heart skip a beat.",
	'<b>{A}</b> paints <b>{B}</b>.',
	'<b>{A}</b> confesses to <b>{B}</b>.',
	'<b>{B}</b> sends a message to <b>{A}</b>, lovingly reminding them of something minor.',
	'<b>{B}</b> and <b>{A}</b> takes a stroll through a park, enjoying the small things.',
	'After a long day, <b>{A}</b> invites <b>{B}</b> to a well-known lookout point late in the evening to enjoy the view over the city at night.',
	'<b>{A}</b> and <b>{B}</b> resting together and talking to each other before falling asleep.',
	"<b>{B}</b> and <b>{A}</b> exploring each others' bodies, but not in a sexual way. Finding their different birthmarks, looking over each others' scars and sharing the stories behind them, running their hands over one another and just appreciating the feeling of the other person next to them.",
	'<b>{A}</b> and <b>{B}</b> go to a fair/amusement park and <b>{A}</b> wants to go on the roller coaster and <b>{B}</b> agrees. Later, <b>{B}</b> regrets their decision and ends up clinging onto <b>{A}</b> for dear life.',
	'<b>{B}</b> and <b>{A}</b> are on a ferris wheel, and everything is going great - until it gets stuck at the very top. For thirty whole minutes.',
	'<b>{B}</b> prevents <b>{A}</b> from getting out of bed by cuddling them.',
	"<b>{A}</b> is about to leave for work. <b>{B}</b> asks them if they've forgotten anything, and <b>{A}</b> gives them a kiss. <b>{B}</b> turns red and opens their hand to reveal <b>{A}</b>'s keys/wallet/etc., saying 'I meant this, but thanks.'",
	"<b>{A}</b> and <b>{B}</b> playing with sidewalk chalk like they're kids again.",
	'<b>{A}</b> and <b>{B}</b> huddled by the fireplace at night after spending the day in the fresh snow.',
	"<b>{B}</b> and <b>{A}</b>'s first holiday season together.",
	'<b>{B}</b> wants to use their laptop on the couch, but <b>{A}</b> always occupies the space in their lap.',
	"<b>{A}</b> doesn't like talking on the phone, but <b>{B}</b> always calls them instead of texting. <b>{B}</b> admits that it's because they want to hear <b>{A}</b>'s voice.",
	'<b>{A}</b> wakes to find that it had snowed overnight and gets excited about playing in it. <b>{B}</b> gets excited because this means that when <b>{A}</b> comes inside, it will be time for cuddling by the fire.',
	'<b>{B}</b> drags <b>{A}</b> into the freezing cold to make a snowman.',
	'<b>{B}</b> and <b>{A}</b> adopting a pet, and arguing over potential names.',
	"<b>{A}</b> being careful (or not at all careful) taking off <b>{B}</b>'s shirt because <b>{B}</b> is extremely ticklish.",
	"<b>{A}</b> taking <b>{B}</b> out for Valentine's Day to cheer them up after their original plans with someone else fell through. As <b>{A}</b> tries their best to make <b>{B}</b> happy and succeeds after only a few attempts, <b>{B}</b> realizes they would have rather been with <b>{A}</b> anyways.",
	'<b>{B}</b> hurt their ankle and is laid up with a cast and crutches. <b>{A}</b> is sitting next to them, doodling little hearts on their cast to cheer them up.',
	"<b>{B}</b> lends their jacket to <b>{A}</b>. When <b>{A}</b> is home, they realize they still have <b>{B}</b>'s sweater and find <b>{B}</b>'s iPod. Out of curiosity, <b>{A}</b> looks through <b>{B}</b>'s music and finds a playlist titled with <b>{A}</b>'s name.",
	'<b>{A}</b> is alone in the rain because they forgot to bring an umbrella, <b>{B}</b> offers to share theirs.',
	'<b>{B}</b> telling really dumb or corny jokes to <b>{A}</b>, thinking they are so clever and funny. <b>{A}</b> just thinks <b>{B}</b> is adorable for thinking the jokes are funny.',
	"<b>{A}</b> teaching <b>{B}</b> how to kiss, and <b>{B}</b> ends up kissing <b>{A}</b> really quick, nervously asks 'Like that?' and leaves <b>{A}</b> silent and flustered for a moment.",
	'<b>{B}</b> absolutely loves the taste of the chap stick/lip balm <b>{A}</b> uses, so they keep stealing kisses from <b>{A}</b>.',
	"<b>{A}</b> and <b>{B}</b> falling asleep together with their heads on the other's shoulder/head in the backseat of the car while their friend is driving.",
	'<b>{B}</b> holding a sobbing <b>{A}</b>. <b>{A}</b> cries themselves to sleep with their face buried into <b>{B}</b>.',
	'<b>{A}</b> and <b>{B}</b> sleeping on top of each other (bed, couch, hammock, etc.) when <b>{B}</b> falls down on the floor.',
	"<b>{A}</b> and <b>{B}</b> watching a horror movie. <b>{A}</b> can't sleep that night and <b>{B}</b> comforts them in a cuddle.",
	"<b>{B}</b> tossing snowballs at <b>{A}</b>'s window, not knowing the window is open and has no screen.",
	'<b>{B}</b> gets the hiccups, causing <b>{A}</b> to laugh every time they try to talk until <b>{A}</b> gets the hiccups too.',
	'<b>{B}</b> and <b>{A}</b> break up, but they have a pet and neither of them want to give it up. Then they spend a few days each with the pet separately. But it kinda helps them get together again.',
	'<b>{A}</b> and <b>{B}</b> at a theme park or carnival, and walking towards one of the many games to win a large stuffed animal. <b>{A}</b> is sure that they can win the game, but after many attempts (and a lot of cash down the drain) <b>{A}</b> gives up. <b>{B}</b>, however, tries and succeeds on their first go.',
	'<b>{A}</b> and <b>{B}</b> unable to sleep after watching a horror movie, but neither will admit that the movie scared them.',
	'<b>{A}</b> trying to get something on their computer to work. While they’re getting frustrated and flipping out, <b>{B}</b> is sitting nearby cracking up.',
	"<b>{B}</b> likes stealing <b>{A}</b>'s phone to change <b>{A}</b>'s phone wallpaper into something stupid (like unattractive pictures of <b>{A}</b>'s face or doing something like picking their nose). <b>{B}</b> is doing another routine swipe of <b>{A}</b>'s phone, but doesn't have the heart to change it because this time because <b>{A}</b>'s phone wallpaper is a cute picture of the two of them (like their first date together, or the only picture they have together).",
	"<b>{A}</b> cuddling with a body pillow, pretending that it's <b>{B}</b>.",
	'<b>{B}</b> getting shy about being naked in front of <b>{A}</b> for the first time.',
	"<b>{B}</b> and <b>{A}</b> were separated for several years for reasons they couldn't help. They finally find each other and have a heartfelt reunion.",
	"<b>{A}</b>'s mom gives <b>{A}</b> and <b>{B}</b> very cheesy, matching shirts/sweaters/scarfs. <b>{B}</b> does their very best to pretend that they love it.",
	'<b>{B}</b> having to help <b>{A}</b> undress after an injury.',
	"<b>{B}</b> snuggling up to <b>{A}</b> because it's cold.",
	"<b>{A}</b> using <b>{B}</b>'s lap as a pillow.",
	'<b>{B}</b> buying <b>{A}</b> a special treat when they go out shopping.',
	'<b>{A}</b> giving <b>{B}</b> a tight hug that makes them lose their breath.',
	'<b>{A}</b> staying up half the night to finish a game with <b>{B}</b>.',
	'<b>{B}</b> giving <b>{A}</b> a back massage when they flop on the couch or bed.',
	'<b>{B}</b> making a goofy face until <b>{A}</b> notices and laughs.',
	'<b>{B}</b> trying their best to be quiet while <b>{A}</b> is taking a nap.',
	'<b>{A}</b> helping <b>{B}</b> dry and brush their hair after a shower.',
	'<b>{B}</b> running out in the middle of the night to get a snack that <b>{A}</b> is craving.',
	'<b>{A}</b> wrapping a blanket around <b>{B}</b> when they are sitting on the couch and watching a show.',
	"<b>{B}</b> tucking <b>{A}</b>'s hair behind their ear to help them get it out of their face.",
	'<b>{A}</b> sharing a drink with <b>{B}</b> from the same straw.',
	"<b>{A}</b> doing a chore they know <b>{B}</b> isn't fond of.",
	"<b>{B}</b> wearing clothes in <b>{A}</b>'s favorite color.",
	'<b>{B}</b> tracing their names together in the sand.',
	'<b>{A}</b> writing <b>{B}</b> name in a heart/under the love umbrella/etc. in their notebook together with their own name.',
	'<b>{B}</b> and <b>{A}</b> sharing a soft smile across a crowded room.',
	"<b>{A}</b> and <b>{B}</b> making out until they're breathless.",
	'<b>{B}</b> calming <b>{A}</b> down when they have a bad dream.',
	"<b>{B}</b> following <b>{A}</b>'s family traditions that they enjoy.",
	'<b>{A}</b> telling <b>{B}</b> a dumb joke just to see their smile.',
	"<b>{A}</b> participating in <b>{B}</b>'s hobby even if it doesn't personally interest them.",
	'<b>{B}</b> buying <b>{A}</b> something unrequested because it made <b>{B}</b> think of them.',
	'<b>{B}</b> lightly kissing <b>{A}</b> on top of a freshly formed bruise.',
	'<b>{A}</b> giving <b>{B}</b> a kiss before going to work and they are still in bed.',
	'<b>{B}</b> making <b>{A}</b> their favorite meal when they are having a hard day.',
	'<b>{B}</b> traveling long distances just to see <b>{A}</b>.',
	'<b>{B}</b> tucking the sheets around <b>{A}</b> when they stir during the night.',
	"<b>{B}</b> holding <b>{A}</b>'s hands when they are shaking.",
	'<b>{A}</b> and <b>{B}</b> spending the night on the perfect hill for stargazing.',
	'<b>{B}</b> and <b>{A}</b> throwing food for the ducks at the duck pond.',
	'<b>{A}</b> and <b>{B}</b> having a picnic under a large fruit tree in the middle of summer.',
	'<b>{A}</b> and <b>{B}</b> going to explore an abandoned house on the edge of town.',
	'<b>{B}</b> and <b>{A}</b> testing beds and couches at a furniture store.',
	'<b>{A}</b> and <b>{B}</b> playing on the swings at a small playground that nobody goes to anymore.',
	'<b>{A}</b> and <b>{B}</b> lighting fall-scented candles.',
	'<b>{B}</b> and <b>{A}</b> carving pumpkins.',
	'<b>{A}</b> and <b>{B}</b> making crafts and having a playful argument over their creative differences.',
	'<b>{A}</b> and <b>{B}</b> decorating their house with seasonal decorations.',
	'<b>{A}</b> and <b>{B}</b> drowning in oversized sweaters during chilly days.',
	"<b>{A}</b> and <b>{B}</b>'s child coming to sleep with them after having a bad dream.",
	'<b>{A}</b> and <b>{B}</b> remembering their first kiss… and they have very different takes on it.',
	'<b>{B}</b> hiding in a closet to jump out and surprise <b>{A}</b>, but <b>{A}</b> just keeps not going near the closet by chance.',
	'<b>{B}</b> and <b>{A}</b> tossing coins in a well and making wishes.',
	'<b>{A}</b> and <b>{B}</b>  living together for the first time.',
	'<b>{B}</b> and <b>{A}</b> texting.',
	'<b>{A}</b> and <b>{B}</b> writing letters to each other.',
	"<b>{A}</b> and <b>{B}</b> holding hands because there's a crowd but not letting go when they get out of it.",
	'<b>{B}</b> and <b>{A}</b> going swimming together.',
	'<b>{A}</b> and <b>{B}</b> shopping, with one of them being way more excited about it than the other who just kinda drags around and carries their bags.',
	"<b>{B}</b> sneaking into <b>{A}</b>'s room through their window.",
	'<b>{A}</b> and <b>{B}</b> cooking something without the recipe, because <b>{B}</b> is confident they know how to cook it from memory.',
	"<b>{B}</b> and <b>{A}</b> taking couple's quizzes on the Internet.",
	'<b>{A}</b> is scared of the thunder and <b>{B}</b> tries to calm them down during an particularly heavy storm.',
	'<b>{A}</b> and <b>{B}</b> sharing ice cream/cake/a dessert.',
	'<b>{B}</b> gets into a heated argument with someone. <b>{B}</b> begins threatening them, so <b>{A}</b>, picks up <b>{B}</b> and carries/drags them out of the room before anyone gets hurt.',
	'<b>{B}</b> and <b>{A}</b> getting locked in a store after closing.',
	"<b>{B}</b> getting up in the middle of the night to make a snack and accidentally waking up <b>{A}</b> because they didn't stop the microwave's obnoxious beeping in time.",
	"<b>{B}</b> and <b>{A}</b> are drawing each other. <b>{A}</b> makes a spectacular drawing and <b>{B}</b>'s drawing does turn out to be that good. However, <b>{A}</b> keeps <b>{B}</b>'s drawing and treasures it.",
	'<b>{A}</b> having to comfort <b>{B}</b> because <b>{B}</b> just encountered a very large, unpleasant bug outside that scared them.',
	"<b>{B}</b> and <b>{A}</b> go on a camping trip. <b>{B}</b> forgets to bring a sleeping bag, so they have to squeeze into <b>{A}</b>'s sleeping bag with them.",
	'<b>{B}</b> catches a cold so <b>{A}</b> makes them breakfast in bed.',
	"<b>{A}</b> falling asleep in <b>{B}</b>'s lap. <b>{B}</b> holds <b>{A}</b> close and doesn't move from their spot for hours.",
	'<b>{B}</b> giving <b>{A}</b> a piggyback ride.',
	"<b>{A}</b> and <b>{B}</b> going to a drive-thru fast food place. When they get home, it is discovered that the staff did not prepare <b>{A}</b>'s order properly. Despite <b>{A}</b> insisting they don't mind, <b>{B}</b> drives back to the fast food place to demand a new meal be made for <b>{A}</b>.",
	"<b>{B}</b> screaming over a picture of <b>{A}</b> from long before they met. <b>{B}</b> describes the younger <b>{A}</b> as a tiny precious child, then looks at <b>{A}</b>, and says 'Well, you're still a tiny precious child'.",
	"<b>{B}</b> holding <b>{A}</b> very close, close enough to smell their hair. They whisper into <b>{A}</b>'s ear: 'I don't like your new shampoo'",
	"A friend drawing on <b>{A}</b> and <b>{B}</b>'s faces when they sleep. They wake up to see each other faces covered in silly doodles.",
	'<b>{A}</b> hogs all the blankets and <b>{B}</b> gets cold so they cling tightly to <b>{A}</b> for warmth.',
	'<b>{A}</b> coming home from a cuddly date with <b>{B}</b> and realizing that their shirt smells like <b>{B}</b>. <b>{A}</b> pulls their shirt up to their face to smell it before it fades away.',
	"<b>{B}</b> falls asleep in <b>{A}</b>'s lap and <b>{A}</b> has a conversation with someone else while stroking <b>{B}</b>'s hair as if they were a sleeping cat.",
	"<b>{B}</b> reading in bed while <b>{A}</b> rests their head on <b>{B}</b>'s shoulder, sleeping.",
	"<b>{A}</b> goes over to <b>{B}</b>'s home after staying up all night. Even though they do their best to stay awake, they end up falling asleep while cuddling <b>{B}</b>. <b>{A}</b> is quite embarrassed (and half-asleep) when they wake up, but <b>{B}</b> doesn't mind.",
	'<b>{A}</b>: Ah shit <br><b>{B}</b>: Watch your fucking language',
	"<b>{B}</b> and <b>{A}</b> carrying around balloons so they don't get lost in the crowd.",
	'AU: <b>{A}</b> and <b>{B}</b> as the main characters in the last show you watched/book you read/game you played.',
	'<b>{B}</b> spending all their money on <b>{A}</b>, who scolds them for it.',
	'<b>{A}</b> and <b>{B}</b> playing a co-op video game and <b>{A}</b> keeps dicking around and <b>{B}</b> just wants to get past the first level god dammit.',
	"<b>{B}</b> staring admiringly at <b>{A}</b> from across the room. A friend whispers into <b>{B}</b>'s ear: 'Why are you so thirsty?'",
	"<b>{A}</b> touching <b>{B}</b>'s face and telling them that their face is really soft.",
	'<b>{B}</b> and <b>{A}</b> are about to kiss when instead they accidentally hit foreheads really hard and have matching bruises.',
	"<b>{B}</b> telling <b>{A}</b> a story but <b>{A}</b> isn't paying attention at all because they're too busy thinking about what a cutie <b>{B}</b> is.",
	"AU: <b>{A}</b> is the barista at a coffee shop and always screws up <b>{B}</b>'s name on purpose.",
	'<b>{B}</b> and <b>{A}</b> getting sick at the same time.',
	'<b>{B}</b> sings extremely well but has a lot of difficulty playing musical instruments and <b>{A}</b> can play their musical instrument very well but their singing voice is terrible.',
	"<b>{B}</b> and <b>{A}</b> haven't kissed yet. Each time <b>{B}</b> sees <b>{A}</b> they think to themselves 'I've gotta do it this time' but they keep being too shy to do anything. One day a friend asks <b>{B}</b> if <b>{A}</b> has ever tried to kiss them and <b>{B}</b> just screams.",
	"<b>{B}</b> pressing their forehead against <b>{A}</b>'s forehead to check if they have a fever.",
	"<b>{B}</b> reminiscing about the time they first met <b>{A}</b>. They're still in awe of how far they've come.",
	'<b>{A}</b> making <b>{B}</b> some hot chocolate.',
	'<b>{B}</b> and <b>{A}</b> having a snowball fight.',
	"<b>{A}</b> and <b>{B}</b> spending their New Year's Eve on a party with their friends and sharing their New Year's kiss in front of everyone.",
	'<b>{B}</b> and <b>{A}</b> walking through town, holding hands while it snows.',
	"<b>{A}</b> and <b>{B}</b> trying to hide their relationship. However, it turns out everyone knows they're dating.",
	"<b>{B}</b> and <b>{A}</b> battling against each other. Whether it's serious or playful is up to you...",
	'<b>{B}</b> and <b>{A}</b> being brought together by their mutual love for a third party, only to slowly develop feelings for each other over time.',
	'<b>{B}</b> showing <b>{A}</b> some of their favorite vines and memes.',
	'<b>{B}</b> has worked up the courage to propose to <b>{A}</b>.  day they go to propose, though, <b>{A}</b> gets on one knee, and holds out a ring.',
	'AU: <b>{A}</b> and <b>{B}</b> meet in university at one of the neighboring restaurants when they both realize they’re skipping the same class.',
	'AU: They are high school students. <b>{B}</b> gets detention. <b>{A}</b>, not wanting to be alone, joins them.',
	'<b>{A}</b> and <b>{B}</b> in high school, staying up all night together to study for a big test the next day.',
	'<b>{A}</b> and <b>{B}</b> going to Build-A-Bear.',
	'<b>{A}</b> and <b>{B}</b> going on social media and finding all of your posts about them.',
	'AU: <b>{B}</b> and <b>{A}</b> met when they moved into the same town in the Animal Crossing universe. (What species each of them are is totally up to you.)',
	'<b>{B}</b> is trying to impress <b>{A}</b> and ends up falling flat on their face. As <b>{B}</b> lays on the ground and slowly die from embarrassment, <b>{A}</b> has a mind blowing realization that they actually really like <b>{B}</b> and when they help <b>{B}</b> up off the ground, they pull them into a kiss.',
	"<b>{A}</b> is chewing the last piece of gum in a really good pack so <b>{B}</b> pulls them into a kiss to lowkey steal it out of <b>{A}</b>'s mouth",
	"<b>{B}</b> and <b>{A}</b> hosting a holiday open-mic night and performing 'Baby It's Cold Outside' together",
	"AU: <b>{A}</b> and <b>{B}</b> are neighbors and they don't necessarily like/notice each other at first, but <b>{B}</b> gets kittens and <b>{A}</b> comes over just to spend some time with them and it charms <b>{B}</b>'s heart.",
	"<b>{B}</b> gets locked out of their house while their family is gone, so they spend the night at <b>{A}</b>'s place.",
	"Before they started dating, <b>{A}</b> and <b>{B}</b> are best friends. Like the best friends that have known each other since they were in diapers. Whenever <b>{A}</b> would get upset, hurt or just really tired, they would snuggle up on <b>{B}</b> and nuzzle their face into the crook of <b>{B}</b>’s neck. It’s completely platonic, nothing romantic about it whatsoever. <br>When <b>{A}</b> and <b>{B}</b> finally confess their feelings for one another and begin dating, <b>{A}</b> immediately snuggles up in 'their' spot on <b>{B}</b> and just completely relaxes. <b>{B}</b> asks why they always do this, and <b>{A}</b> replies that it makes them feel safe and calm.",
	"<b>{A}</b> can't sleep without <b>{B}</b> by their side.",
	'<b>{B}</b> and <b>{A}</b> going on a nice walk in the woods when it suddenly starts to downpour.',
	'<b>{A}</b> and <b>{B}</b> slow dancing with no music, arms wrapped tightly around each other, breath mingling.',
	'<b>{B}</b> and <b>{A}</b> sharing soft kisses, lips barely touching, just chaste little things that leave both parties irrationally breathless.',
	'<b>{B}</b> helping <b>{A}</b> with simple tasks, like brushing their hair, or putting on jewelry, where it’s obviously an excuse to be close to each other, but neither are complaining.',
	'<b>{A}</b> and <b>{B}</b> pressing their faces together sleepily, not even kissing, just resting their foreheads together, noses brushing, breathing each other in.',
	'<b>{B}</b> smiling shyly, cheeks tinging pink, because they were caught staring at <b>{A}</b>.',
	'<b>{A}</b> and <b>{B}</b> playing joyous and silly music to dance around the living room to.',
	"<b>{B}</b> and <b>{A}</b> going out for coffee one morning and <b>{A}</b> already knows <b>{B}</b>'s order by heart.",
	'<b>{B}</b> kissing <b>{A}</b> under the rain without an umbrella after a silly argument, proceeding to giggle it out.',
	"<b>{A}</b> has been planning to propose for a while, they've bought the ring and everything. One day, they somehow lose the ring only for <b>{B}</b> to unexpectedly find it. Bonus: <b>{B}</b> questions a flustered <b>{A}</b> about the ring. Bonus 2: <b>{B}</b> uses the ring to propose instead.",
	"<b>{B}</b> looks at <b>{A}</b> and gently cups their face to examine it. <b>{A}</b> is a little confused and asks what's <b>{B}</b> doing. 'Hold on, there's something on your face,' <b>{B}</b> responds and then kisses <b>{A}</b>. 'It was me.' <br><b>{A}</b> becomes red and flustered.",
	'<b>{B}</b> returning the engagement ring they got for <b>{A}</b> to the jeweller. Not because <b>{A}</b> said no, but because <b>{A}</b> had worked up the courage to propose before <b>{B}</b> did.',
	'<b>{A}</b> and <b>{B}</b> go separately to a New Year’s Party, and end up standing next to each other during the countdown to midnight.',
	'<b>{B}</b>  makes a New Year’s Resolution – but <b>{A}</b> makes it difficult for them to keep it.',
	'<b>{B}</b> gets confetti in their hair. <b>{A}</b> notices.',
	'<b>{A}</b> loves to dance at parties - <b>{B}</b> not so much.',
	"Someone 'accidentally' left the Christmas misteltoe up at a New Year’s Eve party attended by both <b>{B}</b> and <b>{A}</b>.",
	"On New Year's Eve, <b>{A}</b> and <b>{B}</b> reflect on their entire year together.",
	'<b>{B}</b> has never seen <b>{A}</b> in a tuxedo/ball gown before.',
	'<b>{A}</b> makes an unexpected toast in honor of <b>{B}</b>.',
	'<b>{A}</b> and <b>{B}</b> in the morning after a one night stand.',
	"<b>{A}</b> and <b>{B}</b> are in an established long distance relationship, <b>{A}</b> surprises <b>{B}</b> by showing up right before midnight on New Year's Eve.",
	'<b>{A}</b> comes back home to see the mess <b>{B}</b> made in the kitchen trying to cook for them.',
	'<b>{B}</b> heroically saving <b>{A}</b> from a spider by picking it with a glass and throwing it outside.',
	'<b>{A}</b> and <b>{B}</b> hanging out in a garden/field of wildflowers and making flower crowns for each other.',
	'<b>{A}</b> trying their hardest to prank <b>{B}</b>, but they fail each and every single time.',
	'<b>{B}</b> keeps asking weird/strange existential (or otherwise way too deep for 1am) questions and <b>{A}</b> only wants to go to sleeep.',
	'<b>{A}</b> and <b>{B}</b> having water baloon/water gun fight.',
	"<b>{B}</b> finding this prompt generator and putting up their name together with <b>{A}</b>'s name and reacting to the prompts they get.",
	'<b>{A}</b> and <b>{B}</b> singing a duet together.',
	'<b>{A}</b> comes out as trans. <b>{B}</b> does their best to support them.',
	'<b>{B}</b> and <b>{A}</b> tell each other how they miss one another.',
	'<b>{A}</b> and <b>{B}</b> getting married.',
	'<b>{A}</b> and <b>{B}</b> making crafts that remind them of one another.',
	'<b>{B}</b> and <b>{A}</b> started out hating each other but slowly started developing feelings for one another.',
	"<b>{B}</b> wakes <b>{A}</b> at 4 am because they wants someone to eat cereal with. <b>{A}</b> questions why, but <b>{B}</b> surprises them and says 'I just wanted a reason to be with you, is all...'",
	"<b>{A}</b>: It's going to be Christmas soon, <b>{B}</b>. <b>{B}</b>: So what, <b>{A}</b>.",
	'<b>{A}</b>: First of all you just ignored my cats dressed up as Santa, so fuck you. Secondly, <br>[<b>{A}</b> is typing...]',
	'<b>{A}</b> and <b>{B}</b> going star gazing at the observatory.',
	'<b>{B}</b> and <b>{A}</b> staying home and ordering take out bc it’s too hot outside.',
	'<b>{B}</b> and <b>{A}</b> staying in a small town and exploring the little shops and cute restaurants.',
	'<b>{A}</b> and <b>{B}</b> camping beside a lake and going swimming as the sun sets.',
	'<b>{B}</b> and <b>{A}</b> roasting marshmallows on a fire.',
	'<b>{A}</b> and <b>{B}</b> cuddling under the stars.',
	"<b>{B}</b>:*Kisses <b>{A}</b>'s forehead*<br><b>{A}</b>:*frowns* You missed<br><b>{B}</b>:...?<br><b>{A}</b>:*Leans forward and kisses <b>{B}</b>'s lips*",
	'<b>{B}</b>: I always knew it would end like this.',
	'<b>{B}</b>: I don’t want to be alone right now.',
	'<b>{B}</b>: I’ve got you now.',
	"<b>{B}</b>: I love you <br> <b>{A}</b>: *shoving laundry basket into <b>{B}</b>'s hands* stop saying I love you to get out of chores",
	'<b>{A}</b> and <b>{B}</b> going camping',
	'<b>{B}</b> and <b>{A}</b> on a shopping date',
	'<b>{A}</b>: Don’t worry, I’ve been arrested before. I’ll get us out of this.',
	'<b>{A}</b>: I love you. <br> <b>{B}</b>: Pathetic.',
	'<b>{B}</b>: I know that I hurt you. I know that nothing I can say will change the past. But…I’m hoping that you’ll forgive me in the end. I’m hoping that I can make this right.',
	'<b>{B}</b>: Do you hate me or something? <br><b>{A}</b>: Not at all. I’m actually quite in love with you, really.',
	'<b>{A}</b> and <b>{B}</b> are pretending to be married because they want a discount on a vacation special to an expensive resort. What happens? Do they get found out?',
	'<b>{A}</b> and <b>{B}</b> go to school together. <b>{A}</b> got <b>{B}</b> a huge ass teddy bear for a special occassion and <b>{B}</b> is mad cause they have to carry it around all day.',
	'<b>{A}</b> and <b>{B}</b> decide to do a partner costume! Who or what would they dress up as?',
	'<b>{B}</b> and <b>{A}</b> getting matching tattoos',
	'<b>{A}</b> and <b>{B}</b> falling asleep under the stars together... Only to wake up covered in bug bites.',
	'<b>{B}</b> and <b>{A}</b> sleeping together for the first time.  No sex, just sleeping.  When <b>{B}</b> wakes up, they see <b>{A}</b> still asleep. <b>{B}</b> smiles and wakes them up with a sweet kiss. <b>{A}</b>, once aware of what’s happening, kisses back.',
	'<b>{A}</b> and <b>{B}</b> are lost in the woods together.',
	"Imagine the big, bright smile on <b>{B}</b>'s face when <b>{A}</b> finally says ‘I love you’ for the first time.",
	"<b>{A}</b> runs across the road to pet <b>{B}</b>'s pet.",
	'<b>{B}</b> is playing a video game even though they’re really tired. They end up falling asleep during the game. <b>{A}</b> walks up and sees <b>{B}</b> sleeping peacefully, and falling out of their hands, a controller/handheld. Instead of waking up <b>{B}</b> or turning off the game, <b>{A}</b> picks up the controller/handheld and begins to play.',
	'<b>{A}</b> gets addicted to painting nails and forces <b>{B}</b> to let their nails get painted on.',
	'<b>{B}</b> and <b>{A}</b> have to work with each other on a psychology project. A psychology project on attraction.',
	"Imagine <b>{A}</b> wants to spice up their and <b>{B}</b>'s romance life and tries all sorts of cheesy tactics such as candlelit dinners, bringing fruit and whipped cream into the bedroom, sexy underwear... whether they fail or not in their romancing is another question...",
	"<b>{A}</b> and <b>{B}</b> getting dressed in the morning, <b>{B}</b> however is feeling a bit playful and decides to hold a piece of <b>{A}</b>'s clothing hostage so <b>{A}</b> has to try and get it back",
	'<b>{B}</b> and <b>{A}</b> as friends in school before they’re together. They awkwardly use each other to learn how to/practice kissing and end up making out passionately until their mouths are sore.',
	"<b>{A}</b> dressed up as a sexy cop for Halloween and <b>{B}</b> keeps surrendering to <b>{A}</b> by saying 'I've been very bad, you should arrest me.'",
	"<b>{A}</b>: You  don’t  have  to  hide  your  tears  from  me, <b>{B}</b>. It's okay.",
	'<b>{B}</b> waking <b>{A}</b> up with gentle kisses.',
	'<b>{A}</b> spontaneously kissing <b>{B}</b>.',
	'<b>{B}</b> holding <b>{A}</b> close.',
	'<b>{B}</b> gesturing at <b>{A}</b> to come closer.',
	"<b>{A}</b> grabbing <b>{B}</b>'s arm or hiding behind <b>{B}</b> because something scared them.",
	'<b>{A}</b> touching <b>{B}</b> as a show of affection/reassurance.',
	"<b>{B}</b> showing up at <b>{A}</b>'s house without explanation.",
	"<b>{A}</b> treating <b>{B}</b>'s injury.",
	'<b>{B}</b> getting hurt protecting <b>{A}</b>.',
	'<b>{B}</b> tickling <b>{A}</b>.',
	"<b>{A}</b> massaging <b>{B}</b>'s shoulders.",
	"<b>{B}</b> kissing <b>{A}</b>'s neck.",
	'<b>{B}</b> and <b>{A}</b> sharing a bath.',
	'<b>{A}</b> and <b>{B}</b> in the shower together, purely enjoying the company of each other.',
	"<b>{B}</b> putting flowers in <b>{A}</b>'s hair.",
	'<b>{A}</b>: You look tense, lie down and I’ll give you a massage.',
	'<b>{A}</b>: Your nose gets so pink during winter...I have to kiss it.',
	'<b>{B}</b>: Sorry, I didn’t know you were awake, you just looked so cute and I wanted to kiss you.',
	'<b>{B}</b>: I like tracing the lines in your palm, it’s...distracting.',
	'<b>{B}</b>: It’s just so easy to pick you up!',
	'<b>{A}</b>: Do you want to join me in my blanket fort?',
	'<b>{B}</b>: ...so that’s where all the pillows went. Mind if I lay with you?',
	'<b>{A}</b>: Your skin is so soft...',
	'<b>{A}</b>: My shirt is way too big on you...but it’s cute.',
	'<b>{A}</b>: I don’t know how we keep ending up in each other’s beds...',
	'<b>{A}</b>: You know, I really like your eyes, <b>{B}</b>.',
	'<b>{A}</b> and <b>{B}</b> going for an incredibly late night walk.',
	"<b>{B}</b> puts <b>{A}</b>'s favorite movie on for a movie night.",
	'<b>{A}</b> offers <b>{B}</b> their favorite snack/drink/etc.',
	'<b>{B}</b> gently drapes a blanket over <b>{A}</b> and kisses their forehead while they’re half-asleep.',
	'<b>{A}</b> runs <b>{B}</b> a relaxing bath after a long and difficult day.',
	'<b>{B}</b> is experiencing a moment of great joy – only for <b>{A}</b> to suddenly arrive with devastating news.',
	'<b>{B}</b> has become bitter and, well, rather prickly, and <b>{A}</b> is trying to find out why they are acting so out-of-character so suddenly.',
	'<b>{B}</b> is suffering in the summer heat, and <b>{A}</b> is left desperately trying to cool them down.',
	'<b>{A}</b> has to face their worst fear, and <b>{B}</b> must help them through the experience.',
	'<b>{A}</b> is feeling terrible self-doubt, and <b>{B}</b> must try to encourage them.',
	"<b>{A}</b> brushes something off of <b>{B}</b>'s face (eyelash, food crumb, etc.)",
	'<b>{B}</b> shares a drink or a snack with <b>{A}</b>.',
	'<b>{A}</b> helps <b>{B}</b> shave.',
	'<b>{A}</b> applying make up on <b>{B}</b>.',
	'<b>{B}</b> helping <b>{A}</b> wash up (whether it be their hair, body, some blood off their hands, etc.)',
	'<b>{B}</b> giving <b>{A}</b> a smile after making eye contact.',
	'<b>{A}</b> offering <b>{B}</b> a hand to help them with a step.',
	"<b>{B}</b> brushes a thumb over <b>{A}</b>'s cheek.",
	'<b>{A}</b> and <b>{B}</b> slow dance together.',
	'<b>{B}</b> offers <b>{A}</b> a place to stay.',
	'<b>{A}</b> gently kisses <b>{B}</b> on the nose.',
	'<b>{B}</b> gets a call from <b>{A}</b> in the middle of the night.',
	'<b>{B}</b> and <b>{A}</b> celebrate something together.',
	'<b>{B}</b> interlaces their fingers with <b>{A}</b>.',
	'<b>{A}</b> picks a flower for <b>{B}</b>.',
	'<b>{B}</b> makes <b>{A}</b> a hot beverage on a cold day.',
	'<b>{A}</b> is feeling out of it and need constant attention from <b>{B}</b>.',
	"<b>{B}</b> collapsing into <b>{A}</b>'s waiting arms.",
	'<b>{A}</b> picking <b>{B}</b> up.',
	'<b>{A}</b> calling <b>{B}</b> soft things like baby, sweetheart or honey.',
	'<b>{A}</b> waking up in the middle of the night to find <b>{B}</b> still working. <b>{A}</b> has to drag <b>{B}</b> back to bed.',
	"<b>{B}</b> waking up in the middle of the night to find that <b>{A}</b> isn't in their bed.",
	"<b>{B}</b> mumbling <b>{A}</b>'s name and reaching out for them.",
	"<b>{A}</b> has a fever. <b>{B}</b> takes care of them and lovingly runs their fingers through <b>{A}</b>'s sweaty hair.",
	'<b>{A}</b> says something to <b>{B}</b> that strikes a nerve.',
	'<b>{A}</b> witnesses <b>{B}</b> having a panic attack, flashback, or hallucination.',
	'<b>{B}</b> accidentally discovers a secret about <b>{A}</b>.',
	'<b>{A}</b> and <b>{B}</b> have a good, hard cry together.',
	'<b>{A}</b> comes home to find <b>{B}</b> snooping through their things.',
	'<b>{A}</b> tries convincing <b>{B}</b> to run away with them to an undisclosed location.',
	'<b>{A}</b>: There isn’t a word in the dictionary that can explain your type of beauty.',
	'<b>{B}</b>: Can you send me a picture? I want to prove to all of my friends that angels really do exist.',
	'<b>{B}</b>: Of all the stars in the sky, there are none as beautiful as you.',
	'<b>{A}</b>: To be honest, I just wanted a chance to look at the stars with you.',
	'<b>{B}</b>: I’m a child of God, I don’t do that shit.',
	'<b>{A}</b> is a great cook, but <b>{B}</b> rarely cooks. To surprise them, <b>{B}</b> tries to make them something. Emphasis on tries.',
	'<b>{B}</b> teaching <b>{A}</b> how to cook.',
	"It's <b>{B}</b>'s birthday and they have a nice, lazy, sleepy lie-in. <b>{A}</b> decides to cook <b>{B}</b> breakfast in bed and cooks all of <b>{B}</b>'s favourite food. <b>{B}</b> is delighted and showers <b>{A}</b> with kisses.",
	'<b>{A}</b> and <b>{B}</b> deciding to watch a movie together. They decide to cook up some popcorn to share, but end up arguing over how their popcorn should be prepared. <b>{B}</b> likes unsalted, buttered popcorn, but <b>{A}</b> likes theirs salty and butter-free. They spend more time arguing over how to eat their popcorn than they do watching their movie (or even deciding on a movie). Is there any hope they can solve their situation?',
	'<b>{A}</b> is the cook of the family. <b>{B}</b> can not cook but wants to give <b>{A}</b> a break. Whether or not they succeed is up to you.',
	'<b>{B}</b> and <b>{A}</b> talking about their feelings in a healthy and positive space, without judgement, learning more about each other and deepening the bonds of trust that bind them together.',
	"<b>{A}</b> and <b>{B}</b> are married, and offer to babysit their friends' kid, not realizing how much of a challenge it would be.",
	'<b>{A}</b> and <b>{B}</b> decorating a Christmas tree together.',
	'<b>{A}</b> and <b>{B}</b> attending a pride parade.',
	"<b>{B}</b> asleep and accidentally moaning <b>{A}</b>'s name while they're still awake beside <b>{B}</b>.",
	'<b>{B}</b> and <b>{A}</b> playing games in the small arcade in their neighborhood.',
	"<b>{A}</b> and <b>{B}</b> getting a little too drunk at a New Year's Eve party.",
	"<b>{A}</b> running their fingers through <b>{B}</b>'s hair while sitting next to them on the couch.",
	'<b>{A}</b> letting <b>{B}</b> warm their cold hands under their shirt.',
	'<b>{B}</b> and <b>{A}</b> play Twister. Do things get embarrassing? Do things get steamy?',
	'<b>{A}</b> and <b>{B}</b> at a late-night gathering after everyone else has gone home, dancing in the moonlight.',
	"<b>{A}</b> and <b>{B}</b> spending the night together. <b>{A}</b> wakes up first in the morning and contemplates waking <b>{B}</b> with a kiss.<b>{A}</b> leans in only to hesitate centimeters away out of embarrassment. <b>{B}</b> opens their eyes and says, 'Well if you won't do it, I will.'",
	'<b>{B}</b> burns their lip on something hot, <b>{A}</b> kisses it better.',
	'<b>{B}</b> and <b>{A}</b> accidentally dozing off in a hammock together as the sun sets and the air cools down.',
	'<b>{A}</b> and <b>{B}</b> making out so vigorously and passionately that when they’re eventually done, it looks as though they had both just stepped out of the shower.',
  '<b>{A}</b> is up late at night, trying to figure something out or studying, when <b>{B}</b> comes up from behind them with a cup of tea, kisses them on the head, and wishes them good night.',
  "<b>{A}</b> really wants to give <b>{B}</b> a special gift for their anniversary and secretly learn how to draw/play an instrument/write poetry so they can draw/play/write something specifically for <b>{B}</b>",
  "<b>{A}</b> just got <b>{B}</b> out of a dangerous situation and is now treating their wounds at a small house.",
  "<b>{B}</b> wearing <b>{A}</b>’s shirt, curled up in <b>{A}</b>'s lap, their face in the crook of <b>{A}</b>’s neck, while <b>{A}</b> absentmindedly plays with <b>{B}</b>’s hair while reading something/scrolling on their phone.",
  "<b>{A}</b> listening to <b>{B}</b> ramble on about their dreams to open a restaurant/bakery, and <b>{A}</b> already planning out how to make that happen.",
  "<b>{A}</b> and <b>{B}</b> playing in the garden/flower field and making flower crowns on each other. ",
  "Imagine <b>{A}</b> buying some mistletoe, hanging it up in their house, and then trying with increasingly less subtlety as time goes on to get <b>{B}</b> underneath it so they can steal a kiss, while <b>{B}</b> remains blissfully oblivious, and somehow manages to miss all of <b>{A}</b>’s hints.",
  "<b>{A}</b> and <b>{B}</b> are on a date in the park, but it quickly sours when it starts raining. When they get to the bus stop, they remember the bus workers have been striking for better pay. <b>{A}</b> is crestfallen, but <b>{B}</b> invites <b>{A}</b> to walk home dancing in the rain with them.",
  "<b>{A}</b> is in a bad mood and is mumbling a list of things they don’t like about themself under their breath. <b>{B}</b> notices and chimes in with a way longer list of things they like/love about <b>{A}</b>.",
  "<b>{A}</b> and <b>{B}</b> both call in sick to work so they can spend the day at the zoo together.",
  "<b>{B}</b> isn't a very affectionate person, while <b>{A}</b> cherishes every moment they get with <b>{B}</b>. One day while <b>{A}</b> is cooking breakfast, <b>{B}</b> comes up and surprises <b>{A}</b> with a hug from behind. (Bonus + <b>{A}</b> buries their head into the back of <b>{A}</b>'s shirt.)",
  "One day, <b>{A}</b> receives an envelope, the labeling on which indicates that it contains highly-sensitive information for their eyes only. <b>{A}</b> opens the envelope, and inside is a short, affectionate, handwritten love letter from <b>{B}</b>.",
  "<b>{A}</b> and <b>{B}</b> falling in love and getting married and having kids and growing old together and nothing bad ever happens becauSE SCREW ALL THOSE PROMPTS WHERE THEY DO.",
  "<b>{A}</b> is waking up in the middle of the night, shaking, breathing heavily, maybe even crying. <b>{B}</b> wakes up as well, immediately knows what is happening and starts cuddling <b>{A}</b>.",
  "<b>{A}</b> and <b>{B}</b> driving in heavy rain. It’s getting hard to see anything, so they pull over and find a covered picnic area to wait out the storm. They talk until it’s safe to drive again, and find out loads of new things about each other.",
  "<b>{A}</b> sitting cross-legged on the couch with a pile of bows and hair ties in their lap, messing with <b>{B}</b>’s hair, while <b>{B}</b> is sitting on the floor, laughing at <b>{A}</b>’s antics.",
  "After a long day, <b>{A}</b> sleepily crawls into bed with <b>{B}</b>, who is absorbed in a book. <b>{A}</b> lays their head on <b>{B}</b>’s shoulder, and occasionally reads a page of <b>{B}</b>’s book while lapsing into a deep sleep. Once <b>{B}</b> finds out <b>{A}</b> is asleep, they gently lay <b>{A}</b> down, cover them, and turn out the light. ",
  "<b>{A}</b> finding <b>{B}</b>’s hobby which is quite unusual for their personality and decides to dabble in it too, finding they like it too and it’s something they do together.",
  "<b>{A}</b> takes <b>{B}</b> to the countryside at night, and they spend the night in a tent with a clear top so they can cuddle and stargaze.",
  "<b>{A}</b> pulling in <b>{B}</b> by their necktie and giving them a long, passionate kiss.",
  "<b>{A}</b> works at a small airport, in an even smaller store, where they sell miscellaneous snacks and items. <b>{B}</b> is a security guard who often visits the shop near the end of their shift to see <b>{A}</b>.",
  "<b>{A}</b> is the intimidating, scarier half. Their group of friends seem them wearing an adorable, soft, pastel pink sweater and laugh at them.  Until <b>{A}</b> jumps on <b>{B}</b>'s back, grinning and kissing <b>{A}</b>'s cheek because <b>{B}</b> took forever to make that sweater.",
  "<b>{A}</b> has a fry in their mouth and dares <b>{B}</b> to steal it from them. <b>{B}</b> moves in, <b>{A}</b> psychs them out by pulling the fry in a little. <b>{B}</b> tries again and <b>{A}</b> puts the whole fry in their mouth, making <b>{B}</b> kiss them.",
  "<b>{A}</b> wears glasses. <b>{B}</b> goes to kiss their forehead, and when they pull away, <b>{A}</b>'s glasses are all fogged up, and <b>{A}</b> starts saying things like “Well great now I have to clean my glasses/thanks, thanks a lot!/dammit, my glasses!” <b>{B}</b> just giggles.",
  "<b>{A}</b> and <b>{B}</b> going on the Haunted Mansion/a haunted house. <b>{A}</b> isn’t scared, but they pretend to be so they can cling to <b>{B}</b>’s arms.",
  "<b>{A}</b> is a superhero and has a massive crush on <b>{B}</b> while <b>{B}</b> is infatuated by <b>{A}</b>’s superhero alter ego. (Not knowing it’s <b>{A}</b>.)",
  "<b>{A}</b> and <b>{B}</b> are friends and they secretly have feelings for one another. One day, <b>{B}</b> gets into a difficult fight in which they win but are left injured and unconscious and are later found by <b>{A}</b>. <b>{A}</b> immediately starts taking care of them and confesses how they feel at the same time as <b>{B}</b> They have a very shy first kiss after that.",
  "<b>{A}</b> has scars on their back/shoulders (can be self harm, battle scars, etc.). One day <b>{A}</b> has their back exposed, and <b>{B}</b> hugs them from behind, kissing down <b>{A}</b>'s back. When <b>{A}</b> asks what <b>{B}</b> is doing, <b>{B}</b> replies “no one has ever kissed them better before, so I’m doing it now.”  ",
  "Imagine <b>{A}</b> is sick.  When they’re sleeping, <b>{B}</b> wraps them up in a blanket burrito.",
  "<b>{A}</b> is a talented pianist who meets <b>{B}</b> and offers to teach them how to play, unaware that <b>{B}</b> is already an equally talented pianist themselves. <b>{B}</b> accepts so they have an excuse to spend time with <b>{A}</b> but gets discovered one day when <b>{A}</b> walks in on <b>{B}</b> practicing some high-level music.",
  "Imagine <b>{A}</b> returning the engagement ring they got for <b>{B}</b> to the jeweller. Not because [name] said no, but because <b>{B}</b> had worked up the courage to propose before <b>{A}</b> did.",
  "Imagine <b>{A}</b> and <b>{B}</b> getting married (or getting engaged) and, after being together for a long time, sticking to their decision to not have children (neither biological nor adopted). But they are still happy because they know that they do not need to raise a family in order to be in a happy and healthy relationship.",
  "<b>{A}</b> has gone through some form of major trauma and abuse while <b>{B}</b> wasn’t able to help. Months after <b>{A}</b> is safe again, they continue to have nightmares and flashbacks to the event and find it hard to trust people anymore. <b>{B}</b> is heartbroken but slowly helps <b>{A}</b> learn to love again and be themself. ",
  "<b>{A}</b> thinks that <b>{B}</b> has forgotten their anniversary, but <b>{B}</b> is planning something special in secret.",
  "<b>{A}</b> complaining about how they’ve never had a New Year’s kiss before so <b>{B}</b> surprises them with a kiss when the clock strikes midnight.",
  "<b>{A}</b>  and <b>{B}</b> sitting outside together late at night and as the temperature begins to drop they snuggle up together.",
  "<b>{A}</b> and <b>{B}</b> go to a field of flowers to take photos but end up laying in the field together and picking beautiful flowers for each other. ",
  "While <b>{B}</b> is out of the house, <b>{A}</b> puts up glow-in-the-dark stars on <b>{B}</b>’s ceiling along with two lamps (one that looks like the moon and one that looks like the Sun.) To top it off <b>{A}</b> leaves a note saying “You are my moon, my sun, and all of the stars. So I did this to make sure you always know.”",
  "<b>{A}</b> is always cold even in the summer time so <b>{B}</b> is very protective of <b>{A}</b> when they’re outside and always has water and lighter clothing for <b>{A}</b>  in case they get overheated.",
  "<b>{A}</b> writing <b>{B}</b>'s name in a heart/under the love umbrella/etc. in their notebook together with their own name. ",
  "<b>{A}</b> and <b>{B}</b> are neighbors. <b>{A}</b> doesn’t like cooking so they prefer buying instant food, etc. Whereas, <b>{B}</b> always cooks healthy homemade food. <b>{B}</b> notices <b>{A}</b>'s pure laziness so <b>{B}</b> decides to cook for <b>{A}</b> whenever they can and constantly remind them to take care of their health. And <b>{A}</b> genuinely appreciates <b>{B}</b> because no one has ever done anything like this for them. One night, <b>{A}</b> decides to try cooking for once so they go to the grocery store to buy some ingredients. Coincidentally <b>{B}</b> is there also. <b>{A}</b> expects <b>{B}</b> to buy veggies or any other healthy stuff but instead, a big amount of junk food filled up <b>{B}</b>'s basket. They also notice <b>{B}</b>'s bitter and apathetic expression, which is very unlikely of them. <b>{A}</b> starts to get worried so they take <b>{B}</b> home and cook dinner for them. Then, <b>{A}</b> tries to comfort <b>{B}</b> and wait for them to speak up.",
  "<b>{A}</b> and <b>{B}</b> in a Skype/Discord call (webcam optional) when <b>{A}</b> falls asleep in the middle of it. <b>{B}</b> decides to let them sleep since <b>{A}</b> had a long day and they like the sound of their sleeping. ",
  "<b>{B}</b> living on a farm and their parents hire <b>{A}</b> as a farmhand. <b>{B}</b> attempts to show <b>{A}</b> how everything works and every time <b>{A}</b> messes up, <b>{B}</b> laughs hysterically.    ",
  "Every year for <b>{A}</b>’s birthday, <b>{B}</b> goes above and beyond in terms of gifts, planning a birthday party and just generally making sure <b>{A}</b> has the best day ever. This year, <b>{A}</b> decides to return the favour by planning a whole day for <b>{B}</b>. It doesn’t go exactly as <b>{A}</b> planned but they include lots of things that they know <b>{B}</b> likes and tries hard to make the day amazing. <b>{B}</b> doesn’t care that it doesn’t go perfectly, they just revel in how much they love <b>{A}</b>.",
  "<b>{A}</b> is involved in some sort of accident. <b>{B}</b> finds out and rushes to the scene, calling <b>{A}</b> frantically. <b>{A}</b> doesn’t pickup, so <b>{B}</b> leaves <b>{A}</b> a series of voicemails as they race to the scene of <b>{A}</b>’s accident.",
  "<b>{A}</b> didn’t realized that the orchard was going to be closed when they invited <b>{B}</b> on an apple-picking date. <b>{B}</b>, however, doesn’t really mind; they think it’ll be more fun without anyone else around and the added danger of breaking-and-entering.",
  "<b>{B}</b> helping <b>{A}</b> with simple tasks, like brushing their hair, or putting on jewelry, where it’s obviously an excuse to be close to each other, but neither are complaining.",
  "<b>{A}</b> wakes up after a late night out to find that <b>{B}</b>, who doesn’t drink, has made them a feast of hangover foods.",
  "<b>{B}</b> tells <b>{A}</b> all the time to stop exerting themself, and <b>{A}</b> responds with “you can’t do all the work every day! I need to be helpful too!” and continues what they’re doing. ",
  "<b>{A}</b> finds one of those foam noodle things you play with in the pool while shopping with their partner, and <b>{A}</b> challenges <b>{B}</b> to a noodle duel.",
  "<b>{A}</b> and <b>{B}</b> have to cancel date plans because of a heavy rain and they stay at <b>{A}</b>'s home watching god-awful films and laughing their socks off.",
  "<b>{B}</b> is an immortal being of some kind and <b>{A}</b> is a mortal. <b>{A}</b> wants to become immortal and be with <b>{B}</b> forever, but <b>{B}</b> wants to relinquish their mortality and live a normal life with <b>{A}</b>.",
  "<b>{A}</b> sleeping on a chair with their head on a table. <b>{B}</b> then sees and covers them with a warm blanket and a kiss.",
  "<b>{A}</b> loves hearing bedtime stories, so <b>{B}</b> has developed the habit of reading them to <b>{A}</b>.",
  `<b>{A}</b>: So <b>{B}</b>, what'd you want for your birthday?<br><b>{B}</b>, pulling out an extremely long paper labeled "Things I'd do to <b>{A}</b>": Let's see here...`,
  "[name3] being proud of the fact that they were the first one to find out that <b>{A}</b> and <b>{B}</b> like each other.",
  "<b>{B}</b> gets into an argument with <b>{A}</b>, and <b>{B}</b> gets a grudge over it. When they're on bed, they both lie on opposite sides. <b>{A}</b> remembers saying 'I love you' and 'good night' before they sleep, so they say it, making <b>{B}</b> feel bad. <b>{B}</b> cuddles up to them, saying sorry before repeating their words back with a loving smile.",
  "<I>slight nsfw~</I><br><br><b>{A}</b>: What was the biggest mistake you made in your life?<br><b>{B}</b>, sweating: I got curious and checked out your photos...<br><b>{A}</b>, smiling awkwardly: So uh, did you see my nudes?<br><b>{B}</b>: No- WAIT, WHAT?",
  "<b>{A}</b> and <b>{B}</b> like to float lanterns and lie down, looking at the stars in the woods on new years. ",
  "<b>{B}</b> likes pinching <b>{A}</b>'s cheeks.",
  "<b>{A}</b> makes a funny face and <b>{B}</b> reacts by laughing lightheartedly and patting <b>{A}</b>.",
  "<b>{A}</b>: Life is so terrible.<br><b>{B}</b>: You may think of it as terrible, <b>{A}</b>, but sadness like this is temporary and things will soon get better. We both know that no life goes on without having a fair share of struggles and hardships. Simply feeling sad will pass eventually and you will be happy.<br><b>{A}</b>, shocked and confused: This is not the <b>{B}</b> I know, what are you on<br><b>{B}</b>: The will to live.",
  "<b>{A}</b> wearing <b>{B}</b>'s clothes. Their clothes are too big for them though, but <b>{B}</b> insists seeing <b>{A}</b> wear that for the rest of the day because they thought they looked cute.",
  "<b>{B}</b>: You're a really cute bean, <b>{A}</b>.",
  "<b>{A}</b> has a bunch of cute figurines/plushies they treat like it's their child. <b>{B}</b> absolutely loves the act.",
  "<b>{B}</b> giving <b>{A}</b> a surprise gift on a random day because <b>{B}</b> felt like it.",
  "<b>{A}</b> screaming and holding on to <b>{B}</b> as they kill something <b>{A}</b> is scared of (a spider, a cockroach, whatever it can be.).",
  "<b>{A}</b> and <b>{B}</b> running around and unintentionally destroying things all while playing tag and giggling.",
  "<b>{A}</b>: Just look at <b>{B}</b>. They're so cute and adorable~ <br>[name3], seeing <b>{B}</b> throwing a chair: Mhm...",
  "<b>{B}</b>, with a deadpan stare: <b>{A}</b>, this popsicle tastes... weird. What'd you put in this? <br><b>{A}</b>, happily: Well there weren't much options, so I used cyanide. <br><b>{B}</b>, still with a deadpan:I see, I've always wondered what it tasted like— *dies*",
  "<b>{B}</b> taking care of <b>{A}</b> when they're not feeling well.",
  "<b>{A}</b>, crying: You're... you're... you're taller than me! <br><b>{B}</b>:<br><b>{B}</b>: And you realized it just now?",
  "<b>{B}</b>: What are you listening to? <br><b>{A}</b>: Love songs. <br><b>{B}</b>, in a teasing manner: Oh really? You're in love? In love with who, may I ask?<br>[name3]: Why are you asking? All of us know who <b>{A}</b> likes.<br><b>{B}</b>, panicking: WHO?!<br><b>{A}</b>:<br>[name3]:<br>[name3]: This is why you're still single.",
  "[name3], stuck in a hole: Help :(<br><b>{A}</b> and <b>{B}</b>: How'd you even get there-",
  '<b>{B}</b>: <b>{A}</b>, will you marry me? <br><b>{A}</b>, unable to decide between "of course I do" and "YES, YESSSSSS!":<br><b>{A}</b>: Of yes course.<br>*silence*<br><b>{B}</b>: Huh?',
  "<b>{B}</b> and <b>{A}</b>: *are about to kiss*<br>[name3], kicking down the door: WHAT'S UP, IDIOTS- OH. OH MY GOD. OH MY GODDDD.<br>*[name3] shuts the door close*",
  "<b>{B}</b> reaching out both arms for <b>{A}</b> to cuddle in a cold, snowy night.",
  "<b>{A}</b>, <b>{B}</b> and [name3] just enjoying a cup of coffee in their favorite cafe.",
  "<b>{A}</b>, on top of a chair: *screaming*<br><b>{B}</b>: <b>{A}</b>?! What's wrong?!<br><b>{A}</b>, pointing at a spider on the floor: Spider!<br><b>{B}</b>:<br><b>{B}</b>: *starts screaming loudly as well*",
  "<b>{B}</b> has a bit of a problem with their emotions. Fortunately though, they have <b>{A}</b> to approach whenever they feel down.",
  "[name3] finding <b>{B}</b> and <b>{A}</b> sitting on the floor sleeping, <b>{A}</b> leaning on <b>{B}</b>'s body, both smiling and blushing.",
  "<b>{A}</b> and <b>{B}</b>, on a mountain at a rainy night, smiling and telling each other warm-hearted compliments and sweet nothings as they view the ocean beneath.",
  "<b>{B}</b> watching <b>{A}</b> follow and feed a duck with bread. Ducks are not common in where <b>{A}</b> was from, so <b>{A}</b> was new to this and keeps on talking to <b>{B}</b> about how cute ducks are.",
  "<b>{B}</b> teasing <b>{A}</b> about how cute they are when they're mad. <b>{A}</b> had just gotten mad at <b>{B}</b> for eating their chips/snacks.",
  "<b>{B}</b>,crossing their arms: You know, I'm quite the bad guy type.<br>[name3], putting a hand on their chin: Oh really? You don't seem to act that way around <b>{A}</b>.<br><b>{B}</b>: Shut it [name3], I act that way to everyone. <b>{A}</b> isn't an exception!<br><b>{A}</b>, entering the room: Good morning-<br><b>{B}</b>, immediately smiling sweetly and waving cutely at <b>{A}</b>: Good morning sweetheart <3",
  `<b>{A}</b> giving <b>{B}</b> a bouquet of flowers with a small paper that said "I'm still not getting over the fact that you stole a dollar from me <3"`,
  "[name3]: What am I made of? <br><b>{B}</b>: Atoms and flesh. <br><b>{A}</b>: [name3].<br><b>{B}</b>: Friend material.",
  "<b>{B}</b> always invites their friends over every week. Their house has a cookie jar in the kitchen, but it is always empty after their friends visit. It became more obvious that <b>{A}</b> was the one eating everything, so <b>{B}</b> surprises <b>{A}</b> with an extra jar of cookies the next time they came over.",
  "<b>{A}</b>, grumpy: You need to stop patting my head, <b>{B}</b>, my hair is now all messy.<br><b>{B}</b>, still patting <b>{A}</b>'s head: Don't worry. I know how hard it is for you to admit how much you like it.",
  "<b>{B}</b> gets a little tired of overplayed Christmas/Valentines songs, so <b>{A}</b> always writes songs just for <b>{B}</b>.",
  "<b>{B}</b>, in a dramatic tone: I'd die for you, <b>{A}</b>.<br><b>{B}</b>, pausing the dramatic act: I still hope someone doesn't kill me though.<br>[name3], eating popcorn in the back: I think I know what I'm gonna do today.<br><b>{B}</b>, tilting their head a full 180: If you're gonna do anything I'll murder you first.",
  "<b>{B}</b>, talking to [name3]: <b>{A}</b> won't stop grabbing my chocolate, so I hid the real stuff in my room and put chili on the ones in the kitchen.<br>[name3], glancing at the kitchen: B-but <b>{A}</b>'s eating them...<br><b>{B}</b>: I'm sure they'll feel the spiciness soon.<br><b>{A}</b>, noticing <b>{B}</b> and [name3] peeking: Oh hey guys. The chocolate here was a little hot.",
  "<b>{B}</b> accidentally spills a drink on <b>{A}</b>'s favorite shirt/clothing, but <b>{A}</b> forgives them.",
  "<I>slight nsfw~</I><br><br><b>{A}</b> and <b>{B}</b> playing seductive music in their room late at night, keeping [name3] wide awake in the room next to them, wondering: what are they doing there, huh?",
  "<b>{A}</b>, dreamily: You know, I've always wanted to crush Oreos and mix it with matcha ice cream, then top it on rice.<br><b>{B}</b>: ...You had me hooked until you mentioned rice.<br>[name3], looking a little disappointed: You sure are imaginative, aren't you...",
  "<b>{B}</b>: In your opinion, which tastes better: cheesecake or brownies?<br><b>{A}</b>: You.<br><b>{B}</b>: <b>{A}</b>, we're planning for our anniversary.<br><b>{A}</b>, crossing their arms: That doesn't change what I want.<br><b>{B}</b>, now blushing profusely: Fair enough.",
  `<b>{B}</b> gets a little too drunk and starts flirting with <b>{A}</b>. <b>{B}</b> asks if <b>{A}</b> was single, which they replied with, "Only for you, honey."`,
  "<b>{B}</b>: Now now, <b>{A}</b>, let's keep things low-key. I don't want anyone else to find out we're dating.<br><b>{A}</b>: I'm gonna spam heart emojis on our messages and everyone will find out.<br><b>{B}</b>: Not what I wanted, but this chaotic energy you're throwing everywhere is the reason I love you.",
  `<b>{B}</b>, lazily sitting on a chair: I'm hungry.<br><b>{A}</b>, giggling mischievously: Hi hungry. I'm too lazy to make you food though.<br><b>{B}</b>: "Too lazy to make you food though" is a terrible name.`,
];

export default prompts;
