const prompts = [
	'Them resting together and talking to each other before falling asleep.',
	'Forehead touching. Forehead kisses.',
	"Them exploring each others' bodies, but not in a sexual way. Finding their different birthmarks, looking over each others' scars and sharing the stories behind them, running their hands over one another and just appreciating the feeling of the other person next to them.",
	'{A} and {B} go to a fair/amusement park and {A} wants to go on the roller coaster and {B} agrees. Later, {B} regrets their decision and ends up clinging onto {A} for dear life.',
	'They are on a ferris wheel, and everything is going great - until it gets stuck at the very top. For thirty whole minutes.',
	"{B} won't let {A} get out of bed by cuddling them. ",
	"{A} is about to leave for work. {B} asks them if they've forgotten anything, and {A} gives them a kiss. {B} turns red and opens their hand to reveal {A}'s keys/wallet/etc., saying 'I meant this, but thanks.'",
	'{A} buys a box of sweets and puts them in the cupboard. {B} spontaneously eats them all in the middle of the night and tries to keep it a secret.',
	"{A}: Is it hot in here or is it just me? <br> {B}: It's you. <br> {A}: What? <br> {B}: What?",
	"Them playing with sidewalk chalk like they're kids again.",
	'Them accidentally (or purposefully) dozing off in a hammock together as the sun sets and the air cools down.',
	'Them huddled by the fireplace at night after making snow angels in the fresh snow.',
	'Their first holiday season together.',
	'{B} wants to use their laptop on the couch, but {A} always occupies the space in their lap.',
	"{A} doesn't like talking on the phone, but {B} always calls them instead of texting. {B} admits that it's because they want to hear {A}'s voice.",
	'{A} wakes to find that it had snowed overnight and gets excited about playing in it. {B} gets excited because this means that when {B} comes inside, it will be time for cuddling by the fire.',
	"{A} and {B} reveal their tumblr blogs to each other. {B} turns out to be {A}'s #1 tumblr crush.",
	'{B} drags {A} into the freezing cold to make a snowman.',
	'{A} and {B} sending each other sexy and silly selfies.',
	'Them meeting at the age of five years old on the first day of kindergarten.',
	'Them getting a puppy/kitty, and arguing over names.',
	"{A} being careful (or not at all careful) taking off {B}'s shirt because {B} is extremely ticklish.",
	"{A} taking {B} out for Valentine's Day to cheer them up after their original plans with someone else fell through. As {A} tries their best to make {B} happy and succeeds after only a few attempts, {B} realizes they would have rather been with {A} anyways.",
	'{B} hurt their ankle and is laid up with a cast and crutches. {A} is sitting next to them, doodling little hearts on their cast to cheer them up.',
	"{B} lends their sweater to {A}. When {A} is home, they realize they still have {B}'s sweater and find {B}'s iPod. Out of curiosity, {A} looks through {B}'s music and finds a playlist titled with {A}'s name.",
	'{A} is alone in the rain because they forgot to bring an umbrella, {B} offers to share theirs.',
	'{B} telling really dumb or corny jokes to {A}, thinking they are so clever and funny. {A} just thinks {B} is adorable for thinking the jokes are funny.',
	"{A} teaching {B} how to kiss, and {B} ends up kissing {A} really quick, nervously asks 'Like that?' and leaves {A} silent and flustered for a moment.",
	'{B} absolutely loves the taste of the chap stick/lip balm {A} uses, so they keep stealing kisses from {A}.',
	"{A} and {B} falling asleep together with their heads on the other's shoulder/head in the backseat of the car while their friend is driving.",
	'{B} holding a sobbing {A}. {A} cries themselves to sleep with their face buried into {B}.',
	'{A} and {B} sleeping on top of each other (in the bed, couch, where ever you prefer) when {B} flops down on the floor.',
	"{A} seeing some of {B}'s night blogging.",
	'{B} burns their tongue on something hot, {A} kisses it better.',
	"{B} is a prince or princess, falling for {A}, the castle gardener who tends to the foliage surrounding {B}'s balcony.",
	"{A} and {B} watching a horror movie. {A} can't sleep that night and {B} comforts them in a cuddle.",
	"{B} tossing snowballs at {A}'s window, not knowing the window is open and has no screen.",
	"{A} and {B} sleeping together. {A} wakes up first and contemplates waking {B} with a kiss.{A} leans in only to hesitate centimeters away out of embarrassment. {B} opens their eyes and says, 'Well if you won't do it, I will.'",
	'{B} gets the hiccups, causing {A} to laugh every time they try to talk until {A} gets the hiccups too.',
	'{A} and {B} not speaking each other languages, falling in love and learning together.',
	'{B} and {A} break up, but they have a pet and neither of them want to give it up. Then they spend a few days each with the pet separately. But it kinda helps them get together again.',
	'{A} and {B} dancing in the moonlight.',
	'{A} and {B} at a theme park or carnival, and walking towards one of the many games to win a large stuffed animal. {A} is sure that they can win the game, but after many attempts (and a lot of cash down the drain) {A} gives up. {B}, however, tries and succeeds on their first go.',
	'{B} and {A} eating spaghetti like the lady and the tramp did in that animated film.',
	"{B} is a ghost who falls in love with {A}, but {A} can't see them. Does {B} do anything to make {A} notice them?",
	'{A} and {B} unable to sleep after watching a horror movie, but neither will admit that the movie scared them.',
	'{B} and {A} play Twister. Things get embarrassing and awkward fast.',
	'{A} trying to get something on their computer to work. While they’re getting frustrated and flipping out, {B} is sitting nearby cracking up.',
	"{B} likes stealing {A}'s phone to change {A}'s phone wallpaper into something stupid (like unattractive pictures of {A}'s face or doing something like picking their nose). {B} is doing another routine swipe of {A}'s phone, but doesn't have the heart to change it because this time because {A}'s phone wallpaper is a cute picture of the two of them (like their first date together, or the only picture they have together).",
	"{A} cuddling with a body pillow, pretending that it's {B}...",
	'{B} getting shy about being naked in front of {A} for the first time.',
	'{A} getting to go back in time and change something bad that happened in their past with {B}.',
	'{A} has amnesia and {B} is taking care of them. {B} tries their best to help {A} remember them.',
	"{B} and {A} were separated for several years for reasons they couldn't help. They finally find each other and have a heartfelt reunion.",
	'{B} and {A} stranded on a raft in the middle of a lake.',
	"{A}'s mom gives {A} and {B} very cheesy, matching shirts/sweaters/scarfs. {B} does their very best to pretend that they love it.",
	'{B} having to help {A} undress after an injury.',
	'{A} and {B} adopting an orphan.',
	"{B} snuggling up to {A} because i's cold.",
	"{A} using {B}'s lap as a pillow.",
	'{B} buying {A} a special treat when they go out shopping.',
	'{A} giving {B} a tight hug that makes them lose their breath.',
	'{A} staying up half the night to finish a game with {B}.',
	'{B} giving {A} a back massage when they flop on the couch or bed.',
	'{B} making a goofy face until {A} notices and laughs.',
	'{A} letting {B} warm their cold hands under their shirt.',
	'{B} trying their best to be quiet while {A} is taking a nap.',
	'{A} helping {B} dry and brush their hair after a shower.',
	'{B} running out in the middle of the night to get a food item that {A} is craving.',
	'{A} wrapping a blanket around {B} when they are sitting on the couch and watching a show.',
	"{B} tucking {A}'s hair behind their ear to help them get it out of their face.",
	'{A} sharing a drink with {B} from the same straw.',
	"{A} doing a chore they know {B} isn't fond of.",
	"{B} wearing clothes in {A}'s favorite color.",
  '{A} and {B} sharing a really long scarf.',
	'{B} tracing their names together in the sand.',
	'{A} writing {B} name in a heart/under the love umbrella/etc. in their notebook together with their own name.',
	'{B} and {A} sharing a soft smile across a crowded room.',
	"{A} and {B} having a tickle fight until they're breathless.",
	'{B} calming {A} down when they have a bad dream.',
	"{A} playing their fingers through {B}'s hair while sitting next to them on the couch.",
	"{B} following {A}'s family traditions that they enjoy.",
	'{A} telling {B} a dumb joke just to see their smile.',
	"{A} participating in {B}'s hobby even if it doesn't personally interest them.",
	'{B} buying {A} something unrequested because it made {B} think of them.',
	'{B} lightly kissing {A} on top of a freshly formed bruise.',
	'{A} giving {B} a kiss before going to work and they are still in bed.',
	'{B} making {A} their favorite meal when they are having a hard day.',
	'{A} helping {B} dry and brush their hair after a shower.',
	'{B} traveling long distances just to see {A}.',
	'{B} tucking the sheets around {A} when they stir during the night.',
	"{B} holding {A}'s hands when they are shaking.",
	'{A} and {B} spending the night on the perfect hill for stargazing.',
	'{A} and {B} on a large field with a fresh foot of snow.',
	'{B} and {A} throwing food for the ducks at the duck pond.',
	'{B} and {A} sitting on the couch that is really soft and sinking into the cushions..',
	'{A} and {B} under a large fruit tree in the middle of summer.',
	'{B} and {A} playing games in the small arcade.',
	'{A} and {B} going to explore an abandoned house on the edge of town.',
	'{B} and {A} chilling out on beds and couches at a furniture store.',
	'{A} and {B} playing on the swings at a small playground that nobody goes to anymore.',
	'{A} and {B} lighting fall-scented candles.',
	'{B} and {A} carving faces in pumpkins.',
	'{A} and {B} making crafts.',
	'{A} and {B} decorating their house with seasonal decorations.',
	'{B} and {A} raking up leaves and jumping into them.',
	'{A} and {B} drowning in oversized sweaters during chilly days.',
	'{A} and {B} finger painting with their child.',
	"{A} and {B}'s child coming to sleep with them after having a bad dream.",
	'{A} and {B} remembering their first kiss… and they have very different takes on it.',
	'{B} hiding in a closet to jump out and surprise {A}, but {A} just keeps not going near the closet by chance.',
	'{B} and {A} making wishes.',
	'{A} and {B}  living together for the first time.',
	'{B} and {A} backpacking across the world.',
	'{B} and {A} texting. Or better yet, writing letters to each other.',
	"{A} and {B} holding hands because there's a crowd but not letting go when they get out of it.",
	'{A} having to rescue {B} from a pack of kittens/puppies.',
	"{A} and {B} meeting on a train when {B} falls asleep on {A}'s shoulder.",
	'{B} and {A} playing in water and splashing each other.',
	'{A} and {B} shopping, with one of them being way more excited about it than the other who just kinda drags around and carries their bags.',
	'They meet when {A} sees {B} walk into a street sign.',
	"{B} breaking into {A}'s room through their window.",
	'{A} and {B} cooking something without the recipe, because {B} is confident they know how to cook it from memory.',
	'{B} and {A} taking couple quizzes on the Internet.',
	'{A} is scared of the thunder and {B} tries to calm them down during an particulary heavy strom.',
	"{B} kissing away {A}'s tears.",
	'{A} and {B} sharing ice cream/cake/a dessert.',
	'{A}: guess what <br> {B}: what <br> {A}: i love you <br> {B}:  O:',
	'{A} and {B} are a pair of ghosts haunting a house, and every day they try to outcompete each other in scaring whoever comes in.',
	'{B} gets into a heated argument with someone. {B} begins threatening them, so {A}, picks up {B} and carries/drags them out of the room before anyone gets hurt.',
	'{A} and {B} becoming YouTubers/vloggers.',
	"{B} and {A} aren't together yet, but they like each other and they are mutuals on twitter/tumblr. {A} accidentally publishes a tweet/post about their crush on {B} on their main account, when they meant to put it on a private side account. {B} is too dense to realize it's obviously about them, but it still worries them enough to ask a rather mortified {A} about it.",
	'{A} is a special effects make-up artist and {B} always volunteers as their model when they want to try something new.',
	'{B} showing {A} some of their favorite viral videos/memes.',
	'{B} and {A} getting locked in a store.',
	"{B} getting up in the middle of the night to make a snack and accidentally waking up {A} because they didn't stop the microwaves obnoxious beeping in time.",
	'{A} and {B} burning something together.',
	'{B} and {A} wearing each other’s clothes.',
	'{A} and {B} just booping noses.',
	"{B} and {A} each other. {A} makes a spectacular drawing and {B}'s drawing does turn out to be that good. However, {A} keeps {B}'s drawing and treasures it.",
	'{A} and {B}  reading mean tweets/comments about themselves and laughing it off.',
	'{B} and {A} getting lost in IKEA.',
	"{B} trying to mooch off of {A}'s wifi and jokingly putting their own name in as the password, then being shocked that it actually works and they're now connected to {A}'s wifi...",
	'{A} having to comfort {B} because {B} just encountered a very large, unpleasant bug outside that scared them.',
	"{B} and {A} go on a camping trip. {B} forgets to bring a sleeping bag, so they have to squeeze into {A}'s sleeping bag with them.",
	'{B} catches a cold so {A} makes them breakfast in bed.',
	"{A} falling asleep in {B}'s lap. {B} holds {A} close and doesn't move from their spot for hours.",
	"{B} making a video 'proving' that {A} is the Illuminati, complete with The X-Files theme.",
	'{A} and {B} as characters in a really crappy free-to-play MMORPG with super skimpy armor.',
	'{B} giving {A} a piggyback ride.',
	'{A} princess carrying {B}.',
	"{B} and {A} as a superhero/sidekick duo, but {B} is constantly messing up and getting in {A}'s way during their crime-fighting missions.",
	"{A} and {B} going to a drive-thru fast food place. When they get home, it is discovered that the staff did not prepare {A}'s order properly. Despite {A} insisting they don't mind, {B} drives back to the fast food place to demand a new meal be made for {A}.",
	"{B}  trying to set up their character with {B}'s character in a life simulation game. After months of trying to get the two together, they scream in triumph when it finally works.",
	"{B} screaming over a picture of {A} from long before they met. {B} describes the younger {A} as a tiny precious child, then looks at {A}, and says 'Well, you're still a tiny precious child'.",
	'{B} and {A} attending a school for kids with disabilities.',
	'{A} and {B} trying to do a three legged race.',
	"{B} holding {A} very close, close enough to smell their hair. They whisper into {A}'s ear: 'I don't like your new shampoo'",
	"A friend drawing on {A} and {B}'s faces when they sleep. They wake up to see each other faces covered in silly doodles.",
	"{B} is playing a video game/reading a book/watching a show and is talking about how they ship two of the characters together because of [insert cute reason here], and then {A} says 'that sounds like you and me right there'.",
	'{A} hogs all the blankets and {B} gets cold so they cling tightly to {A} for warmth.',
	"{B}:I'm gonna do the thing <br>{A}:That's probably a bad idea <br>{B}:*does the thing* <br>{A}:holyshit.",
	'{A} and {B} discovering a hidden treasure.',
	'{A} coming home from a cuddly date with {B} and realizing that their shirt smells like {B}. {A} pulls their shirt up to their face to smell it before it fades away.',
	'{B} giving {A} a back massage when they flop on the couch or bed.',
	"{B} falls asleep in {A}'s lap and {A} has a conversation with someone else while stroking {B}'s hair as if they were a sleeping cat.",
	"{A} and {B} and their friends end up having to all sleep in the same room.  Nobody can get any sleep because {B} is snoring incredibly loud... Except for {A}, who's completely used to it.",
	'{B} and {A} wearing matching Halloween costumes or ugly Christmas sweaters. Or any matching outfits.',
	'{A} knitting something for {B}.',
	"{B} captioning everything {A} does with 'That's hot/cute'.",
	'{A} and {B} sucking helium and talking in very high-pitched voices.',
	"{B} reading in bed while {A} rests their head on {B}'s shoulder, sleeping.",
	"{A} goes over to {B}'s home after staying up all night. Even though they do their best to stay awake, they end up falling asleep while cuddling {B}. {A} is quite embarrassed (and half-asleep) when they wake up, but {B} doesn't mind.",
	'{A}:Ah shit <br>{B}Watch your fucking language',
	'{B} and {A} struggling to find each other in a crowded place. Fortunately, {B} knows just the thing.',
	"{B} and {A} carrying around balloons so they don't get lost in the crowd.",
	'{A} posts a picture of {B} somewhere and it becomes a meme.',
	"{B}: What am I supposed to do while you're gone <br>{A}: ... What do you usually do when I'm gone <br>{B}: Wait for you to come back",
	'{A} and {B} as the main characters in the last show you watched/book you read/game you played.',
	'{B} spending all their money on {A}, who scolds them for it.',
	'{A} and {B} playing a co-op video game and {A} keeps dicking around and {B} just wants to get past the first level god dammit.',
	"{B} staring admiringly at {A} from across the room. A friend whispers into {B}'s ear: 'Why are you so thirsty?'",
	"{A} booping {B}'s nose with their finger.",
	"{A} is a genie. {B} stumbles upon {A}, and they wish for {A} to be free so they can be {B}'s new friend. This seems awkward to {A} at first, but they warm up to {B} and end up crushing on them.",
	"{A} touching {B}'s face and telling them that their face is really soft.",
	'{B} and {A} are about to kiss when instead they accidentally hit foreheads really hard and have matching bruises.',
	'{A} giving {B} a kiss before going to work and they are still in bed.',
	"{B} telling {A} a story but {A} isn't paying attention at all because they;re too busy thinking about what a cutie {B} is.",
	"{A} is the barista at a coffee shop and always screws up {B}'s name on purpose.",
	'{B} and {A} getting sick at the same time.',
	'{B} sings extremely well but has a lot of difficulty playing musical instruments and {A} can play their musical instrument very well but their singing voice is terrible.',
	"{B} and {A} haven't kissed yet. Each time {B} sees {A} they think to themselves 'I've gotta do it this time' but they keep being too shy to do anything. One day a friend asks {B} if {A} has ever tried to kiss them and {B} just screams.",
	'{A} and {B} literally sitting in a tree, kissing..',
	'Imagine {A} and {B}.',
	"{B} pressing their forehead against {A}'s forehead to check if they have a fever.",
	"{B} reminiscing about the time they first met {A}. They're still in awe of how far they've come.",
	'{A} making {B} some hot chocolate.',
	'{B} and {A} having a snowball fight.',
	"{A} and {B} spending their New Year's Eve on a party with their friends and sharing their New Year's kiss in front of everyone.",
	'{B} and {A} walking through town, holding hands while it snows.',
	"{A} and {B} trying to hide their relationship. However, it turns out everyone knows they're dating.",
	'{B} makes breakfast for {A} after staying the night.',
	'{A} and {B} makes breakfast together, after spending the night together.',
	'{A} does house chores.',
	'{A} and {B} does chores around the house, dividing the work.',
	'{A} and {B} does chores around the house, but {B} slacks off.',
	'{B} is reading a book.',
	'{A} goes through their morning routine.',
	'{A} and {B} goes through their morning routine, chatting about the plans for the day.',
	'{A} goes through their bedtime routine.',
	'{A} and {B} goes through their bedtime routine, chatting about the things that happened during the day.',
	'{A} is grocery shopping.',
	'{A} and {B} is grocery shopping together and {A} keeps trying to buy random stuff.',
	'{A} leaves a note for {B}.',
	'{A} and {B} is packing for a trip together.',
	'{A} and {B} is packing for a trip together and {B} is procroastinating.',
	'{B} leaves for work/school/errands in the morning and says goodbye to {A}.',
	'{B} experiences disappointment.',
	'{A} celebrates an anniversary.',
	'{A} and {B} celebrates an anniversary.',
	'{A} and {B} share a hobby.',
	'{A} and {B} commute together.',
	'{B} commutes to work/school/errands.',
	'{A} and {B} try to stay cool on a hot day.',
	'The car breaks down.',
	'{A} has had an argument and {B} helps them calm down.',
	'{A} and {B} had an argument.',
	'{A} and {B} was caught in the middle of an argument.',
	'{A} is bored.',
	'{A} and {B} goes to the movies.',
	'{A} and {B} has a date night.',
	'{B} lost the keys.',
	'{A} has bad news.',
	'{B} has bad news for {A} and doesnt know how to break the news.',
	'{B} has good news for {A} and cant wait to share the news.',
	'{A} is standing in line for frozen yogurt, eavesdropping on two girls in line.',
	'{A} and {B} is standing in line for frozen yogurt, eavesdropping on two girls in line.',
	'{B} is daydreaming.',
	'{B} is waiting to be picked up.',
	'{B} teases someone and blames it on {A} before running away laughing.',
	'{A} approaches {B} to talk but gets flustered and leaves without saying a word.',
	'{A} is approached by {B} who stands there not saying a word, before leaving from getting flustered, confusing {A}.',
	'{B} gets embarrassed.',
	"{B}'s mind goes blank after {A} smiles at them.",
	"{A} gets sad when {B} isn't where they usually are.",
	'{B} is ignored by {A}.',
	'{A} and {B} share an umbrella.',
	'{A} forgets their umbrella.',
	'{A} and {B} has an afternoon tea together.',
	'{B} sees {A} and runs after them.',
	'{A} sees {B} and runs after them, scaring them from the sudden charge.',
	'{A} helps {B} lift the grocery bags.',
	"{B} show's an embarrassing photo to {A}.",
	'{A} prepares their home for {B} to come visit.',
	'{B} is extremely overjoyed from talking with/dating {A}.',
	'{B} jumps with joy.',
	'{A} wraps their jacket around {B} on a cold night.',
	'{A} wraps their jacket around {B} on a cold night, sharing the jacket together.',
	'{A} and {B} reaffirms their love.',
	'{A} takes funny photos of {B}.',
	'{B} secretly takes a picture of {A}.',
	'{B} gets sick.',
	'{B} takes care of a sick {A}.',
	'{B} has a nightmare.',
	'{A} consoles {B} after a nightmare.',
	"{A} doesn't want to take medicine, since it takes bad.",
	'{B} dances in the rain with an umbrella.',
	'{B} dances in the rain without an umbrella.',
	'{A} consoles {B} after an episode from mental scarring.',
	'{A} finds {B} waiting somewhere.',
	'Clothes got wet and has to be dried off.',
	'{B} unexpectantly hugs {a} to save them from something.',
	'{A} unexpectantly hugs {B} to save them from something and they linger.',
	'{A} and {B} hugs.',
	'{A} feeds {B}.',
	'{B} feeds {A} and share an indirect kiss.',
	'{A} thinks {B} is going to feed them and {B} laughs lovingly at {A}.',
	"{A} gets {B}'s phone number.",
	'{A} and {B} displays PDA.',
	'{A} and {B} is lovey-dovey in front of friends.',
	'{B} waits for {A} to show up on their usual route, pretending to just arrive but has secretly been waiting.',
	'{A} and {B} tries to get past each other in a doorway, awkwardly mirroring each other.',
	"{B} laughs at {A} and makes {A}'s heart skip a beat.",
	'{A} paints {B}.',
	'{A} confesses to {B}.',
	'{B} sends a message to {A}, lovingly reminding them of something minor.',
	'{B} and {A} takes a stroll through a park, enjoying the small things.',
	'After a long day, {A} invites {B} to a well-known lookout point late in the evening to enjoy the view over the city at night.',
	'{A} and {B} resting together and talking to each other before falling asleep.',
	
	"{B} and {A} exploring each others' bodies, but not in a sexual way. Finding their different birthmarks, looking over each others' scars and sharing the stories behind them, running their hands over one another and just appreciating the feeling of the other person next to them.",
	'{A} and {B} go to a fair/amusement park and {A} wants to go on the roller coaster and {B} agrees. Later, {B} regrets their decision and ends up clinging onto {A} for dear life.',
	'{B} and {A} are on a ferris wheel, and everything is going great - until it gets stuck at the very top. For thirty whole minutes.',
	'{B} prevents {A} from getting out of bed by cuddling them.',
	"{A} is about to leave for work. {B} asks them if they've forgotten anything, and {A} gives them a kiss. {B} turns red and opens their hand to reveal {A}'s keys/wallet/etc., saying 'I meant this, but thanks.'",
	"{A} and {B} playing with sidewalk chalk like they're kids again.",
	'{A} and {B} huddled by the fireplace at night after spending the day in the fresh snow.',
	"{B} and {A}'s first holiday season together.",
	'{B} wants to use their laptop on the couch, but {A} always occupies the space in their lap.',
	"{A} doesn't like talking on the phone, but {B} always calls them instead of texting. {B} admits that it's because they want to hear {A}'s voice.",
	'{A} wakes to find that it had snowed overnight and gets excited about playing in it. {B} gets excited because this means that when {A} comes inside, it will be time for cuddling by the fire.',
	'{B} drags {A} into the freezing cold to make a snowman.',
	'{B} and {A} adopting a pet, and arguing over potential names.',
	"{A} being careful (or not at all careful) taking off {B}'s shirt because {B} is extremely ticklish.",
	"{A} taking {B} out for Valentine's Day to cheer them up after their original plans with someone else fell through. As {A} tries their best to make {B} happy and succeeds after only a few attempts, {B} realizes they would have rather been with {A} anyways.",
	'{B} hurt their ankle and is laid up with a cast and crutches. {A} is sitting next to them, doodling little hearts on their cast to cheer them up.',
	"{B} lends their jacket to {A}. When {A} is home, they realize they still have {B}'s sweater and find {B}'s iPod. Out of curiosity, {A} looks through {B}'s music and finds a playlist titled with {A}'s name.",
	'{A} is alone in the rain because they forgot to bring an umbrella, {B} offers to share theirs.',
	'{B} telling really dumb or corny jokes to {A}, thinking they are so clever and funny. {A} just thinks {B} is adorable for thinking the jokes are funny.',
	"{A} teaching {B} how to kiss, and {B} ends up kissing {A} really quick, nervously asks 'Like that?' and leaves {A} silent and flustered for a moment.",
	'{B} absolutely loves the taste of the chap stick/lip balm {A} uses, so they keep stealing kisses from {A}.',
	"{A} and {B} falling asleep together with their heads on the other's shoulder/head in the backseat of the car while their friend is driving.",
	'{B} holding a sobbing {A}. {A} cries themselves to sleep with their face buried into {B}.',
	'{A} and {B} sleeping on top of each other (bed, couch, hammock, etc.) when {B} falls down on the floor.',
	"{A} and {B} watching a horror movie. {A} can't sleep that night and {B} comforts them in a cuddle.",
	"{B} tossing snowballs at {A}'s window, not knowing the window is open and has no screen.",
	'{B} gets the hiccups, causing {A} to laugh every time they try to talk until {A} gets the hiccups too.',
	'{B} and {A} break up, but they have a pet and neither of them want to give it up. Then they spend a few days each with the pet separately. But it kinda helps them get together again.',
	'{A} and {B} at a theme park or carnival, and walking towards one of the many games to win a large stuffed animal. {A} is sure that they can win the game, but after many attempts (and a lot of cash down the drain) {A} gives up. {B}, however, tries and succeeds on their first go.',
	'{A} and {B} unable to sleep after watching a horror movie, but neither will admit that the movie scared them.',
	'{A} trying to get something on their computer to work. While they’re getting frustrated and flipping out, {B} is sitting nearby cracking up.',
	"{B} likes stealing {A}'s phone to change {A}'s phone wallpaper into something stupid (like unattractive pictures of {A}'s face or doing something like picking their nose). {B} is doing another routine swipe of {A}'s phone, but doesn't have the heart to change it because this time because {A}'s phone wallpaper is a cute picture of the two of them (like their first date together, or the only picture they have together).",
	"{A} cuddling with a body pillow, pretending that it's {B}.",
	'{B} getting shy about being naked in front of {A} for the first time.',
	"{B} and {A} were separated for several years for reasons they couldn't help. They finally find each other and have a heartfelt reunion.",
	"{A}'s mom gives {A} and {B} very cheesy, matching shirts/sweaters/scarfs. {B} does their very best to pretend that they love it.",
	'{B} having to help {A} undress after an injury.',
	"{B} snuggling up to {A} because it's cold.",
	"{A} using {B}'s lap as a pillow.",
	'{B} buying {A} a special treat when they go out shopping.',
	'{A} giving {B} a tight hug that makes them lose their breath.',
	'{A} staying up half the night to finish a game with {B}.',
	'{B} giving {A} a back massage when they flop on the couch or bed.',
	'{B} making a goofy face until {A} notices and laughs.',
	'{B} trying their best to be quiet while {A} is taking a nap.',
	'{A} helping {B} dry and brush their hair after a shower.',
	'{B} running out in the middle of the night to get a snack that {A} is craving.',
	'{A} wrapping a blanket around {B} when they are sitting on the couch and watching a show.',
	"{B} tucking {A}'s hair behind their ear to help them get it out of their face.",
	'{A} sharing a drink with {B} from the same straw.',
	"{A} doing a chore they know {B} isn't fond of.",
	"{B} wearing clothes in {A}'s favorite color.",
	'{B} tracing their names together in the sand.',
	'{A} writing {B} name in a heart/under the love umbrella/etc. in their notebook together with their own name.',
	'{B} and {A} sharing a soft smile across a crowded room.',
	"{A} and {B} making out until they're breathless.",
	'{B} calming {A} down when they have a bad dream.',
	"{B} following {A}'s family traditions that they enjoy.",
	'{A} telling {B} a dumb joke just to see their smile.',
	"{A} participating in {B}'s hobby even if it doesn't personally interest them.",
	'{B} buying {A} something unrequested because it made {B} think of them.',
	'{B} lightly kissing {A} on top of a freshly formed bruise.',
	'{A} giving {B} a kiss before going to work and they are still in bed.',
	'{B} making {A} their favorite meal when they are having a hard day.',
	'{B} traveling long distances just to see {A}.',
	'{B} tucking the sheets around {A} when they stir during the night.',
	"{B} holding {A}'s hands when they are shaking.",
	'{A} and {B} spending the night on the perfect hill for stargazing.',
	'{B} and {A} throwing food for the ducks at the duck pond.',
	'{A} and {B} having a picnic under a large fruit tree in the middle of summer.',
	'{A} and {B} going to explore an abandoned house on the edge of town.',
	'{B} and {A} testing beds and couches at a furniture store.',
	'{A} and {B} playing on the swings at a small playground that nobody goes to anymore.',
	'{A} and {B} lighting fall-scented candles.',
	'{B} and {A} carving pumpkins.',
	'{A} and {B} making crafts and having a playful argument over their creative differences.',
	'{A} and {B} decorating their house with seasonal decorations.',
	'{A} and {B} drowning in oversized sweaters during chilly days.',
	"{A} and {B}'s child coming to sleep with them after having a bad dream.",
	'{A} and {B} remembering their first kiss… and they have very different takes on it.',
	'{B} hiding in a closet to jump out and surprise {A}, but {A} just keeps not going near the closet by chance.',
	'{B} and {A} tossing coins in a well and making wishes.',
	'{A} and {B}  living together for the first time.',
	'{B} and {A} texting.',
	'{A} and {B} writing letters to each other.',
	"{A} and {B} holding hands because there's a crowd but not letting go when they get out of it.",
	'{B} and {A} going swimming together.',
	'{A} and {B} shopping, with one of them being way more excited about it than the other who just kinda drags around and carries their bags.',
	"{B} sneaking into {A}'s room through their window.",
	'{A} and {B} cooking something without the recipe, because {B} is confident they know how to cook it from memory.',
	"{B} and {A} taking couple's quizzes on the Internet.",
	'{A} is scared of the thunder and {B} tries to calm them down during an particularly heavy storm.',
	'{A} and {B} sharing ice cream/cake/a dessert.',
	'{B} gets into a heated argument with someone. {B} begins threatening them, so {A}, picks up {B} and carries/drags them out of the room before anyone gets hurt.',
	'{B} and {A} getting locked in a store after closing.',
	"{B} getting up in the middle of the night to make a snack and accidentally waking up {A} because they didn't stop the microwave's obnoxious beeping in time.",
	"{B} and {A} are drawing each other. {A} makes a spectacular drawing and {B}'s drawing does turn out to be that good. However, {A} keeps {B}'s drawing and treasures it.",
	'{A} having to comfort {B} because {B} just encountered a very large, unpleasant bug outside that scared them.',
	"{B} and {A} go on a camping trip. {B} forgets to bring a sleeping bag, so they have to squeeze into {A}'s sleeping bag with them.",
	'{B} catches a cold so {A} makes them breakfast in bed.',
	"{A} falling asleep in {B}'s lap. {B} holds {A} close and doesn't move from their spot for hours.",
	'{B} giving {A} a piggyback ride.',
	"{A} and {B} going to a drive-thru fast food place. When they get home, it is discovered that the staff did not prepare {A}'s order properly. Despite {A} insisting they don't mind, {B} drives back to the fast food place to demand a new meal be made for {A}.",
	"{B} screaming over a picture of {A} from long before they met. {B} describes the younger {A} as a tiny precious child, then looks at {A}, and says 'Well, you're still a tiny precious child'.",
	"{B} holding {A} very close, close enough to smell their hair. They whisper into {A}'s ear: 'I don't like your new shampoo'",
	"A friend drawing on {A} and {B}'s faces when they sleep. They wake up to see each other faces covered in silly doodles.",
	'{A} hogs all the blankets and {B} gets cold so they cling tightly to {A} for warmth.',
	'{A} coming home from a cuddly date with {B} and realizing that their shirt smells like {B}. {A} pulls their shirt up to their face to smell it before it fades away.',
	"{B} falls asleep in {A}'s lap and {A} has a conversation with someone else while stroking {B}'s hair as if they were a sleeping cat.",
	"{B} reading in bed while {A} rests their head on {B}'s shoulder, sleeping.",
	"{A} goes over to {B}'s home after staying up all night. Even though they do their best to stay awake, they end up falling asleep while cuddling {B}. {A} is quite embarrassed (and half-asleep) when they wake up, but {B} doesn't mind.",
	'{A}: Ah shit <br>{B}: Watch your fucking language',
	"{B} and {A} carrying around balloons so they don't get lost in the crowd.",
	'AU: {A} and {B} as the main characters in the last show you watched/book you read/game you played.',
	'{B} spending all their money on {A}, who scolds them for it.',
	'{A} and {B} playing a co-op video game and {A} keeps dicking around and {B} just wants to get past the first level god dammit.',
	"{B} staring admiringly at {A} from across the room. A friend whispers into {B}'s ear: 'Why are you so thirsty?'",
	"{A} touching {B}'s face and telling them that their face is really soft.",
	'{B} and {A} are about to kiss when instead they accidentally hit foreheads really hard and have matching bruises.',
	"{B} telling {A} a story but {A} isn't paying attention at all because they're too busy thinking about what a cutie {B} is.",
	"AU: {A} is the barista at a coffee shop and always screws up {B}'s name on purpose.",
	'{B} and {A} getting sick at the same time.',
	'{B} sings extremely well but has a lot of difficulty playing musical instruments and {A} can play their musical instrument very well but their singing voice is terrible.',
	"{B} and {A} haven't kissed yet. Each time {B} sees {A} they think to themselves 'I've gotta do it this time' but they keep being too shy to do anything. One day a friend asks {B} if {A} has ever tried to kiss them and {B} just screams.",
	"{B} pressing their forehead against {A}'s forehead to check if they have a fever.",
	"{B} reminiscing about the time they first met {A}. They're still in awe of how far they've come.",
	'{A} making {B} some hot chocolate.',
	'{B} and {A} having a snowball fight.',
	"{A} and {B} spending their New Year's Eve on a party with their friends and sharing their New Year's kiss in front of everyone.",
	'{B} and {A} walking through town, holding hands while it snows.',
	"{A} and {B} trying to hide their relationship. However, it turns out everyone knows they're dating.",
	"{B} and {A} battling against each other. Whether it's serious or playful is up to you...",
	'{B} and {A} being brought together by their mutual love for a third party, only to slowly develop feelings for each other over time.',

	'{B} showing {A} some of their favorite vines and memes.',
	'{B} has worked up the courage to propose to {A}.  day they go to propose, though, {A} gets on one knee, and holds out a ring.',
	'AU: {A} and {B} meet in university at one of the neighboring restaurants when they both realize they’re skipping the same class.',
	'AU: They are high school students. {B} gets detention. {A}, not wanting to be alone, joins them.',
	'{A} and {B} in high school, staying up all night together to study for a big test the next day.',
	'{A} and {B} going to Build-A-Bear.',
	'{A} and {B} going on social media and finding all of your posts about them.',
	'AU: {B} and {A} met when they moved into the same town in the Animal Crossing universe. (What species each of them are is totally up to you.)',
	'{B} is trying to impress {A} and ends up falling flat on their face. As {B} lays on the ground and slowly die from embarrassment, {A} has a mind blowing realization that they actually really like {B} and when they help {B} up off the ground, they pull them into a kiss.',
	"{A} is chewing the last piece of gum in a really good pack so {B} pulls them into a kiss to lowkey steal it out of {A}'s mouth",
	"{B} and {A} hosting a holiday open-mic night and performing 'Baby It's Cold Outside' together",
	"AU: {A} and {B} are neighbors and they don't necessarily like/notice each other at first, but {B} gets kittens and {A} comes over just to spend some time with them and it charms {B}'s heart.",
	"{B} gets locked out of their house while their family is gone, so they spend the night at {A}'s place.",
	"Before they started dating, {A} and {B} are best friends. Like the best friends that have known each other since they were in diapers. Whenever {A} would get upset, hurt or just really tired, they would snuggle up on {B} and nuzzle their face into the crook of {B}’s neck. It’s completely platonic, nothing romantic about it whatsoever. <br>When {A} and {B} finally confess their feelings for one another and begin dating, {A} immediately snuggles up in 'their' spot on {B} and just completely relaxes. {B} asks why they always do this, and {A} replies that it makes them feel safe and calm.",
	"{A} can't sleep without {B} by their side.",
	'{B} and {A} going on a nice walk in the woods when it suddenly starts to downpour.',
	'{A} and {B} slow dancing with no music, arms wrapped tightly around each other, breath mingling.',
	'{B} and {A} sharing soft kisses, lips barely touching, just chaste little things that leave both parties irrationally breathless.',
	'{B} helping {A} with simple tasks, like brushing their hair, or putting on jewelry, where it’s obviously an excuse to be close to each other, but neither are complaining.',
	'{A} and {B} pressing their faces together sleepily, not even kissing, just resting their foreheads together, noses brushing, breathing each other in.',
	'{B} smiling shyly, cheeks tinging pink, because they were caught staring at {A}.',
	'{A} and {B} playing joyous and silly music to dance around the living room to.',
	"{B} and {A} going out for coffee one morning and {A} already knows {B}'s order by heart.",
	'{B} kissing {A} under the rain without an umbrella after a silly argument, proceeding to giggle it out.',
	"{A} has been planning to propose for a while, they've bought the ring and everything. One day, they somehow lose the ring only for {B} to unexpectedly find it. Bonus: {B} questions a flustered {A} about the ring. Bonus 2: {B} uses the ring to propose instead.",
	"{B} looks at {A} and gently cups their face to examine it. {A} is a little confused and asks what's {B} doing. 'Hold on, there's something on your face,' {B} responds and then kisses {A}. 'It was me.' <br>{A} becomes red and flustered.",
	'{B} returning the engagement ring they got for {A} to the jeweller. Not because {A} said no, but because {A} had worked up the courage to propose before {B} did.',
	'{A} and {B} go separately to a New Year’s Party, and end up standing next to each other during the countdown to midnight.',
	'{B}  makes a New Year’s Resolution – but {A} makes it difficult for them to keep it.',
	'{B} gets confetti in their hair. {A} notices.',
	'{A} loves to dance at parties - {B} not so much.',
	"Someone 'accidentally' left the Christmas misteltoe up at a New Year’s Eve party attended by both {B} and {A}.",
	"On New Year's Eve, {A} and {B} reflect on their entire year together.",
	'{B} has never seen {A} in a tuxedo/ball gown before.',
	'{A} makes an unexpected toast in honor of {B}.',
	'{A} and {B} in the morning after a one night stand.',
	"{A} and {B} are in an established long distance relationship, {A} surprises {B} by showing up right before midnight on New Year's Eve.",
	'{A} comes back home to see the mess {B} made in the kitchen trying to cook for them.',
	'{B} heroically saving {A} from a spider by picking it with a glass and throwing it outside.',
	'{A} and {B} hanging out in a garden/field of wildflowers and making flower crowns for each other.',
	'{A} trying their hardest to prank {B}, but they fail each and every single time.',
	'{B} keeps asking weird/strange existential (or otherwise way too deep for 1am) questions and {A} only wants to go to sleeep.',
	'{A} and {B} having water baloon/water gun fight.',
	"{B} finding this prompt generator and putting up their name together with {A}'s name and reacting to the prompts they get.",
	'{A} and {B} singing a duet together.',
	'{A} comes out as trans. {B} does their best to support them.',
	'{B} and {A} tell each other how they miss one another.',
	'{A} and {B} getting married.',
	'{A} and {B} making crafts that remind them of one another.',
	'{B} and {A} started out hating each other but slowly started developing feelings for one another.',
	"{B} wakes {A} at 4 am because they wants someone to eat cereal with. {A} questions why, but {B} surprises them and says 'I just wanted a reason to be with you, is all...'",
	"{A}: It's going to be Christmas soon, {B}. {B}: So what, {A}.",
	'{A}: First of all you just ignored my cats dressed up as Santa, so fuck you. Secondly, <br>[{A} is typing...]',
	'{A} and {B} going star gazing at the observatory.',
	'{B} and {A} staying home and ordering take out bc it’s too hot outside.',
	'{B} and {A} staying in a small town and exploring the little shops and cute restaurants.',
	'{A} and {B} camping beside a lake and going swimming as the sun sets.',
	'{B} and {A} roasting marshmallows on a fire.',
	'{A} and {B} cuddling under the stars.',
	"{B}:*Kisses {A}'s forehead*<br>{A}:*frowns* You missed<br>{B}:...?<br>{A}:*Leans forward and kisses {B}'s lips*",
	'{A}: Goodbye.',
	'{B}: I always knew it would end like this.',
	'{B}: I don’t want to be alone right now.',
	'{B}: I’ve got you now.',
	"{B}: I love you <br> {A}: *shoving laundry basket into {B}'s hands* stop saying I love you to get out of chores",
	'{A} and {B} going camping',
	'{B} and {A} on a shopping date',
	'{A}: Don’t worry, I’ve been arrested before. I’ll get us out of this.',
	'{A}: I love you. <br> {B}: Pathetic.',
	'{B}: I know that I hurt you. I know that nothing I can say will change the past. But…I’m hoping that you’ll forgive me in the end. I’m hoping that I can make this right.',
	'{B}: Do you hate me or something? <br>{A}: Not at all. I’m actually quite in love with you, really.',
	'{A} and {B} are pretending to be married because they want a discount on a vacation special to an expensive resort. What happens? Do they get found out?',
	'{A} and {B} go to school together. {A} got {B} a huge ass teddy bear for a special occassion and {B} is mad cause they have to carry it around all day.',
	'{A} and {B} decide to do a partner costume! Who or what would they dress up as?',
	'{B} and {A} getting matching tattoos',
	'{A} and {B} falling asleep under the stars together... Only to wake up covered in bug bites.',
	'{B} and {A} sleeping together for the first time.  No sex, just sleeping.  When {B} wakes up, they see {A} still asleep. {B} smiles and wakes them up with a sweet kiss. {A}, once aware of what’s happening, kisses back.',
	'{A} and {B} are lost in the woods together.',
	"Imagine the big, bright smile on {B}'s face when {A} finally says ‘I love you’ for the first time.",
	"{A} runs across the road to pet {B}'s pet.",
	'{B} is playing a video game even though they’re really tired. They end up falling asleep during the game. {A} walks up and sees {B} sleeping peacefully, and falling out of their hands, a controller/handheld. Instead of waking up {B} or turning off the game, {A} picks up the controller/handheld and begins to play.',
	'{A} gets addicted to painting nails and forces {B} to let their nails get painted on.',
	'{B} and {A} have to work with each other on a psychology project. A psychology project on attraction.',
	"Imagine {A} wants to spice up their and {B}'s romance life and tries all sorts of cheesy tactics such as candlelit dinners, bringing fruit and whipped cream into the bedroom, sexy underwear... whether they fail or not in their romancing is another question...",
	"{A} and {B} getting dressed in the morning, {B} however is feeling a bit playful and decides to hold a piece of {A}'s clothing hostage so {A} has to try and get it back",
	'{B} and {A} as friends in school before they’re together. They awkwardly use each other to learn how to/practice kissing and end up making out passionately until their mouths are sore.',
	"{A} dressed up as a sexy cop for Halloween and {B} keeps surrendering to {A} by saying 'I've been very bad, you should arrest me.'",
	"{A}: You  don’t  have  to  hide  your  tears  from  me, {B}. It's okay.",
	'{B} waking {A} up with gentle kisses.',
	'{A} spontaneously kissing {B}.',
	'{B} holding {A} close.',
	'{B} gesturing at {A} to come closer.',
	"{A} grabbing {B}'s arm or hiding behind {B} because something scared them.",
	'{A} touching {B} as a show of affection/reassurance.',
	"{B} showing up at {A}'s house without explanation.",
	"{A} treating {B}'s injury.",
	'{B} getting hurt protecting {A}.',
	'{B} tickling {A}.',
	"{A} massaging {B}'s shoulders.",
	"{B} kissing {A}'s neck.",
	'{B} and {A} sharing a bath.',
	'{A} and {B} in the shower together, purely enjoying the company of each other.',
	"{B} putting flowers in {A}'s hair.",
	'{A}: You look tense, lie down and I’ll give you a massage.',
	'{A}: Your nose gets so pink during winter...I have to kiss it.',
	'{B}: Sorry, I didn’t know you were awake, you just looked so cute and I wanted to kiss you.',
	'{B}: I like tracing the lines in your palm, it’s...distracting.',
	'{B}: It’s just so easy to pick you up!',
	'{A}: Do you want to join me in my blanket fort?',
	'{B}: ...so that’s where all the pillows went. Mind if I lay with you?',
	'{A}: Your skin is so soft...',
	'{A}: My shirt is way too big on you...but it’s cute.',
	'{A}: I don’t know how we keep ending up in each other’s beds...',
	'{A}: You know, I really like your eyes, {B}.',
	'{A} and {B} going for an incredibly late night walk.',
	"{B} puts {A}'s favorite movie on for a movie night.",
	'{A} offers {B} their favorite snack/drink/etc.',
	'{B} gently drapes a blanket over {A} and kisses their forehead while they’re half-asleep.',
	'{A} runs {B} a relaxing bath after a long and difficult day.',
	'{B} is experiencing a moment of great joy – only for {A} to suddenly arrive with devastating news.',
	'{B} has become bitter and, well, rather prickly, and {A} is trying to find out why they are acting so out-of-character so suddenly.',
	'{B} is suffering in the summer heat, and {A} is left desperately trying to cool them down.',
	'{A} has to face their worst fear, and {B} must help them through the experience.',
	'{A} is feeling terrible self-doubt, and {B} must try to encourage them.',
	"{A} brushes something off of {B}'s face (eyelash, food crumb, etc.)",
	'{B} shares a drink or a snack with {A}.',
	'{A} helps {B} shave.',
	'{A} applying make up on {B}.',
	'{B} helping {A} wash up (whether it be their hair, body, some blood off their hands, etc.)',
	'{B} giving {A} a smile after making eye contact.',
	'{A} offering {B} a hand to help them with a step.',
	"{B} brushes a thumb over {A}'s cheek.",
	'{A} and {B} slow dance together.',
	'{B} offers {A} a place to stay.',
	'{A} gently kisses {B} on the nose.',
	'{B} gets a call from {A} in the middle of the night.',
	'{B} and {A} celebrate something together.',
	'{B} interlaces their fingers with {A}.',
	'{A} picks a flower for {B}.',
	'{B} makes {A} a hot beverage on a cold day.',
	'{A} is feeling out of it and need constant attention from {B}.',
	"{B} collapsing into {A}'s waiting arms.",
	'{A} picking {B} up.',
	'{A} calling {B} soft things like baby, sweetheart or honey.',
	'{A} waking up in the middle of the night to find {B} still working. {A} has to drag {B} back to bed.',
	"{B} waking up in the middle of the night to find that {A} isn't in their bed.",
	"{B} mumbling {A}'s name and reaching out for them.",
	"{A} has a fever. {B} takes care of them and lovingly runs their fingers through {A}'s sweaty hair.",
	'{A} says something to {B} that strikes a nerve.',
	'{A} witnesses {B} having a panic attack, flashback, or hallucination.',
	'{B} accidentally discovers a secret about {A}.',
	'{A} and {B} have a good, hard cry together.',
	'{A} comes home to find {B} snooping through their things.',
	'{A} tries convincing {B} to run away with them to an undisclosed location.',
	'{A}: There isn’t a word in the dictionary that can explain your type of beauty.',
	'{B}: Can you send me a picture? I want to prove to all of my friends that angels really do exist.',
	'{B}: Of all the stars in the sky, there are none as beautiful as you.',
	'{A}: To be honest, I just wanted a chance to look at the stars with you.',
	'{B}: I’m a child of God, I don’t do that shit.',
	'{A} is a great cook, but {B} rarely cooks. To surprise them, {B} tries to make them something. Emphasis on tries.',
	'{B} teaching {A} how to cook.',
	"It's {B}'s birthday and they have a nice, lazy, sleepy lie-in. {A} decides to cook {B} breakfast in bed and cooks all of {B}'s favourite food. {B} is delighted and showers {A} with kisses.",
	'{A} and {B} deciding to watch a movie together. They decide to cook up some popcorn to share, but end up arguing over how their popcorn should be prepared. {B} likes unsalted, buttered popcorn, but {A} likes theirs salty and butter-free. They spend more time arguing over how to eat their popcorn than they do watching their movie (or even deciding on a movie). Is there any hope they can solve their situation?',
	'{A} is the cook of the family. {B} can not cook but wants to give {A} a break. Whether or not they succeed is up to you.',
	'{B} and {A} talking about their feelings in a healthy and positive space, without judgement, learning more about each other and deepening the bonds of trust that bind them together.',
	"{A} and {B} are married, and offer to babysit their friends' kid, not realizing how much of a challenge it would be.",
	'{A} and {B} decorating a Christmas tree together.',
	'{A} and {B} attending a pride parade.',
	"{B} asleep and accidentally moaning {A}'s name while they're still awake beside {B}.",
	'{B} and {A} playing games in the small arcade in their neighborhood.',
	"{A} and {B} getting a little too drunk at a New Year's Eve party.",
	"{A} running their fingers through {B}'s hair while sitting next to them on the couch.",
	'{A} letting {B} warm their cold hands under their shirt.',
	'{B} and {A} play Twister. Do things get embarrassing? Do things get steamy?',
	'{A} and {B} at a late-night gathering after everyone else has gone home, dancing in the moonlight.',
	"{A} and {B} spending the night together. {A} wakes up first in the morning and contemplates waking {B} with a kiss.{A} leans in only to hesitate centimeters away out of embarrassment. {B} opens their eyes and says, 'Well if you won't do it, I will.'",
	'{B} burns their lip on something hot, {A} kisses it better.',
	'{B} and {A} accidentally dozing off in a hammock together as the sun sets and the air cools down.',
	'{A} and {B} making out so vigorously and passionately that when they’re eventually done, it looks as though they had both just stepped out of the shower.'
];

export default prompts;
