const sliceOfLifePrompts = [
  '{A} makes breakfast for {B} after staying the night.',
  '{B} makes breakfast for {A} after staying the night.',
  '{A} and {B} makes breakfast together, after spending the night together.',
  '{A} does house chores.',
  '{B} does house chores.',
  '{A} and {B} does chores around the house, dividing the work.',
  '{A} and {B} does chores around the house, but {B} slacks off.',
  '{A} is reading a book.',
  '{B} is reading a book.',
  '{A} goes through their morning routine.',
  '{B} goes through their morning routine.',
  '{A} and {B} goes through their morning routine, chatting about the plans for the day.',
  '{A} goes through their bedtime routine.',
  '{B} goes through their bedtime routine.',
  '{A} and {B} goes through their bedtime routine, chatting about the things that happened during the day.',
  '{A} is grocery shopping.',
  '{B} is grocery shopping.',
  '{A} and {B} is grocery shopping together and {A} keeps trying to buy random stuff.',
  '{A} and {B} is grocery shopping together and {B} keeps trying to buy random stuff.',
  '{A} leaves a note for {B}.',
  '{B} leaves a note for {A}.',
  '{A} and {B} is packing for a trip together.',
  '{A} and {B} is packing for a trip together and {A} is procroastinating.',
  '{A} and {B} is packing for a trip together and {B} is procroastinating.',
  '{A} leaves for work/school/errands in the morning and says goodbye to {B}.',
  '{B} leaves for work/school/errands in the morning and says goodbye to {A}.',
  '{A} experiences disappointment.',
  '{B} experiences disappointment.',
  '{A} celebrates an anniversary.',
  '{B} celebrates an anniversary.',
  '{A} and {B} celebrates an anniversary.',
  '{A} and {B} share a hobby.',
  '{A} and {B} commute together.',
  '{A} commutes to work/school/errands.',
  '{B} commutes to work/school/errands.',
  '{A} and {B} try to stay cool on a hot day.',
  'The car breaks down.',
  '{A} has had an argument and {B} helps them calm down.',
  '{B} has had an argument and {A} helps them calm down.',
  '{A} and {B} had an argument.',
  '{A} and {B} was caught in the middle of an argument.',
  '{A} is bored.',
  '{B} is bored.',
  '{A} and {B} goes to the movies.',
  '{A} and {B} has a date night.',
  '{A} lost the keys.',
  '{B} lost the keys.',
  '{A} has bad news.',
  '{B} has bad news.',
  '{A} has bad news for {B} and doesnt know how to break the news.',
  '{B} has bad news for {A} and doesnt know how to break the news.',
  '{A} has good news for {B} and cant wait to share the news.',
  '{B} has good news for {A} and cant wait to share the news.',
  '{A} is standing in line for frozen yogurt, eavesdropping on two girls in line.',
  '{B} is standing in line for frozen yogurt, eavesdropping on two girls in line.',
  '{A} and {B} is standing in line for frozen yogurt, eavesdropping on two girls in line.',
  '{A} is daydreaming.',
  '{B} is daydreaming.',
  '{A} is waiting to be picked up.',
  '{B} is waiting to be picked up.',
  '{A} teases someone and blames it on {B} before running away laughing.',
  '{B} teases someone and blames it on {A} before running away laughing.',
  '{A} approaches {B} to talk but gets flustered and leaves without saying a word.',
  '{B} approaches {A} to talk but gets flustered and leaves without saying a word.',
  '{A} is approached by {B} who stands there not saying a word, before leaving from getting flustered, confusing {A}.',
  '{B} is approached by {A} who stands there not saying a word, before leaving from getting flustered, confusing {B}.',
  '{A} gets embarrassed.',
  '{B} gets embarrassed.',
  "{A}'s mind goes blank after {B} smiles at them.",
  "{B}'s mind goes blank after {A} smiles at them.",
  "{A} gets sad when {B} isn't where they usually are.",
  "{B} gets sad when {A} isn't where they usually are.",
  "{A} is ignored by {B}.",
  "{B} is ignored by {A}.",
  "{A} and {B} share an umbrella.",
  "{A} forgets their umbrella.",
  "{B} forgets their umbrella.",
  "{A} and {B} has an afternoon tea together.",
  "{A} sees {B} and runs after them.",
  "{B} sees {A} and runs after them.",
  "{A} sees {B} and runs after them, scaring them from the sudden charge.",
  "{B} sees {a} and runs after them, scaring them from the sudden charge.",
  "{A} helps {B} lift the grocery bags.",
  "{B} helps {A} lift the grocery bags.",
  "{A} show's an embarrassing photo to {B}.",
  "{B} show's an embarrassing photo to {A}.",
  "{A} prepares their home for {B} to come visit.",
  "{B} prepares their home for {A} to come visit.",
  "{A} is extremely overjoyed from talking with/dating {B}.",
  "{B} is extremely overjoyed from talking with/dating {A}.",
  "{A} jumps with joy.",
  "{B} jumps with joy.",
  "{A} wraps their jacket around {B} on a cold night.",
  "{B} wraps their jacket around {A} on a cold night.",
  "{A} wraps their jacket around {B} on a cold night, sharing the jacket together.",
  "{B} wraps their jacket around {A} on a cold night, sharing the jacket together.",
  "{A} and {B} share a light kiss.",
  "{B} and {A} share a passionate kiss.",
  "{A} and {B} reaffirms their love.",
  "{A} takes funny photos of {B}.",
  "{B} takes funny photos of {A}.",
  "{A} secretly takes a picture of {B}.",
  "{B} secretly takes a picture of {A}.",
  "{A} gets sick.",
  "{B} gets sick.",
  "{A} takes care of a sick {B}.",
  "{B} takes care of a sick {A}.",
  "{A} has a nightmare.",
  "{B} has a nightmare.",
  "{A} consoles {B} after a nightmare.",
  "{B} consoles {A} after a nightmare.",
  "{A} doesn't want to take medicine, since it takes bad.",
  "{B} doesn't want to take medicine, since it takes bad.",
  "{A} dances in the rain with an umbrella.",
  "{B} dances in the rain with an umbrella.",
  "{A} dances in the rain without an umbrella.",
  "{B} dances in the rain without an umbrella.",
  "{A} consoles {B} after an episode from mental scarring.",
  "{B} consoles {A} after an episode from mental scarring.",
  "{A} finds {B} waiting somewhere.",
  "{B} finds {A} waiting somewhere.",
  "Clothes got wet and has to be dried off.",
  "{A} unexpectantly hugs {B} to save them from something.",
  "{B} unexpectantly hugs {a} to save them from something.",
  "{A} unexpectantly hugs {B} to save them from something and they linger.",
  "{B} unexpectantly hugs {a} to save them from something and they linger.",
  "{A} and {B} hugs.",
  "{A} feeds {B}.",
  "{B} feeds {A}.",
  "{A} feeds {B} and share an indirect kiss.",
  "{B} feeds {A} and share an indirect kiss.",
  "{A} thinks {B} is going to feed them and {B} laughs lovingly at {A}.",
  "{B} thinks {A} is going to feed them and {A} laughs lovingly at {B}.",
  "{A} gets {B}'s phone number.",
  "{B} gets {A}'s phone number.",,
  "{A} and {B} displays PDA.",
  "{A} and {B} is lovey-dovey in front of friends.",
  "{A} waits for {B} to show up on their usual route, pretending to just arrive but has secretly been waiting.",
  "{B} waits for {A} to show up on their usual route, pretending to just arrive but has secretly been waiting.",
  "{A} and {B} tries to get past each other in a doorway, awkwardly mirroring each other.",
  "{A} laughs at {B} and makes {B}'s heart skip a beat.",
  "{B} laughs at {A} and makes {A}'s heart skip a beat.",
  "{A} paints {B}.",
  "{B} paints {A}.",
  "{A} confesses to {B}.",
  "{B} confesses to {A}.",
  "{A} sends a message to {B}, lovingly reminding them of something minor.",
  "{B} sends a message to {A}, lovingly reminding them of something minor.",
];

export default sliceOfLifePrompts